import type { MailEntry } from "@takt/domain";
import { pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // undoDone
  undoneBody: "Tags und Status ändern sich dadurch nicht.",
  undoFailed: "Das Zurücknehmen hat nicht geklappt",
  undo: "Rückgängig",
  openAgain: (title: string) => `${title} ist wieder offen.`,

  // attachmentLabel (A-19.9, A-19.10 wording)
  attachmentKind: { link: "Verweis", image: "Bild", file: "Datei" },
  attachmentValue: { link: "Adresse", image: "Bild", file: "Dateipfad" },
  // AttachmentFormDialog
  valueMissing: {
    link: "Ohne Adresse lässt sich der Anhang nicht öffnen.",
    image: "Ohne Bild lässt sich der Anhang nicht öffnen.",
    file: "Ohne Dateipfad lässt sich der Anhang nicht öffnen.",
  },
  pickCancelled: "Auswahl abgebrochen.",
  typePathByHand: (reason: string) => `${reason} Tragen Sie den vollständigen Pfad von Hand ein — SuperTakt prüft ihn genauso.`,
  attachmentAdded: "Anhang hinzugefügt.",
  attachmentAddedBody: "Entfernen über das Papierkorbsymbol in der Zeile.",
  addAttachment: "Anhang hinzufügen",
  addAttachmentLead: "Ein Verweis, ein Bild oder eine Datei, die zu diesem Todo gehört.",
  add: "Hinzufügen",
  kind: "Art",
  linkPlaceholder: "https://…",
  linkHint: "Nur „http“ und „https“. SuperTakt speichert die Adresse, nicht die Seite.",
  imagePathPlaceholder: "Pfad der Bilddatei",
  filePathPlaceholder: "Vollständiger Pfad zur Datei",
  imageHint: "SuperTakt legt eine Kopie neben seinen Daten ab. Verschieben Sie die Quelle später, bleibt das Vorschaubild.",
  fileHint: "SuperTakt merkt sich den Pfad und kopiert nichts. Verschwindet die Datei, sagt der Anhang das.",
  choose: "Auswählen …",
  title: "Titel",
  titleHint: "Optional. Ohne Titel steht in der Liste ein lesbares Stück der Adresse beziehungsweise des Pfades.",
  // AttachmentRow
  previewUnreadable: (label: string) => `Vorschaubild nicht lesbar: ${label}`,
  noLongerReadable: "Nicht mehr lesbar",
  preview: (label: string) => `Vorschaubild: ${label}`,
  fromEmail: "Aus einer E-Mail",
  fromEmailBy: "Aus einer E-Mail von ",
  // Same word as in the task pane (A-19.22b).
  rebuilt: "(nachgebaut)",
  openAttachment: (kind: string, label: string, rebuilt: boolean) => `${kind} öffnen: ${label}${rebuilt ? " (nachgebaut)" : ""}`,
  removeAttachment: (kind: string, label: string) => `${kind} entfernen: ${label}`,
  // Attachments: sentences for the shell's refusal keys (locked sentences SP-13)
  refusal: {
    link_empty: "Dieser Verweis hat keine Adresse.",
    link_too_long: "Diese Adresse ist zu lang, um sie zu öffnen.",
    link_control_character: "Diese Adresse enthält unsichtbare Steuerzeichen. SuperTakt öffnet sie nicht.",
    link_unparsable: "Diese Adresse lässt sich nicht lesen.",
    link_scheme_rejected:
      "Diese Adresse lässt sich nicht öffnen: SuperTakt öffnet nur „http“ und „https“. Ein Netzwerkpfad ist keine Adresse, sondern eine Anmeldung an einem fremden Rechner.",
    link_not_normalized:
      "Diese Adresse steht nicht in der Form, die SuperTakt beim Anlegen erzeugt. Sie wird nicht geöffnet — sonst stünde hier eine andere Adresse, als geöffnet würde.",
    link_no_host: "Dieser Adresse fehlt der Rechnername.",
    link_userinfo:
      "Diese Adresse trägt Zugangsdaten vor dem Rechnernamen. Sie sieht dann nach einem anderen Ziel aus, als sie ansteuert, und wird nicht geöffnet.",
    path_empty: "Dieser Anhang hat keinen Pfad.",
    path_too_long: "Dieser Pfad ist zu lang, um ihn zu öffnen.",
    path_control_character: "Dieser Pfad enthält unsichtbare Steuerzeichen. SuperTakt öffnet ihn nicht.",
    path_unc:
      "Dieser Pfad zeigt auf eine Netzwerkfreigabe. SuperTakt öffnet keine, weil ein solcher Zugriff zugleich eine Anmeldung an einem fremden Rechner ist.",
    path_not_absolute: "Dieser Pfad ist nicht vollständig. SuperTakt öffnet nur vollständige Pfade.",
    path_stream_separator:
      "Der Dateiname trägt einen Doppelpunkt. Unter Windows benennt er einen zweiten Datenstrom derselben Datei — geöffnet würde dann nicht das, was hier steht. SuperTakt öffnet ihn deshalb nicht.",
    path_indirect_extension:
      "Diese Datei ist eine Verknüpfung. Ihr Ziel steht woanders — die Rückfrage könnte darüber nicht die Wahrheit sagen, deshalb öffnet SuperTakt sie nicht.",
    path_missing: "Diese Datei ist an diesem Pfad nicht mehr vorhanden.",
  } as Readonly<Record<string, string>>,
  refusedUnknown: "SuperTakt hat das Öffnen abgewiesen. Der Anhang bleibt bestehen; der Grund lässt sich hier nicht genauer benennen.",
  openFailed: "Das Öffnen ist fehlgeschlagen. Möglicherweise ist auf diesem Rechner keine Anwendung dafür eingerichtet.",
  attachmentRemoved: "Anhang entfernt.",
  attachmentRemovedBody: (label: string) => `${label} gehört nicht mehr zu diesem Todo.`,
  attachmentsLoading: "Anhänge werden geladen",
  attachmentsFailed: "Die Anhänge ließen sich nicht laden",
  noAttachments: "Keine Anhänge",
  noAttachmentsBody: "Ein Verweis, ein Bild oder eine Datei, die zu diesem Todo gehört. SuperTakt kopiert nur Bilder; Verweise und Dateien merkt es sich als Adresse beziehungsweise Pfad.",
  attachments: "Anhänge",
  removeTitle: "Anhang entfernen",
  removeLead: (label: string, todo: string) => `${label} gehört danach nicht mehr zu ${todo}.`,
  removeImage: "Die Kopie des Bildes im Datenverzeichnis von SuperTakt wird mit gelöscht. Die Datei, aus der sie stammt, bleibt unberührt.",
  removeOther: "SuperTakt vergisst die Adresse beziehungsweise den Pfad. Die Datei oder die Seite dahinter bleibt unberührt.",
  remove: "Entfernen",
  // attachmentChronology
  email: "E-Mail",
  addedSuffix: " (hinzugefügt)",
  // The stored kind stays German in the Bestand (E-133 point 3); the screen shows this label.
  mailKind: { Antwort: "Antwort", Weiterleitung: "Weiterleitung", "E-Mail": "E-Mail" } satisfies Record<MailEntry["kind"], string>,
  // AttachmentOpenDialog (locked sentences SP-01, SP-02)
  openBlockedTitle: "Diese Datei wird nicht geöffnet",
  openExecutesTitle: "Diese Datei wird ausgeführt",
  openTitle: "Diese Datei wird geöffnet",
  openHandover: "SuperTakt übergibt diese Datei an die Standardanwendung des Systems — dasselbe wie ein Doppelklick im Dateimanager. Was danach geschieht, entscheidet die Anwendung, die Ihr System dafür eingestellt hat.",
  executesStrong: "Diese Datei wird dabei ausgeführt.",
  executesBody: (extension: string) => ` Eine Datei mit der Endung „${extension}" ist ein Programm oder eine Befehlsfolge und läuft mit Ihren Rechten.`,
  fromEmailFile: "Diese Datei stammt aus einer E-Mail.",
  fromEmailFileBy: "Diese Datei stammt aus einer E-Mail von ",
  senderDecided: " Ihren Namen und ihren Inhalt hat der Absender bestimmt, nicht Sie.",
  rebuiltStrong: "Diese Datei ist ein Nachbau:",
  rebuiltBody: " Outlook hat die ursprüngliche Nachricht nicht als Datei hergegeben. Absender, Empfänger, Betreff, Versanddatum und Text stehen in der Datei. Die technischen Kopfzeilen der ursprünglichen Nachricht stehen nicht darin — und mit ihnen nicht der Nachweis, welchen Weg sie genommen hat.",
  fileName: "Dateiname",
  nameWhenOpening: "Name beim Öffnen",
  trailingDotsNote: "Punkte und Leerzeichen am Ende lässt Windows beim Öffnen weg.",
  nameFromEmail: "Name aus der E-Mail",
  nameFromEmailNote: "Diesen Namen hat der Absender gewählt. SuperTakt zeigt ihn, öffnet aber die Datei oben — ein fremder Name bestimmt hier nichts.",
  fullPath: "Vollständiger Pfad",
  extension: "Endung",
  noExtension: "keine — das System entscheidet selbst, womit es die Datei öffnet",
  willExecute: "— wird ausgeführt",
  willOpen: "— wird geöffnet",
  execute: "Ausführen",
  open: "Öffnen",
  // TodoDetailAside (locked sentences SP-05)
  deadline: "Frist",
  deadlineCardLead: "Ein Kalendertag mit optionaler Uhrzeit; sie steht in keinem Export.",
  setDeadline: "Frist setzen",
  changeDeadline: "Frist ändern",
  noDeadline: "Keine Frist gesetzt. Dieses Todo ist deshalb weder überfällig noch heute fällig — es hat schlicht keinen dieser Zustände.",
  deadlineTime: (time: string) => `${time} Uhr · Ortszeit`,
  noExport: "Ohne Abrechnung",
  noExportCard: "Zeit wird erfasst. Dieses Todo ist von Buchungen und Export ausgeschlossen.",
  noEvidence: "Ohne Nachweis",
  noEvidenceCard: "Für dieses Todo wird keine Leistung abgefragt. Zeiten und Notizen bleiben erhalten.",
  estimate: "Zeitschätzung",
  estimateMinutes: (minutes: number) => `${String(minutes)} Minuten`,
  recordedTime: "Erfasste Zeit",
  total: "Gesamt",
  allRecordedUnrounded: "Alle erfassten Zeiten, ungerundet.",
  allBookingsUnrounded: "Alle Buchungen, ungerundet.",
  stillOpen: "Noch offen",
  exportUnavailable: "Was der Export daraus macht, ist gerade nicht abrufbar.",
  notExportedYet: "Noch nicht exportiert.",
  exportYieldsTotal: (quarters: string) => `Beim Export ergibt das ${quarters} — über alle Tagesgruppen zusammen.`,
  // Split around the service message so it can carry `lang="de"` (E-138 point 4).
  previewProblemLead: "Was der Export aus den offenen Buchungen macht, ließ sich nicht abrufen: ",
  previewProblemTail: " Solange fehlt auch die Kennzeichnung der Tagesgruppen, denen die Leistung fehlt.",
  tags: "Tags",
  tagsCardLead: "Tags sind der häufigste Griff, mit dem eine Karte die Spalte wechselt.",
  noTags: "Keine Tags. Regeln, die Tags verlangen, treffen dieses Todo damit nicht — Regeln über Status, „Erledigt“ oder den Exportstatus schon.",
  origin: "Herkunft",
  created: "Angelegt",
  lastChanged: "Zuletzt geändert",
  status: "Status",
  change: "Ändern",
  // TodoDoneSwitch (locked sentence SP-16, second half)
  isDone: (title: string) => `${title} ist erledigt.`,
  statusUnchanged: "Der Status bleibt unverändert — Erledigt und Status sind zwei getrennte Größen.",
  doneFailed: "Das Kennzeichen ließ sich nicht ändern",
  taskDone: "Todo erledigt",
  reopenedByTimer: "Der Timerstart hat das Kennzeichen aufgehoben — SuperTakt hat das getan, nicht Sie.",
  // TodoNoteCard and TodoTagsCell
  internalNote: "Vermerk",
  noteSaved: "Vermerk gespeichert.",
  noteSavedBody: "Er bleibt in SuperTakt.",
  saveNote: "Vermerk speichern",
  unsavedChange: "Nicht gespeicherte Änderung",
  lastChangedOn: (when: string) => `Zuletzt geändert am ${when}`,
  noteNotSaved: "Der Vermerk wurde nicht gespeichert",
  tag: "Tag",
  tagPlural: "Tags",
  // TodoFormDialog
  titleMissing: "Ohne Titel lässt sich ein Todo nicht wiederfinden.",
  todoCreated: "Todo angelegt.",
  isSaved: (title: string) => `${title} ist gespeichert.`,
  tagsCreated: (count: number, names: string) => `Neu angelegt ${count === 1 ? "wurde das Tag" : "wurden die Tags"} ${names}.`,
  defaultTagsAdded: (count: number, names: string) => `Als Standard-Tag ${count === 1 ? "kam" : "kamen"} ${names} hinzu.`,
  todoChanged: "Todo geändert.",
  newTodo: "Neues Todo",
  editTodo: "Todo bearbeiten",
  newTodoLead: "Titel genügt. Alles andere lässt sich später ergänzen.",
  editTodoLead: "Änderungen gelten sofort. Die erfassten Zeiten bleiben unberührt.",
  create: "Anlegen",
  save: "Speichern",
  titlePlaceholder: "Wofür wird Zeit erfasst?",
  callNumber: "Call-Nummer",
  callNumberHint: "Aus dem Ticketsystem. Darf leer bleiben; das Add-in trägt sie beim Buchen aus einer E-Mail ein.",
  // O-GF (T-393): the core is character-identical with `deadlineHintCore` in the
  // task pane bundle; `proof:addin` 19d (GF-03) compares both. The default time is
  // a main-application sentence only (E-122 point 3).
  deadlineHintCore:
    "Ein Kalendertag, die Uhrzeit ist optional. Überfällig ist die Frist erst ab dem Folgetag. Leer lassen heißt: keine Frist. Sie ändert nichts an Pools, Spalten, Buchungen oder Export.",
  deadlineHintDefaultTime: "Ohne eigene Uhrzeit gilt 00:00.",
  // E-121 point 9: the domain returns the code, the UI says the sentence.
  dueDateInvalid: (minYear: number, maxYear: number) =>
    `Eine Frist ist ein Tag der Form JJJJ-MM-TT zwischen ${String(minYear)} und ${String(maxYear)}. Eine Uhrzeit gehört nicht dazu.`,
  callNumberRejection: {
    empty: "Die Call-Nummer ist leer. Sie darf leer bleiben.",
    too_short: (min: number) => `Eine Call-Nummer braucht mindestens ${String(min)} Zeichen.`,
    too_long: (max: number) => `Eine Call-Nummer darf höchstens ${String(max)} Zeichen haben. Länger findet die Duplikatsuche sie nicht wieder.`,
    forbidden_characters: "Erlaubt sind Buchstaben, Ziffern, Punkt, Schrägstrich, Bindestrich und Unterstrich — keine Leerzeichen.",
    formula_start: "Eine Call-Nummer darf nicht mit =, +, - oder @ beginnen.",
  },
  noExportHint: "Zeit erfassen, ohne das Todo in Buchungen oder im Export anzuzeigen.",
  noEvidenceHint: "Beim Stoppen keine Leistung abfragen.",
  priority: "Priorität",
  priorityHint: "Die Werte und ihre Gewichtung stehen in den Einstellungen unter „Prioritäten“.",
  noPriority: "Keine Priorität",
  estimateInMinutes: "Zeitschätzung in Minuten",
  statusHint: "Die Werte stehen in den Einstellungen unter „Status“.",
  tagsHintNew: "Tippen Sie einen Namen: Vorhandene Tags werden vorgeschlagen, ein unbekannter lässt sich als neues Tag anlegen. Die Standard-Tags aus den Einstellungen kommen beim Anlegen von selbst hinzu — sie stehen hier nicht zur Wahl, damit dieselbe Regel nicht zweimal gilt.",
  tagsHintEdit: "Tippen Sie einen Namen: Vorhandene Tags werden vorgeschlagen, ein unbekannter lässt sich als neues Tag anlegen.",
  // TodoListFilters (locked sentence SP-03)
  deadlineFilter: { overdue: "Überfällig", due_today: "Heute fällig", due_later: "Später fällig", no_due_date: "Ohne Frist" },
  sortLabel: { recent: "Zuletzt bearbeitet", asc: "Frist, früheste zuerst", desc: "Frist, späteste zuerst" },
  filterTodos: "Todos filtern",
  searchTodos: "Todos durchsuchen",
  searchPlaceholder: "Titel oder Call-Nummer …",
  anyStatus: "Jeder Status",
  pool: "Pool",
  allPools: "Alle Pools",
  filterByTag: "Nach Tag filtern …",
  anyDeadline: "Jede Frist",
  ordering: "Ordnung",
  showDone: "Erledigte einblenden",
  sortHint: "Ein Todo ohne Frist steht in beiden Richtungen am Ende. Es hat keinen Wert, keinen frühesten und keinen spätesten.",
  // TodoListScreen
  search: "Suche",
  rule: "Regel",
  unknownRule: "unbekannte Regel",
  unknown: "Unbekannt",
  doneFilter: "Erledigte",
  shown: "eingeblendet",
  statusStaysSame: "Der Status bleibt unverändert.",
  hiddenFromList: (unchanged: string) => `Aus dieser Liste ausgeblendet. ${unchanged}`,
  todoDeleted: "Todo gelöscht.",
  isRemoved: (title: string) => `${title} ist entfernt.`,
  todoDeleteFailed: "Das Todo ließ sich nicht löschen.",
  statusChanged: (name: string) => `Status geändert: ${name}.`,
  statusChangedBody: (title: string, status: string) => `${title} steht jetzt auf ${status}. Tags und Kanban-Spalten bleiben unberührt.`,
  statusChangeFailed: "Der Status ließ sich nicht ändern",
  openAction: "Öffnen",
  edit: "Bearbeiten",
  statusEntry: (name: string) => `Status: ${name}`,
  currentStatus: "Aktueller Status",
  markDone: "Als erledigt markieren",
  undoDone: "Erledigt zurücknehmen",
  delete: "Löschen",
  todosTitle: "Todos",
  todosLead: "Alles, wofür Zeit erfasst wird. Erledigte sind ausgeblendet, bis Sie sie einblenden.",
  todoSingular: "Todo",
  todoPlural: "Todos",
  loadingShort: "wird geladen …",
  todosLoading: "Todos werden geladen",
  noTodoTitle: "Noch kein Todo",
  noTodoBody: "SuperTakt erfasst Zeit auf Todos. Legen Sie das erste an — Titel genügt.",
  noMatchTitle: "Kein Todo passt zu diesen Filtern",
  noMatchBody: "Setzen Sie einen Filter zurück oder blenden Sie erledigte Todos ein.",
  resetFilters: "Filter zurücksetzen",
  loadMoreLeft: (left: string) => `Weitere laden (${left} übrig)`,
  deleteTodoTitle: "Todo löschen?",
  deleteTodoLead: (title: string) => `${title} wird mit allen noch nicht exportierten Zeitbuchungen entfernt.`,
  deleteTodoConsequence: "Hängt an dem Todo eine bereits exportierte Buchung, lehnt SuperTakt das Löschen ab: Abgerechnete Zeit wird nicht durch das Löschen eines Todos entfernt.",
  deleteForGood: "Endgültig löschen",
  hiddenDoneOne: "erledigtes Todo ist",
  hiddenDoneMany: "erledigte Todos sind",
  hiddenDone: (count: string) => `${count} ausgeblendet.`,
  show: "Einblenden",
  // TodoTable
  tableCaption: "Alle Todos mit Erledigt-Kennzeichen, Call-Nummer, Status, Frist, Tags und Exportstand ihrer Buchungen",
  columnDone: "Erledigt",
  columnCall: "Call",
  columnTitle: "Titel",
  columnBookings: "Buchungen",
  columnActions: "Aktionen",
  markOpen: (title: string) => `${title} als offen markieren`,
  markDoneFor: (title: string) => `${title} als erledigt markieren`,
  stopTimerFor: (title: string) => `Timer für ${title} stoppen`,
  startTimerFor: (title: string) => `Timer für ${title} starten`,
  menuFor: (title: string) => `Menü für ${title}`,
  // TodoDetailScreen
  bookingDeleted: "Buchung gelöscht.",
  groupChangesToo: "Die Tagesgruppe dieses Todos ändert sich mit.",
  bookingDeleteFailed: "Die Buchung ließ sich nicht löschen",
  writtenOffNotDeleted: "Ausgebuchte Zeit wird nicht gelöscht. Sie bleibt als Beleg stehen.",
  billedNotDeleted: "Abgerechnete Zeit wird nicht gelöscht.",
  todoLoading: "Todo wird geladen",
  callAndStatus: (call: string, status: string) => `Call ${call} · Status: ${status}`,
  stopTimer: "Timer stoppen",
  startTimer: "Timer starten",
  emailHistory: "E-Mail-Verlauf",
  timeUnavailable: "Zeitpunkt nicht verfügbar",
  outlookFailed: "Outlook ließ sich nicht öffnen",
  outlookFailedBody: "Der Rückverweis konnte auf diesem Rechner nicht geöffnet werden.",
  openInOutlook: "In Outlook öffnen",
  ownNote: "Eigene Notiz: ",
  attachmentsLead: "Ein Verweis öffnet den Browser, eine Datei die Standardanwendung des Systems, ein Bild wird hier gezeigt. Geöffnet wird nur auf Ihren Klick.",
  bookingsCard: "Buchungen",
  manualTime: "Zeit von Hand",
  groupedNoExport: "Nach Kalendertag gruppiert. Von der Abrechnung ausgeschlossen.",
  groupedByDay: "Nach Kalendertag gruppiert — so entsteht auch die Exportzeile.",
  noTimeYet: "Noch keine Zeit erfasst",
  noTimeYetBody: "Starten Sie den Timer oder tragen Sie eine Zeit von Hand ein.",
  booking: "Buchung",
  bookings: "Buchungen",
  groupNoExport: " · ohne Abrechnung",
  groupOpen: (open: string) => ` · ${open} offen`,
  groupFullyExported: " · vollständig exportiert",
  groupBlocked: "Diese Tagesgruppe hat keinen Leistungstext und geht so nicht in den Export. Der übrige Export läuft trotzdem — sie bleibt offen und erscheint beim nächsten Mal wieder.",
  exportedTimes: (count: number) => `${String(count)}× exportiert`,
  withoutNote: "Ohne Leistung",
  bookingMenu: "Menü für diese Buchung",
  deleteBookingTitle: "Buchung löschen?",
  deleteBookingLead: (duration: string, day: string) => `${duration} vom ${day} werden entfernt.`,
  deleteBookingConsequence: "Die Tagesgruppe dieses Todos wird dadurch kleiner, und der gerundete Exportwert ändert sich mit.",
};

const en: typeof de = {
  undoneBody: "Tags and status do not change.",
  undoFailed: "Undoing did not work",
  undo: "Undo",
  openAgain: (title: string) => `${title} is open again.`,

  attachmentKind: { link: "Link", image: "Image", file: "File" },
  attachmentValue: { link: "Address", image: "Image", file: "File path" },
  valueMissing: {
    link: "Without an address the attachment cannot be opened.",
    image: "Without an image the attachment cannot be opened.",
    file: "Without a file path the attachment cannot be opened.",
  },
  pickCancelled: "Selection cancelled.",
  typePathByHand: (reason: string) => `${reason} Enter the full path by hand — SuperTakt checks it the same way.`,
  attachmentAdded: "Attachment added.",
  attachmentAddedBody: "Remove it with the bin icon in the row.",
  addAttachment: "Add attachment",
  addAttachmentLead: "A link, an image or a file that belongs to this todo.",
  add: "Add",
  kind: "Kind",
  linkPlaceholder: "https://…",
  linkHint: "Only “http” and “https”. SuperTakt stores the address, not the page.",
  imagePathPlaceholder: "Path of the image file",
  filePathPlaceholder: "Full path to the file",
  imageHint: "SuperTakt keeps a copy next to its data. If you move the source later, the preview stays.",
  fileHint: "SuperTakt remembers the path and copies nothing. If the file disappears, the attachment says so.",
  choose: "Choose …",
  title: "Title",
  titleHint: "Optional. Without a title the list shows a readable part of the address or path.",
  previewUnreadable: (label: string) => `Preview not readable: ${label}`,
  noLongerReadable: "No longer readable",
  preview: (label: string) => `Preview: ${label}`,
  fromEmail: "From an email",
  fromEmailBy: "From an email by ",
  rebuilt: "(rebuilt)",
  openAttachment: (kind: string, label: string, rebuilt: boolean) => `Open ${kind.toLowerCase()}: ${label}${rebuilt ? " (rebuilt)" : ""}`,
  removeAttachment: (kind: string, label: string) => `Remove ${kind.toLowerCase()}: ${label}`,
  refusal: {
    link_empty: "This link has no address.",
    link_too_long: "This address is too long to open.",
    link_control_character: "This address contains invisible control characters. SuperTakt does not open it.",
    link_unparsable: "This address cannot be read.",
    link_scheme_rejected:
      "This address cannot be opened: SuperTakt only opens “http” and “https”. A network path is not an address but a sign-in to another computer.",
    link_not_normalized:
      "This address is not in the form SuperTakt creates when adding it. It is not opened — otherwise the address shown here would differ from the one opened.",
    link_no_host: "This address lacks the host name.",
    link_userinfo:
      "This address carries credentials before the host name. It then looks like a different target than it goes to, and is not opened.",
    path_empty: "This attachment has no path.",
    path_too_long: "This path is too long to open.",
    path_control_character: "This path contains invisible control characters. SuperTakt does not open it.",
    path_unc:
      "This path points to a network share. SuperTakt opens none, because such an access is also a sign-in to another computer.",
    path_not_absolute: "This path is not complete. SuperTakt only opens complete paths.",
    path_stream_separator:
      "The file name contains a colon. On Windows it names a second data stream of the same file — what would open is not what is shown here. So SuperTakt does not open it.",
    path_indirect_extension:
      "This file is a shortcut. Its target is elsewhere — the confirmation could not tell the truth about it, so SuperTakt does not open it.",
    path_missing: "This file no longer exists at this path.",
  } as Readonly<Record<string, string>>,
  refusedUnknown: "SuperTakt refused to open it. The attachment stays; the reason cannot be named more precisely here.",
  openFailed: "Opening failed. Possibly no application for it is set up on this computer.",
  attachmentRemoved: "Attachment removed.",
  attachmentRemovedBody: (label: string) => `${label} no longer belongs to this todo.`,
  attachmentsLoading: "Loading attachments",
  attachmentsFailed: "The attachments could not be loaded",
  noAttachments: "No attachments",
  noAttachmentsBody: "A link, an image or a file that belongs to this todo. SuperTakt copies only images; links and files are remembered as address or path.",
  attachments: "Attachments",
  removeTitle: "Remove attachment",
  removeLead: (label: string, todo: string) => `${label} then no longer belongs to ${todo}.`,
  removeImage: "The copy of the image in SuperTakt's data folder is deleted as well. The file it came from stays untouched.",
  removeOther: "SuperTakt forgets the address or path. The file or page behind it stays untouched.",
  remove: "Remove",
  email: "Email",
  addedSuffix: " (added)",
  mailKind: { Antwort: "Reply", Weiterleitung: "Forward", "E-Mail": "Email" } satisfies Record<MailEntry["kind"], string>,
  openBlockedTitle: "This file is not opened",
  openExecutesTitle: "This file is executed",
  openTitle: "This file is opened",
  openHandover: "SuperTakt hands this file to the system's default application — the same as a double click in the file manager. What happens then is decided by the application your system has set for it.",
  executesStrong: "This file is executed.",
  executesBody: (extension: string) => ` A file with the extension “${extension}” is a program or a command sequence and runs with your permissions.`,
  fromEmailFile: "This file comes from an email.",
  fromEmailFileBy: "This file comes from an email by ",
  senderDecided: " Its name and content were decided by the sender, not by you.",
  rebuiltStrong: "This file is a rebuild:",
  rebuiltBody: " Outlook did not hand over the original message as a file. Sender, recipients, subject, send date and text are in the file. The technical headers of the original message are not — and with them not the proof of which route it took.",
  fileName: "File name",
  nameWhenOpening: "Name when opening",
  trailingDotsNote: "Windows drops trailing dots and spaces when opening.",
  nameFromEmail: "Name from the email",
  nameFromEmailNote: "The sender chose this name. SuperTakt shows it but opens the file above — a foreign name decides nothing here.",
  fullPath: "Full path",
  extension: "Extension",
  noExtension: "none — the system itself decides what opens the file",
  willExecute: "— is executed",
  willOpen: "— is opened",
  execute: "Execute",
  open: "Open",
  deadline: "Due date",
  deadlineCardLead: "A calendar day with optional time; it is in no export.",
  setDeadline: "Set due date",
  changeDeadline: "Change due date",
  noDeadline: "No due date set. So this todo is neither overdue nor due today — it simply has none of these states.",
  deadlineTime: (time: string) => `${time} · local time`,
  noExport: "No billing",
  noExportCard: "Time is recorded. This todo is excluded from bookings and export.",
  noEvidence: "No evidence",
  noEvidenceCard: "This todo does not ask for work done. Times and notes are kept.",
  estimate: "Estimate",
  estimateMinutes: (minutes: number) => `${String(minutes)} minutes`,
  recordedTime: "Recorded time",
  total: "Total",
  allRecordedUnrounded: "All recorded times, unrounded.",
  allBookingsUnrounded: "All bookings, unrounded.",
  stillOpen: "Still open",
  exportUnavailable: "What the export makes of it cannot be retrieved right now.",
  notExportedYet: "Not exported yet.",
  exportYieldsTotal: (quarters: string) => `At export this yields ${quarters} — over all day groups together.`,
  previewProblemLead: "What the export makes of the open bookings could not be retrieved: ",
  previewProblemTail: " Until then the marking of day groups missing work done is missing too.",
  tags: "Tags",
  tagsCardLead: "Tags are the most common handle that moves a card to another column.",
  noTags: "No tags. Rules that require tags do not match this todo — rules about status, “Done” or the export status do.",
  origin: "Origin",
  created: "Created",
  lastChanged: "Last changed",
  status: "Status",
  change: "Change",
  isDone: (title: string) => `${title} is done.`,
  statusUnchanged: "The status stays unchanged — done and status are two separate things.",
  doneFailed: "The done flag could not be changed",
  taskDone: "Todo done",
  reopenedByTimer: "The timer start lifted the flag — SuperTakt did that, not you.",
  internalNote: "Internal note",
  noteSaved: "Internal note saved.",
  noteSavedBody: "It stays in SuperTakt.",
  saveNote: "Save internal note",
  unsavedChange: "Unsaved change",
  lastChangedOn: (when: string) => `Last changed ${when}`,
  noteNotSaved: "The internal note was not saved",
  tag: "tag",
  tagPlural: "tags",
  titleMissing: "Without a title a todo cannot be found again.",
  todoCreated: "Todo created.",
  isSaved: (title: string) => `${title} is saved.`,
  tagsCreated: (count: number, names: string) => `Newly created ${count === 1 ? "tag" : "tags"}: ${names}.`,
  defaultTagsAdded: (count: number, names: string) => `Added as default ${count === 1 ? "tag" : "tags"}: ${names}.`,
  todoChanged: "Todo changed.",
  newTodo: "New todo",
  editTodo: "Edit todo",
  newTodoLead: "A title is enough. Everything else can be added later.",
  editTodoLead: "Changes apply at once. The recorded times stay untouched.",
  create: "Create",
  save: "Save",
  titlePlaceholder: "What is time recorded for?",
  callNumber: "Call number",
  callNumberHint: "From the ticket system. May stay empty; the add-in fills it in when booking from an email.",
  deadlineHintCore:
    "A calendar day, the time is optional. The due date is only overdue from the following day. Leave empty for no due date. It changes nothing about pools, columns, bookings or export.",
  deadlineHintDefaultTime: "Without a time of your own, 00:00 applies.",
  dueDateInvalid: (minYear: number, maxYear: number) =>
    `A due date is a day of the form YYYY-MM-DD between ${String(minYear)} and ${String(maxYear)}. A time is not part of it.`,
  callNumberRejection: {
    empty: "The call number is empty. It may stay empty.",
    too_short: (min: number) => `A call number needs at least ${String(min)} characters.`,
    too_long: (max: number) => `A call number may have at most ${String(max)} characters. Longer ones are not found again by the duplicate search.`,
    forbidden_characters: "Allowed are letters, digits, dot, slash, hyphen and underscore — no spaces.",
    formula_start: "A call number must not start with =, +, - or @.",
  },
  noExportHint: "Record time without showing the todo in bookings or in the export.",
  noEvidenceHint: "Skip the note prompt when stopping.",
  priority: "Priority",
  priorityHint: "The values and their weighting are in the settings under “Priorities”.",
  noPriority: "No priority",
  estimateInMinutes: "Estimate in minutes",
  statusHint: "The values are in the settings under “Status”.",
  tagsHintNew: "Type a name: existing tags are suggested, an unknown one can be created as a new tag. The default tags from the settings are added by themselves when creating — they are not offered here, so the same rule does not apply twice.",
  tagsHintEdit: "Type a name: existing tags are suggested, an unknown one can be created as a new tag.",
  deadlineFilter: { overdue: "Overdue", due_today: "Due today", due_later: "Due later", no_due_date: "No due date" },
  sortLabel: { recent: "Last edited", asc: "Due date, earliest first", desc: "Due date, latest first" },
  filterTodos: "Filter todos",
  searchTodos: "Search todos",
  searchPlaceholder: "Title or call number …",
  anyStatus: "Any status",
  pool: "Pool",
  allPools: "All pools",
  filterByTag: "Filter by tag …",
  anyDeadline: "Any due date",
  ordering: "Order",
  showDone: "Show done",
  sortHint: "A todo without a due date is at the end in both directions. It has no value, neither earliest nor latest.",
  search: "Search",
  rule: "Rule",
  unknownRule: "unknown rule",
  unknown: "Unknown",
  doneFilter: "Done",
  shown: "shown",
  statusStaysSame: "The status stays unchanged.",
  hiddenFromList: (unchanged: string) => `Hidden from this list. ${unchanged}`,
  todoDeleted: "Todo deleted.",
  isRemoved: (title: string) => `${title} is removed.`,
  todoDeleteFailed: "The todo could not be deleted.",
  statusChanged: (name: string) => `Status changed: ${name}.`,
  statusChangedBody: (title: string, status: string) => `${title} is now on ${status}. Tags and Kanban columns stay untouched.`,
  statusChangeFailed: "The status could not be changed",
  openAction: "Open",
  edit: "Edit",
  statusEntry: (name: string) => `Status: ${name}`,
  currentStatus: "Current status",
  markDone: "Mark as done",
  undoDone: "Undo done",
  delete: "Delete",
  todosTitle: "Todos",
  todosLead: "Everything time is recorded for. Done ones are hidden until you show them.",
  todoSingular: "todo",
  todoPlural: "todos",
  loadingShort: "loading …",
  todosLoading: "Loading todos",
  noTodoTitle: "No todo yet",
  noTodoBody: "SuperTakt records time on todos. Create the first one — a title is enough.",
  noMatchTitle: "No todo matches these filters",
  noMatchBody: "Reset a filter or show done todos.",
  resetFilters: "Reset filters",
  loadMoreLeft: (left: string) => `Load more (${left} left)`,
  deleteTodoTitle: "Delete todo?",
  deleteTodoLead: (title: string) => `${title} is removed together with all time bookings not yet exported.`,
  deleteTodoConsequence: "If an already exported booking is attached to the todo, SuperTakt refuses to delete it: billed time is not removed by deleting a todo.",
  deleteForGood: "Delete for good",
  hiddenDoneOne: "done todo is",
  hiddenDoneMany: "done todos are",
  hiddenDone: (count: string) => `${count} hidden.`,
  show: "Show",
  tableCaption: "All todos with done flag, call number, status, due date, tags and export state of their bookings",
  columnDone: "Done",
  columnCall: "Call",
  columnTitle: "Title",
  columnBookings: "Bookings",
  columnActions: "Actions",
  markOpen: (title: string) => `Mark ${title} as open`,
  markDoneFor: (title: string) => `Mark ${title} as done`,
  stopTimerFor: (title: string) => `Stop timer for ${title}`,
  startTimerFor: (title: string) => `Start timer for ${title}`,
  menuFor: (title: string) => `Menu for ${title}`,
  bookingDeleted: "Booking deleted.",
  groupChangesToo: "This todo's day group changes with it.",
  bookingDeleteFailed: "The booking could not be deleted",
  writtenOffNotDeleted: "Written-off time is not deleted. It stays as evidence.",
  billedNotDeleted: "Billed time is not deleted.",
  todoLoading: "Loading todo",
  callAndStatus: (call: string, status: string) => `Call ${call} · Status: ${status}`,
  stopTimer: "Stop timer",
  startTimer: "Start timer",
  emailHistory: "Email history",
  timeUnavailable: "Time not available",
  outlookFailed: "Outlook could not be opened",
  outlookFailedBody: "The link back could not be opened on this computer.",
  openInOutlook: "Open in Outlook",
  ownNote: "Own note: ",
  attachmentsLead: "A link opens the browser, a file the system's default application, an image is shown here. Nothing opens except on your click.",
  bookingsCard: "Bookings",
  manualTime: "Time by hand",
  groupedNoExport: "Grouped by calendar day. Excluded from billing.",
  groupedByDay: "Grouped by calendar day — this is also how the export row comes about.",
  noTimeYet: "No time recorded yet",
  noTimeYetBody: "Start the timer or enter a time by hand.",
  booking: "booking",
  bookings: "bookings",
  groupNoExport: " · no billing",
  groupOpen: (open: string) => ` · ${open} open`,
  groupFullyExported: " · fully exported",
  groupBlocked: "This day group has no work text and so does not go into the export. The rest of the export still runs — it stays open and appears again next time.",
  exportedTimes: (count: number) => `exported ${String(count)}×`,
  withoutNote: "No work done",
  bookingMenu: "Menu for this booking",
  deleteBookingTitle: "Delete booking?",
  deleteBookingLead: (duration: string, day: string) => `${duration} of ${day} are removed.`,
  deleteBookingConsequence: "This todo's day group becomes smaller, and the rounded export value changes with it.",
};

export function todoTexts(): typeof de {
  return pickTexts({ de, en });
}
