import { expect, test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const entry = '/@fs/' + fileURLToPath(new URL('./support/kanban-layout.html', import.meta.url)).replace(/^\//, '');
test('Kanban keeps filters together and gives a single column readable space; manual booking belongs to bookings', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => { errors.push(error.message); console.log(error.stack); });
  const todo = { id: 'task', title: 'Call 31825 – Datenübertragung und Rechnungsprüfung', callNumber: '31825', statusId: 'status', tagIds: [], priorityId: 'high', dueDate: '2026-09-03', dueTime: '12:30', completedAt: null, createdAt: '2026-09-01T08:00:00Z', updatedAt: '2026-09-16T08:00:00Z' };
  const column = { id: 'pool', name: 'Offen (extern)', rule: [], matchMode: 'all', excludedTags: [], statusIds: ['status'], completion: 'open', exportState: 'any', placement: 'board', position: 0, resolved: { tagCount: 0, excludedTagCount: 0, isEmpty: false, unresolvedRequired: false, unresolvedExcluded: false, matchesNothing: false, emptyRuleFolderIds: [], emptyExcludedFolderIds: [] } };
  await page.route('**/priority-fixture/**', async route => {
    const url = new URL(route.request().url());
    const path = url.pathname.replace('/priority-fixture', '');
    let data: unknown = [];
    if (path === '/settings') data = { settings: { idleDetectionEnabled: false }, defaultTags: [], windowsUser: 'Test', exportDirectoryState: 'ok' };
    else if (path === '/tag-tree') data = { rootFolders: [], rootTags: [] };
    else if (path === '/todo-statuses') data = [{ id: 'status', name: 'Backlog', position: 0 }];
    else if (path === '/priorities') data = [{ id: 'high', name: 'Hohe Priorität', weight: 100 }];
    else if (path.startsWith('/timer')) data = null;
    else if (path === '/pools') data = [column];
    else if (path === '/board') data = { generatedAt: '2026-09-16T08:00:00Z', appearances: [], columns: [{ column, todos: [todo], total: 30, nextCursor: 'more' }] };
    else if (path === '/todos/task/attachments') data = { items: [] };
    else if (path === '/time-entries') data = { items: [], total: 0, nextCursor: null };
    else if (path === '/todos/task') data = { todo, totalSeconds: 0, openSeconds: 0 };
    else if (path === '/todos/task/note') data = { todoId: 'task', text: '', updatedAt: todo.updatedAt };
    await route.fulfill({ json: { data } });
  });
  await page.goto(entry);
  await expect(page.getByRole('button', { name: todo.title, exact: true })).toBeVisible();
  const filters = page.getByRole('region', { name: 'Kanban filtern und sortieren' });
  await expect(filters.getByRole('combobox', { name: 'Priorität', exact: true })).toBeVisible();
  expect((await page.locator('.kcolumn').boundingBox())!.width).toBeGreaterThan(450);
  await expect(page.getByRole('button', { name: 'Mehr Karten laden' })).toBeVisible();
  await page.screenshot({ path: '/tmp/kanban-layout.png' });
  await page.setViewportSize({ width: 600, height: 820 });
  await expect(filters).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto(entry + '?detail');
  const bookings = page.locator('.card').filter({ has: page.getByRole('heading', { name: 'Buchungen', exact: true }) });
  await expect(bookings.getByRole('button', { name: 'Zeit von Hand', exact: true })).toBeVisible();
  const deadline = page.locator('.detail__deadline-card');
  await expect(deadline).toContainText('12:30 Uhr');
  await bookings.getByRole('button', { name: 'Zeit von Hand', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  expect(errors).toEqual([]);
});
