import { expect, test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const entry = '/@fs/' + fileURLToPath(new URL('./support/priorities.html', import.meta.url)).replace(/^\//, '');

test('configure a weighted priority, assign it to a todo, use the calendar and inspect collapsed Kanban tags', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const priorities: { id: string; name: string; weight: number }[] = [];
  let saved: Record<string, unknown> | undefined;
  await page.route('**/priority-fixture/**', async route => {
    const path = new URL(route.request().url()).pathname.replace('/priority-fixture', '');
    let data: unknown = [];
    if (path === '/priorities') {
      if (route.request().method() === 'POST') {
        const input = route.request().postDataJSON();
        priorities.push({ id: 'priority', ...input }); data = priorities[0];
      } else data = priorities;
    } else if (path === '/settings') data = { settings: {}, defaultTags: [], windowsUser: 'Test', exportDirectoryState: 'ok' };
    else if (path === '/tag-tree') data = { rootFolders: [], rootTags: [] };
    else if (path === '/todo-statuses') data = [{ id: 'status', name: 'Backlog', position: 0, color: null }];
    else if (path === '/todos' && route.request().method() === 'POST') { saved = route.request().postDataJSON(); data = { todo: { id: 'todo', ...saved }, poolMovement: null, addedDefaultTagIds: [], createdTags: [] }; }
    await route.fulfill({ json: { data } });
  });
  await page.goto(entry);
  await page.getByRole('button', { name: 'Priorität hinzufügen' }).click();
  const priorityDialog = page.getByRole('dialog');
  await priorityDialog.getByLabel(/^Name/).fill('Dringend');
  await priorityDialog.getByLabel(/^Gewichtung/).fill('100');
  await priorityDialog.getByRole('button', { name: 'Speichern', exact: true }).click();
  await expect(priorityDialog).toBeHidden();
  expect(priorities[0]).toMatchObject({ name: 'Dringend', weight: 100 });
  await expect(page.getByText('Gewichtung 100', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Todo erstellen' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel(/^Titel/).fill('Wichtige Aufgabe');
  await dialog.getByRole('combobox', { name: 'Priorität', exact: true }).click();
  await page.getByRole('option', { name: 'Dringend · 100', exact: true }).click();
  await dialog.getByRole('textbox', { name: 'Frist', exact: true }).click();
  const calendar = page.getByRole('application', { name: 'Frist: Datum wählen', exact: true });
  await expect(calendar).toBeVisible();
  const day = calendar.locator('[data-part="table-cell-trigger"]:not([data-outside-range]):not([data-disabled])').nth(12);
  expect(await day.evaluate(element => { const box = element.getBoundingClientRect(); return element.contains(document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2)); })).toBe(true);
  await page.screenshot({ path: '/tmp/priorities-todo-calendar.png' });
  await day.click();
  await expect(calendar).toBeHidden();
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Anlegen', exact: true }).click();
  await expect(dialog).toBeHidden();
  expect(saved?.priorityId).toBe('priority');
  expect(saved?.dueTime).toBe('00:00');
  expect(saved?.dueDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  const tags = page.getByRole('button', { name: '2 Tags', exact: true });
  await expect(page.locator('.tagsurface')).toBeHidden();
  await tags.hover();
  await expect(page.locator('.tagsurface')).toBeVisible();
  await expect(page.locator('.tagsurface')).toContainText('Projekte');
  await expect(page.locator('.tagsurface')).toContainText('Arbeit');
  await expect(page.locator('.tagsurface')).toContainText('Extern oder Intern');
  await page.screenshot({ path: '/tmp/priorities-kanban-tags.png' });
  await page.mouse.move(1000, 500);
  await expect(page.locator('.tagsurface')).toBeHidden();
  await page.getByRole('button', { name: 'Todo erstellen' }).click();
  await dialog.getByLabel(/^Titel/).fill('Termin mit Uhrzeit');
  await dialog.getByRole('textbox', { name: 'Frist', exact: true }).click();
  await calendar.locator('[data-part="table-cell-trigger"]:not([data-outside-range]):not([data-disabled])').nth(12).click();
  await dialog.getByRole('button', { name: 'Frist: Uhrzeit', exact: true }).click();
  const timePicker = page.getByRole('dialog', { name: 'Frist: Uhrzeit wählen', exact: true });
  await expect(timePicker).toBeVisible();
  await timePicker.getByRole('listbox', { name: 'Stunde', exact: true }).getByRole('option', { name: '12', exact: true }).click();
  const minutes = timePicker.getByRole('listbox', { name: 'Minute', exact: true });
  await minutes.getByRole('option', { name: '30', exact: true }).click();
  await page.keyboard.press('ArrowDown');
  await expect(minutes.getByRole('option', { name: '31', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('ArrowUp');
  await page.screenshot({ path: '/tmp/deadline-time-picker.png' });
  await timePicker.getByRole('button', { name: 'Übernehmen', exact: true }).click();
  await expect(timePicker).toBeHidden();
  await page.screenshot({ path: '/tmp/combined-deadline.png' });
  await dialog.getByRole('button', { name: 'Anlegen', exact: true }).click();
  await expect(dialog).toBeHidden();
  expect(saved?.dueTime).toBe('12:30');
  expect(errors).toEqual([]);
});
