import { expect, test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
const entry = '/@fs/' + fileURLToPath(new URL('./support/settings-structure.html', import.meta.url)).replace(/^\//, '');
test('Tags and rules live in separate settings areas; legacy links still work', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => { errors.push(error.message); console.log(error.stack); });
  const todo = { id: 'task', title: 'Call 31825 – Datenübertragung und Rechnungsprüfung', callNumber: '31825', statusId: 'status', tagIds: [], priorityId: 'high', dueDate: '2026-09-03', dueTime: '12:30', completedAt: null, createdAt: '2026-09-01T08:00:00Z', updatedAt: '2026-09-16T08:00:00Z' };
  const column = { id: 'pool', name: 'Offen (extern)', rule: [], matchMode: 'all', excludedTags: [], statusIds: ['status'], completion: 'open', exportState: 'any', placement: 'board', position: 0, resolved: { tagCount: 0, excludedTagCount: 0, isEmpty: false, unresolvedRequired: false, unresolvedExcluded: false, matchesNothing: false, emptyRuleFolderIds: [], emptyExcludedFolderIds: [] } };
  await page.route('**/priority-fixture/**', async route => {
    const url = new URL(route.request().url());
    const path = url.pathname.replace('/priority-fixture', '');
    let data: unknown = [];
    if (path === '/settings') data = { settings: { idleDetectionEnabled: false }, defaultTags: [], windowsUser: 'Test', exportDirectoryState: 'ok' };
    else if (path === '/tag-tree') data = { rootFolders: [], rootTags: [] };
    else if (path === '/todo-statuses') data = [{ id: 'status', name: 'Backlog', position: 0 }];
    else if (path === '/priorities') data = [{ id: 'high', name: 'Hohe Priorität', weight: 100 }];
    else if (path.startsWith('/timer')) data = null;
    else if (path === '/pools') data = [column];
    else if (path === '/board') data = { generatedAt: '2026-09-16T08:00:00Z', appearances: [], columns: [{ column, todos: [todo], total: 30, nextCursor: 'more' }] };
    else if (path === '/todos/task/attachments') data = { items: [] };
    else if (path === '/time-entries') data = { items: [], total: 0, nextCursor: null };
    else if (path === '/todos/task') data = { todo, totalSeconds: 0, openSeconds: 0 };
    else if (path === '/todos/task/note') data = { todoId: 'task', text: '', updatedAt: todo.updatedAt };
    await route.fulfill({ json: { data } });
  });
  await page.goto(entry + '#/tags');
  await expect(page.getByRole('navigation', { name: 'Hauptnavigation' }).getByRole('link', { name: 'Tags', exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Standard-Tags', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tags und Ordner', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Regeln', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: /Regeln Pools und Kanban-Spalten/ }).click();
  await expect(page.getByRole('heading', { name: 'Regeln', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tags und Ordner', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Neue Regel', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.goto(entry + '#/einstellungen?bereich=standardtags');
  await expect(page.getByRole('heading', { name: 'Tags und Ordner', exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/settings-tags.png' });
  expect(errors).toEqual([]);
});
