import { getLanguage, pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // SettingsScreen
  noticeLabel: {
    auth_failure_burst: "Gehäufte Anmeldeversuche ohne gültigen Nachweis",
    token_in_url: "Ein Nachweis stand in einer Adresszeile und wurde abgewiesen",
    origin_rejected: "Eine Anfrage kam von einer fremden Herkunft",
    host_rejected: "Eine Anfrage nannte einen fremden Hostnamen",
    file_permissions_wide: "Eine Datei im Datenordner hat zu weite Rechte",
  },
  // Rail hints stay at most 36 characters in both languages (welle-18.md R-L5).
  areas: {
    darstellung: { label: "Darstellung", hint: "Themes, Farbmodus und Zeilendichte" },
    timer: { label: "Timer", hint: "Leistung beim Stoppen" },
    export: { label: "Export", hint: "Zielordner, Vorlage, Rundung" },
    daten: { label: "Daten", hint: "Sichern, wiederherstellen, umziehen" },
    tags: { label: "Tags", hint: "Tags, Ordner und Standard-Tags" },
    regeln: { label: "Regeln", hint: "Pools und Kanban-Spalten" },
    prioritaeten: { label: "Prioritäten", hint: "Prioritäten und ihre Gewichtung" },
    status: { label: "Status", hint: "Statuswerte eines Todos" },
    addin: { label: "Outlook-Add-in", hint: "Zugang des Add-ins" },
    arbeitsplatz: { label: "Arbeitsplatz", hint: "Abrechnungsname, Ablageort, Meldungen" },
  },
  settingsTitle: "Einstellungen",
  areasNav: "Bereiche der Einstellungen",
  settingsLoading: "Einstellungen werden geladen",
  density: {
    comfortable: "Normal — mehr Luft zwischen den Zeilen",
    compact: "Kompakt — mehr Zeilen auf dem Bildschirm",
  },
  timerTitle: "Timer",
  timerLead: "Bestimmen Sie, wann Sie Ihre Leistung eintragen möchten.",
  promptOnStop: "Leistung beim Stoppen abfragen",
  promptOnStopHint: "Ausgeschaltet wird die Zeit sofort gebucht, auch beim Wechsel zu einem anderen Timer. Vorhandene Leistung bleibt erhalten; fehlenden Text können Sie später in der Buchungsübersicht ergänzen.",
  detectIdle: "Inaktive Zeit erkennen",
  detectIdleHint: "Bei Ihrer Rückkehr pausiert der Timer, bis Sie die inaktive Zeit als Pause auslassen, einem Todo zuordnen oder aufteilen. Offene Zuordnungen bleiben beim Ausschalten dieser Einstellung erhalten.",
  timerWhenIdle: "Timer bei Inaktivität",
  keepRunning: "Weiterlaufen lassen",
  pauseUntilAssigned: "Bis zur Zuordnung pausieren",
  detectIdleAfter: "Inaktivität erkennen nach",
  minutes: (count: number) => `${String(count)} ${count === 1 ? "Minute" : "Minuten"}`,
  idleChecking: "Inaktivitätserkennung wird geprüft …",
  idleSupported: "Systemweite Erkennung verfügbar — auch Eingaben in anderen Programmen zählen als Aktivität.",
  idleUnsupported: "Systemweite Erkennung ist hier nicht verfügbar. Sie benötigt die Desktop-App und eine unterstützte Systemschnittstelle.",
  idlePrivacy: "Es werden nur Zeitpunkte gelesen, keine Tasten, Texte oder Programminhalte aufgezeichnet.",
  displayTitle: "Darstellung",
  displayLead: "Alles hier wirkt sofort und bleibt beim nächsten Start erhalten.",
  language: "Sprache",
  languageHint: "Das Outlook-Add-in und die Meldungen des lokalen Dienstes bleiben vorerst deutsch.",
  // Version check (A-28.1, welle-18-fluss.md 1.2)
  versionCheckTitle: "Versionsprüfung",
  versionCheckLabel: "Nach neuen Versionen suchen",
  versionCheckHint: "Fragt die Veröffentlichungen von SuperTakt auf GitHub ab. Ausgeschaltet stellt SuperTakt keine Verbindung nach außen her.",
  // File permissions of the Bestand (A-28.8, welle-18-fluss.md 6.2)
  permissionsTitle: "Die Dateien des Bestands sind für andere Benutzer lesbar",
  permissionsBody: "SuperTakt konnte die Rechte beim Start nicht enger setzen. Der Bestand enthält Kundendaten und interne Vermerke.",
  permissionsRemedy: "Rechte der Dateien im Ordner oben auf den eigenen Benutzer beschränken, dann SuperTakt neu starten. Die Warnung verschwindet nach dem Neustart.",
  colorMode: "Farbmodus",
  modeSystem: "System",
  modeSystemHint: "Folgt dem Farbmodus des Betriebssystems.",
  modeDark: "Dunkel",
  modeLight: "Hell",
  fixedColors: (dark: boolean) => `Dieses Theme verwendet feste ${dark ? "dunkle" : "helle"} Farben. Die freie Farbwahl steht bei Klassisch und den anpassbaren Themes zur Verfügung.`,
  chooseTheme: "Theme auswählen",
  themeMode: { dark: "Dunkel · ", light: "Hell · ", auto: "Hell & Dunkel · " },
  themeHint: "Alle Themes verwenden das klassische Layout. Klassisch ist der Standard.",
  rowDensity: "Zeilendichte",
  rowDensityHint: "Bestimmt die Abstände in Tabellen und Listen, unabhängig vom gewählten Theme.",
  motionIntensity: "Bewegung in der Oberfläche",
  motionIntensityHint: "Steuert Übergänge, Dialoge und Rückmeldungen. Die Systemeinstellung „Bewegung reduzieren“ hat immer Vorrang.",
  motion: {
    reduced: "Reduziert — nahezu ohne Bewegung",
    subtle: "Dezent — kurze, ruhige Übergänge",
    expressive: "Lebendig — stärkere räumliche Rückmeldung",
  },
  workstation: "Arbeitsplatz",
  workstationLead: "Meldet der Dienst. Hier nicht änderbar.",
  factsLoading: "Die Auskünfte werden geladen.",
  securityNotices: "Sicherheitsmeldungen",
  securityNoticesLead: "Zählwerte und Zeitpunkte, keine Inhalte.",
  refresh: "Aktualisieren",
  noticesLoading: "Meldungen werden geladen",
  nothingNoticed: "Nichts aufgefallen. Die Liste ist beim nächsten Start wieder leer — sie liegt im Arbeitsspeicher und nicht in einer Datei neben Kundendaten.",
  times: "Mal",
  timesPlural: "Mal",
  lastAt: (when: string) => `zuletzt ${when}`,

  // ExportSettings (locked sentence SP-10)
  settingsSaved: "Einstellungen gespeichert.",
  exportTitle: "Export",
  exportLead: "Vor jedem Lauf erneut geprüft.",
  save: "Speichern",
  folderBlocksSave: "Solange dieser Ordner eingetragen ist, lässt sich nichts speichern. Wählen Sie einen anderen — die übrigen Einstellungen auf dieser Karte gehen dabei nicht verloren.",
  activeTemplate: "Aktive Exportvorlage",
  builtIn: (name: string) => `${name} (mitgeliefert)`,
  templateFieldsHint: "Welche Felder eine Vorlage enthaelt, legen Sie im Vorlageneditor fest.",
  editTemplates: "Vorlagen bearbeiten",
  roundingBeforeExport: "Rundung vor dem Export",
  roundUp: (label: string) => `${label} — immer auf die nächste Viertelstunde`,
  roundNearest: (label: string) => `${label} — zur nächstgelegenen`,
  roundingGroupTitle: "Gerundet wird die Tagesgruppe, nicht die einzelne Buchung",
  roundingGroupBody: "Alle noch offenen Buchungen desselben Todos an einem Kalendertag werden addiert, erst dann wird die Summe gerundet — mindestens 0,25. Zehn, zwanzig und fünf Minuten ergeben 0,75 und nicht dreimal 0,25.",
  settingsNotSaved: "Die Einstellungen wurden nicht gespeichert",
  setThisFolder: "Diesen Ordner einstellen?",
  readableNotes: "Die Exportdatei enthält lesbare Kundennotizen. Base64 ist eine Kodierung, keine Verschlüsselung — wer die Datei öffnen kann, kann sie lesen.",
  setFolderAnyway: "Ordner trotzdem einstellen",
  chooseOtherFolder: "Anderen Ordner wählen",
  folderAcknowledge: "Ich weiß, dass die Kundennotizen dorthin gelangen, und will es so.",

  // StatusFormDialog
  statusNameTaken: "Diesen Namen gibt es schon. Zwei Statuswerte mit demselben Namen wären in jeder Auswahl nicht auseinanderzuhalten.",
  newStatus: "Neuen Status anlegen",
  renameStatus: (name: string) => `${name} umbenennen`,
  newStatusLead: "Der neue Status steht danach in jeder Auswahl. Er bekommt keine Todos, solange keines darauf gestellt wird.",
  renameStatusLead: "Nur der Name ändert sich. Welche Todos diesen Status tragen, bleibt unverändert — und welche Karte auf dem Board steht, hängt ohnehin an den Tags.",
  create: "Anlegen",
  statusCreated: "Status angelegt.",
  statusRenamed: "Status umbenannt.",
  statusCreatedBody: (name: string) => `${name} steht ab sofort zur Auswahl. Standard für neue Todos ist er dadurch nicht.`,
  statusRenamedBody: (from: string, to: string) => `Aus ${from} wurde ${to}.`,
  name: "Name",
  statusPlaceholder: "z. B. Wartet auf Rückmeldung",
  newStatusHint: "Der neue Status steht am Ende der Reihenfolge. Verschieben lässt er sich danach mit den Pfeilen.",
  renameStatusHint: "Die Reihenfolge und der Standard bleiben, wie sie sind.",
  renameEverywhereTitle: "Das Umbenennen wirkt überall sofort",
  renameEverywhereBody: "Der Status ist eine Eigenschaft des Todos, kein Text an einer Stelle. Der neue Name steht danach in der Todo-Liste, in der Detailansicht, in jedem Formular und auf jeder Karte des Boards.",
  // StatusSettings (locked sentences SP-19 live in StatusRow)
  statusMoved: (name: string, position: number, total: number) => `${name} steht jetzt an ${String(position)}. Stelle von ${String(total)}.`,
  defaultChanged: "Standard geändert.",
  defaultChangedBody: (name: string) => `Neue Todos bekommen ab sofort ${name}. Vorhandene Todos ändern sich dadurch nicht.`,
  statusDeleted: "Status gelöscht.",
  statusDeletedBody: (name: string) => `${name} steht nicht mehr zur Auswahl.`,
  statusTitle: "Status",
  statusLead: "Nicht die Spalten des Boards.",
  createStatus: "Status anlegen",
  countsUnknown: "Wie viele Todos in einem Status stehen, ist gerade nicht bekannt",
  countAgain: "Erneut zählen",
  countsUnknownTail: "Anlegen, Umbenennen und Verschieben geht trotzdem. Beim Löschen entscheidet dann der Dienst — er weist einen belegten Status ab, ohne etwas umzuhängen.",
  noStatusTitle: "Es gibt keinen einzigen Status",
  noStatusBody: "Ohne Status lässt sich kein Todo anlegen — jedes neue Todo bekommt einen. Legen Sie mindestens einen an.",
  statusOrder: "Statuswerte in ihrer Reihenfolge",
  changeNotApplied: "Die Änderung wurde nicht übernommen",
  twoThings: "Zwei Dinge, bevor Sie etwas ändern",
  oneDefaultStrong: "Genau ein Status ist der Standard.",
  oneDefaultBody: " Jedes neue Todo bekommt ihn — aus der Liste, aus dem Board und aus dem Outlook-Add-in. Ein anderer wird Standard, indem Sie ihn dazu bestimmen; abwählen lässt sich der Standard nicht, nur weitergeben.",
  inUseStrong: "Ein Status mit Todos wird nicht gelöscht.",
  inUseBody: " SuperTakt hängt dabei nichts automatisch um — es gäbe keinen ehrlichen Zielwert. Stellen Sie die Todos zuerst auf einen anderen Status um; danach lässt sich der leere Status löschen.",
  deleteStatusTitle: "Status löschen?",
  statusNotDeleted: "Der Status wurde nicht gelöscht",
  deleteStatusLead: (name: string) => `${name} steht danach nicht mehr zur Auswahl — weder in der Liste noch in einem Formular.`,
  statusStillThere: (name: string) => `${name} steht weiterhin zur Auswahl. Der Dienst hat das Löschen abgelehnt und dabei nichts verändert.`,
  statusEmpty: "Der Status ist leer: Kein Todo trägt ihn. Vorhandene Todos ändern sich durch das Löschen nicht, weil keines betroffen ist.",
  todoAddedMeanwhile: " Zwischen dem Zählen und dem Löschen ist offenbar ein Todo dazugekommen. Schließen Sie diesen Dialog: Die Zeile nennt jetzt, wie viele es sind, und führt zu ihnen.",
  deleteStatus: "Status löschen",
  // StatusRow (locked sentences SP-19)
  lastStatus: "Das ist der letzte Status. Es muss mindestens einen geben, sonst bekäme ein neues Todo keinen.",
  isDefaultBlocker: "Das ist der Standard für neue Todos. Bestimmen Sie zuerst einen anderen zum Standard — sonst wäre nicht mehr festgelegt, was ein neues Todo bekommt.",
  oneTodoLeft: "Hier steht noch ein Todo. SuperTakt hängt es nicht von sich aus um; stellen Sie es zuerst auf einen anderen Status.",
  todosLeft: (todos: string) => `Hier stehen noch ${todos}. SuperTakt hängt sie nicht von sich aus um; stellen Sie sie zuerst auf einen anderen Status.`,
  todo: "Todo",
  todos: "Todos",
  counting: "Todos werden gezählt …",
  countUnknown: "Anzahl unbekannt",
  defaultForNew: " · Standard für neue Todos",
  showThisTodo: "Dieses Todo anzeigen",
  showTheseTodos: (todos: string) => `Diese ${todos} anzeigen`,
  defaultWord: "Standard",
  defaultForNewOf: (name: string) => ` für neue Todos — ${name}`,
  moveUp: (name: string) => `${name} nach oben`,
  moveDown: (name: string) => `${name} nach unten`,
  rename: "Umbenennen",
  deleteBlocked: (name: string) => `${name} löschen — derzeit nicht möglich`,
  deleteNamed: (name: string) => `${name} löschen`,
  // PrioritySettings
  prioritiesTitle: "Prioritäten",
  prioritiesLead: "Je höher die ganzzahlige Gewichtung, desto wichtiger die Priorität. Todos ohne Priorität stehen bei dieser Sortierung zuletzt.",
  addPriority: "Priorität hinzufügen",
  prioritiesLoading: "Prioritäten werden geladen",
  noPriorities: "Noch keine Prioritäten eingerichtet.",
  weightOf: (weight: number) => `Gewichtung ${String(weight)}`,
  edit: "Bearbeiten",
  delete: "Löschen",
  editPriority: "Priorität bearbeiten",
  createPriority: "Priorität anlegen",
  weight: "Gewichtung",
  weightHint: "Eine ganze Zahl. Größere Werte stehen im Kanban weiter oben.",
  deletePriorityTitle: "Priorität löschen?",
  willBeRemoved: (name: string) => `${name} wird entfernt.`,
  deletePriorityConsequence: "Zugeordnete Todos bleiben erhalten und haben danach keine Priorität.",
  // Same form as `deleteNamed`; the visible word stays in the name (WCAG 2.5.3).
  editNamed: (name: string) => `${name} bearbeiten`,
  priorityNameMissing: "Name fehlt.",
  priorityNameTooLong: "Name ist länger als 120 Zeichen.",
  priorityWeightInvalid: "Gewichtung ist keine ganze Zahl.",

  // DefaultTagSettings
  defaultTags: "Standard-Tags",
  defaultTagsLead: "Auch aus dem Add-in.",
  defaultTagsSaved: "Standard-Tags gespeichert.",
  noTagYet: "Noch kein Tag",
  noTagYetBody: "Legen Sie unten unter „Tags und Ordner“ einen Tag an. Danach können Sie ihn hier als Standard auswählen.",
  searchTag: "Tag suchen …",
  noDefaultTag: "Kein Standard-Tag gesetzt. Neue Todos entstehen ohne Tags — Regeln, die Tags verlangen, treffen sie damit zunächst nicht.",
  tagIs: "Tag wird",
  tagsAre: "Tags werden",
  attachedToEveryTodo: (tags: string) => `${tags} an jedes neue Todo gehängt.`,
  defaultTagsNotSaved: "Die Standard-Tags wurden nicht gespeichert",
  // DataTransferSettings
  importDone: "Import abgeschlossen",
  // A-28.6: only shown when the count is above zero (welle-18-fluss.md 4.5).
  importRejectedOver24h: (count: number) =>
    count === 1 ? "1 Buchung über 24 Stunden abgewiesen." : `${String(count)} Buchungen über 24 Stunden abgewiesen.`,
  importCounts: (todos: number, projects: number, tags: number, entries: number) =>
    `${String(todos)} Todos, ${String(projects)} Projekte, ${String(tags)} Tags und ${String(entries)} Zeitbuchungen wurden übernommen.`,
  dataImported: "Daten importiert.",
  backupCreated: "Datensicherung erstellt.",
  invalidJson: "Die gewählte Datei enthält kein gültiges JSON.",
  backupTitle: "SuperTakt-Datensicherung",
  backupLead: "Vollständiges, versioniertes JSON-Archiv.",
  backupHint: "Enthält Todos, Vermerke, Tags, Strukturen, Zeitbuchungen, Exporteinstellungen, Protokolle und Bildanhänge. Eine Wiederherstellung ersetzt den aktuellen Bestand.",
  downloadBackup: "Sicherung herunterladen",
  restoreBackup: "Sicherung wiederherstellen",
  todoistTitle: "Aus Todoist importieren",
  addsToData: "Ergänzt den vorhandenen Bestand.",
  todoistHint: "Entpacken Sie das Todoist-Backup und wählen Sie eine oder mehrere CSV-Dateien. Projekte werden Pools, Bereiche und Prioritäten werden Tags; Unteraufgaben bleiben im Vermerk nachvollziehbar.",
  chooseTodoist: "Todoist-CSV auswählen",
  superProductivityTitle: "Aus Super Productivity importieren",
  superProductivityHint: "Wählen Sie eine JSON-Datensicherung aus Super Productivity. Projekte, Bereiche, Tags, Fristen, Vermerke, Erledigt-Zustand und erfasste Zeiten werden übernommen.",
  outlookBridgeHint: "Leistungsnachweise aus OutlookBridge werden dem passenden Buchungstag zugeordnet. Ursprüngliche Notizen bleiben als Vermerk erhalten.",
  callPattern: "Call-Nummer aus Titel erkennen (Regex)",
  callPatternHint: "Die erste Klammergruppe liefert die Call-Nummer, ohne Gruppe der gesamte Treffer. Groß-/Kleinschreibung wird ignoriert. Leer lassen zum Ausschalten.",
  excludeTransferred: "Bereits übertragene Zeiten vom erneuten Export ausnehmen",
  excludeTransferredHint: "OutlookBridge-Markierungen „Eingetragen“ werden mit Herkunftsvermerk als ausgebucht übernommen. Ausgeschaltet werden alle Zeiten wieder offen importiert.",
  chooseSuperProductivity: "Super-Productivity-JSON auswählen",
  fileFailed: "Die Datei konnte nicht verarbeitet werden",
  restoreTitle: "SuperTakt-Datensicherung wiederherstellen?",
  restoreLead: "Der aktuelle Bestand wird vollständig durch den Inhalt der gewählten Sicherung ersetzt.",
  restoreConsequence: "Todos und Zeitbuchungen, die nur im aktuellen Bestand vorkommen, sind danach nicht mehr vorhanden.",
  restoreAcknowledge: "Ich habe den aktuellen Bestand bei Bedarf gesichert.",
  replaceData: "Bestand ersetzen",
  // PreferencesContext
  settingNotSaved: "Die Einstellung wurde nicht gespeichert",

  // Version check (locked sentences SP-12)
  updateOpenFailed: "Update konnte nicht geöffnet werden",
  releasePageOpened: "Die Release-Seite ist im Browser geöffnet.",
  releasePageOpenedBody: "Herunterladen und Installieren geschehen dort — SuperTakt tut von sich aus nichts davon.",
  versionRejected: "Die gemeldete Fassungsbezeichnung hat die Prüfung der Anwendung nicht bestanden. SuperTakt öffnet dafür keine Seite.",
  releasePageFailed: "Die Release-Seite ließ sich nicht öffnen. Möglicherweise ist auf diesem Rechner kein Browser eingerichtet; der angezeigte Verweis führt von Hand zum selben Ziel.",
  versionSkipped: (version: string) => `Fassung ${version} wird nicht mehr gemeldet.`,
  versionSkippedBody: "Eine spätere, höhere Fassung meldet sich wieder.",
  newerAvailableBefore: "Eine neuere Fassung von SuperTakt ist verfügbar: ",
  installedIs: (installed: string) => `. Installiert ist ${installed}.`,
  view: "Ansehen",
  closeUpdateNotice: "Hinweis auf die neue Fassung schließen",
  updateAvailable: "Update verfügbar",
  updateReady: "Eine neue Version von SuperTakt ist bereit.",
  decideLater: "Später entscheiden",
  installed: "Installiert",
  newVersion: "Neue Version",
  releasePageHint: "Die Release-Seite öffnet sich im Browser. Download und Installation starten Sie dort selbst.",
  officialReleasePage: "Offizielle Release-Seite auf GitHub",
  skipHint: "Überspringen blendet nur diese Version aus. Schließen erinnert beim nächsten Start.",
  openReleasePage: "Release-Seite öffnen",
  skip: "Überspringen",
  // OutlookSetup (A-23)
  httpsState: {
    ready: "Die Add-in-Seite ist über HTTPS erreichbar; das Serverzertifikat wurde geprüft.",
    unreachable: "Der lokale Add-in-Server ist nicht erreichbar. Prüfen Sie, ob SuperTakt vollständig gestartet ist.",
    tls_failed: "Die HTTPS-Prüfung ist fehlgeschlagen. Prüfen Sie das Zertifikatsvertrauen und starten Sie Outlook nach einer Änderung neu.",
    certificate_mismatch: "Der Add-in-Server verwendet ein anderes Zertifikat. Bitte SuperTakt neu starten und erneut prüfen.",
    page_missing: "HTTPS funktioniert, aber die Add-in-Seite fehlt. Bitte die SuperTakt-Installation prüfen.",
    certificate_invalid: "Das Zertifikat ist nicht gültig oder entspricht nicht dem lokalen SuperTakt-Serverzertifikat.",
  },
  outlookTitle: "Outlook lokal einrichten",
  outlookLead: "Zertifikat prüfen, Vertrauen bestätigen und anschließend das Add-in verbinden.",
  outlookChecking: "Lokales Zertifikat und HTTPS-Zugang werden geprüft …",
  outlookCheckFailed: "Die Einrichtung konnte nicht geprüft werden",
  outlookBrowserOnly: "Öffnen Sie diese Einstellungen in der SuperTakt-Desktop-App. Im Browser kann SuperTakt die lokalen Zertifikatsspeicher nicht prüfen.",
  outlookUnsupported: "Für dieses Betriebssystem ist die Zertifikatseinrichtung noch nicht verfügbar. Unterstützt werden Windows, Linux und macOS.",
  localAddress: "Lokale Adresse",
  issuedFor: "Ausgestellt für",
  issuer: "Aussteller",
  validFrom: "Gültig ab",
  validUntil: "Gültig bis",
  fingerprint: "SHA-256-Fingerabdruck",
  trustLinux: "Vertrauen in den Browser-Zertifikatsspeichern",
  trustMac: "Vertrauen im Benutzerschlüsselbund",
  trustWindows: "Vertrauen im Windows-Benutzerkonto",
  stored: "Hinterlegt",
  notStored: "Nicht hinterlegt",
  storeChromium: "Chromium / Chrome / Brave",
  storeFirefox: "Firefox-Profil",
  storeMac: "macOS-Benutzerschlüsselbund",
  trustStored: "Vertrauen hinterlegt",
  trustNotStored: "Vertrauen nicht hinterlegt",
  toolsMissing: "Zertifikatswerkzeuge fehlen",
  toolsMissingBody: "Für die Einrichtung werden OpenSSL und unter Linux die NSS-Werkzeuge mit certutil benötigt. Installieren Sie die fehlenden Werkzeuge und wählen Sie „Erneut prüfen“.",
  trustIncomplete: "Vertrauen nicht vollständig hinterlegt",
  trustIncompleteBody: "Mindestens ein Zertifikatsspeicher konnte nicht geändert werden. Schließen Sie den Browser vollständig und versuchen Sie es erneut. Erfolgreiche Einträge bleiben erhalten.",
  linuxImportHint: "Der Import gilt für den gemeinsamen Zertifikatsspeicher von Chromium und Brave und die hier erkannten Firefox-Profile dieses Benutzerkontos. Starten Sie den Browser nach dem Import vollständig neu. Separat abgeschottete Browser benötigen gegebenenfalls eine eigene Einrichtung.",
  httpsChecked: "Lokaler HTTPS-Server geprüft",
  httpsNotReady: "HTTPS-Zugang noch nicht bereit",
  checkAndTrust: "Zertifikat prüfen und vertrauen …",
  manifestHint: "Nach erfolgreicher HTTPS-Prüfung importieren Sie manifest.xml in Outlook und tragen das unten erzeugte Zugangstoken in den Add-in-Einstellungen ein. Das Zertifikat bestätigt die lokale Verbindung; die Anmeldung beim Add-in erfolgt weiterhin mit dem Token.",
  checkAgain: "Erneut prüfen",
  trustTitle: "Diesem lokalen Zertifikat vertrauen?",
  trustLead: "Bestätigen Sie den SHA-256-Fingerabdruck des oben gezeigten Zertifikats: ",
  trustLinuxConsequence: "Dieses Zertifikat wird als vertrauenswürdiges Serverzertifikat in den oben genannten Browser-Zertifikatsspeichern Ihres Benutzerkontos hinterlegt. Es gilt für localhost und 127.0.0.1. Dafür sind keine Administratorrechte nötig. Anschließend prüft SuperTakt die Einträge und die HTTPS-Verbindung. Starten Sie den Browser danach neu.",
  trustMacConsequence: "Dieses Zertifikat wird für localhost im Benutzerschlüsselbund als vertrauenswürdig hinterlegt. Bestätigen Sie gegebenenfalls die macOS-Sicherheitsabfrage. Anschließend prüft SuperTakt Vertrauen und HTTPS-Verbindung.",
  trustWindowsConsequence: "Dieses Zertifikat wird im Zertifikatsspeicher Ihres Windows-Benutzerkontos als vertrauenswürdig hinterlegt. Es gilt für localhost und 127.0.0.1. Bestätigen Sie auch die anschließend angezeigte Windows-Sicherheitsabfrage. Dafür haben Sie drei Minuten Zeit. SuperTakt prüft danach die HTTPS-Verbindung erneut.",
  trustAcknowledge: "Ich habe die Zertifikatsdaten geprüft und möchte diesem Zertifikat vertrauen.",
  trustConfirm: "Zertifikat vertrauen",
  // AddinSettings
  addinTitle: "Outlook-Add-in",
  addinLead: "Getrennt vom Zugang dieser Oberfläche.",
  tokenLoading: "Tokenzustand wird geladen",
  tokenUnreadable: "Die Tokendatei ist nicht lesbar",
  tokenUnreadableBody: "SuperTakt erzeugt von sich aus kein neues Token — das würde ein eingerichtetes Add-in ohne Vorwarnung aussperren. Erzeugen Sie eines von Hand, wenn Sie das Add-in neu einrichten wollen.",
  configured: "Eingerichtet",
  yes: "Ja",
  notConfigured: "Nein — das Add-in kann sich noch nicht ausweisen.",
  issued: "Ausgestellt",
  lastUsed: "Zuletzt benutzt",
  neverUsed: "Noch nie. Wenn das Add-in eingerichtet ist, spricht bisher niemand damit.",
  number: "Nummer",
  tokenNumber: (generation: number) => `${String(generation)}. Token`,
  tokenOnceTitle: "Dieses Token steht genau jetzt hier — und nie wieder",
  tokenOnceBody: "Tragen Sie es in den Add-in-Einstellungen in Outlook ein. Danach ist der Klartext weg; er wird nirgends gespeichert, auch nicht von dieser Seite.",
  toClipboard: "In die Zwischenablage",
  copied: "Kopiert.",
  copyFailed: "Das Kopieren hat nicht geklappt — markieren Sie den Wert von Hand.",
  hide: "Ausblenden",
  newToken: "Neues Token erzeugen",
  createToken: "Token erzeugen",
  newTokenTitle: "Neues Add-in-Token erzeugen?",
  newTokenLead: "Es entsteht genau ein gültiger Abdruck. Das bisherige Token wird im selben Augenblick ungültig.",
  newTokenConsequence: "Das Add-in funktioniert erst wieder, wenn Sie das neue Token dort eingetragen haben. Eine Nachfrist gibt es nicht.",
  // An address exception of `proof:surface` (first person, not an imperative).
  newTokenAcknowledge: "Ich habe Outlook zur Hand und trage das neue Token gleich ein.",
  tokenCreated: "Neues Token erzeugt.",
  tokenCreatedBody: "Das alte ist ab sofort ungültig. Der Klartext steht nur jetzt auf dem Bildschirm.",
  tokenNotCreated: "Das Token wurde nicht erzeugt",
  // Database location advice (locked sentences SP-14: bodies and remedies)
  databaseAdvice: {
    sync_folder: {
      title: "Der Bestand liegt in einem Synchronisierungsordner",
      body: "In dieser Datei stehen alle Todos, Buchungen und Vermerke im Klartext. Der Client des Anbieters lädt sie fortlaufend hoch — auch während SuperTakt läuft, ohne Rückfrage und ohne dass es jemand sieht. Damit liegen die Daten Ihrer Kunden bei einem Anbieter. Dazu kommt ein zweites Problem: Eine Datenbankdatei, die mitten im Schreiben kopiert wird, kommt dort regelmäßig unbrauchbar an, und wenn zwei Rechner denselben Ordner synchronisieren, beschädigen sie einander die Datei.",
      remedy: "SuperTakt kann den Ablageort nicht verlegen — er folgt dem Anwendungsdatenverzeichnis dieses Benutzers. Nehmen Sie diesen Ordner im Synchronisierungsclient von der Übertragung aus.",
    },
    network_share: {
      title: "Der Bestand liegt nicht auf diesem Rechner",
      body: "Der Pfad zeigt auf eine Netzfreigabe. Eine SQLite-Datei über das Netz zu führen gilt als unsicher: Die Sperren, mit denen sie sich gegen gleichzeitige Zugriffe schützt, wirken über viele Netzdateisysteme nicht zuverlässig, und ein Verbindungsabriss mitten im Schreiben kann sie beschädigen. Außerdem liegen die Kundendaten damit auf einem anderen Rechner — bei einem Produkt, das laut E-001 vollständig lokal arbeitet.",
      remedy: "Das Anwendungsdatenverzeichnis gehört auf die lokale Festplatte. Wenn es hier im Netz liegt, ist das eine Einstellung des Windows-Profils; das entscheidet die Verwaltung des Rechners, nicht SuperTakt.",
    },
    roaming_profile: {
      title: "Der Bestand liegt im servergespeicherten Profil",
      body: "Der Ordner AppData\\Roaming wird beim An- und Abmelden auf einen Dateiserver kopiert, wenn das Konto ein servergespeichertes Profil hat. Der ganze Bestand wandert dann mit, Kundennotizen inbegriffen — und kopiert wird auch eine Datei, die gerade noch geöffnet war. Genau deshalb legt SuperTakt seine Daten unter AppData\\Local ab (E-018).",
      remedy: "Steht hier trotzdem Roaming, ist dieses Windows-Profil anders eingerichtet. Auch das entscheidet die Verwaltung des Rechners.",
    },
    temporary_folder: {
      title: "Der Bestand liegt in einem Ordner für flüchtige Dateien",
      body: "Ordner mit dem Namen Temp oder tmp werden von der Windows-Speicheroptimierung, von Aufräumwerkzeugen und je nach System beim Neustart geleert — ohne Rückfrage. Was Sie eintragen, kann beim nächsten Start fehlen. Im Prüf- und Entwicklungsbetrieb ist das gewollt; auf einem Arbeitsplatz ist es ein Fehler in der Einrichtung.",
      remedy: "Starten Sie SuperTakt über die installierte Verknüpfung. Ein abweichendes Anwendungsdatenverzeichnis kommt aus der Umgebung, in der die Anwendung gestartet wurde, und nicht aus den Einstellungen.",
    },
  },
  // WorkstationFacts
  billedAs: "Abgerechnet wird unter",
  noUserName: "Der Dienst nennt keinen Benutzernamen",
  noUserNameBody: "Ohne Namen lässt sich hier nicht nachsehen, wem die Abrechnung Ihre Arbeitszeit zuordnet. Im Export steht trotzdem einer — welcher, zeigt nach dem ersten Lauf das Exportprotokoll.",
  noUserNameRemedy: "Beenden Sie SuperTakt und starten Sie die Anwendung über ihre Verknüpfung neu. Der Name kommt beim Start von der Anwendungshülle; fehlt er, ist der Dienst nicht auf dem üblichen Weg gestartet worden.",
  userNameBefore: "Dieser Name steht in ",
  userNameStrong: "jeder Zeile jeder Exportdatei",
  userNameAfter: ". Er sagt der Abrechnung, wessen Arbeitszeit sie vor sich hat.",
  userNameSourceBefore: "SuperTakt bekommt ihn beim Start vom Betriebssystem, nicht aus einer Umgebungsvariablen: ",
  userNameSourceMiddle: " ändert ihn nicht, und über keine Route lässt er sich setzen. Deshalb steht er hier: nachzusehen ist er damit ",
  userNameSourceStrong: "vor",
  userNameSourceAfter: " dem ersten Export und nicht erst danach im Exportprotokoll.",
  impact: {
    confidentiality: "Die Kundendaten verlassen diesen Rechner",
    durability: "Der Bestand kann verlorengehen oder beschädigt werden",
  },
  foundInPath: "Gefunden im Pfad",
  dataLiesIn: "Der Bestand liegt in",
  noFile: "Diese Fassung führt keine Datei",
  noFileBody: "Der Bestand steht im Arbeitsspeicher: Alles, was Sie eintragen, ist beim Beenden weg. So läuft der Prüfbetrieb und die Musterseite des Designsystems. Im installierten SuperTakt steht an dieser Stelle ein Pfad.",
  copyPath: "Pfad kopieren",
  copyPathFailed: "Das Kopieren hat nicht geklappt — markieren Sie den Pfad von Hand.",
  oneFileBody: "In dieser einen Datei stehen alle Todos, Buchungen und Vermerke — im Klartext. SuperTakt kann den Ort nicht verlegen: Er folgt dem Anwendungsdatenverzeichnis dieses Benutzers und ist über keine Einstellung verstellbar.",
  backupBefore: "Zum Sichern: SuperTakt beenden und den ",
  backupStrong: "ganzen Ordner",
  backupMiddle: " kopieren. Neben ",
  backupSidecars: " führt SQLite die Nachbardateien ",
  and: " und ",
  backupAfter: "; die Datei allein kann unvollständig sein.",
  pathNothing: "Am Pfad ist nichts aufgefallen — das ist keine Entwarnung, sondern eine Nichtaussage: ",
  pathOnlyJudged: "Beurteilt wurde nur, was im Pfad steht. ",
  limitBefore: "Zum ",
  limitExportStrong: "Exportordner",
  limitMiddle: " fragt der Dienst das Betriebssystem und belegt Merkmale; zu ",
  limitFileStrong: "dieser Datei",
  limitDrive: " fragt er nur nach den Zugriffsrechten. Ein zugeordnetes Netzlaufwerk wie ",
  limitAfter: " und ein Ordner, den ein Synchronisierungsclient nach einer Umbenennung weiter überwacht, stehen in keinem Pfad.",
};

const en: typeof de = {
  noticeLabel: {
    auth_failure_burst: "Repeated sign-in attempts without valid proof",
    token_in_url: "A proof was in an address line and was rejected",
    origin_rejected: "An access came from a foreign origin",
    host_rejected: "An access named a foreign host name",
    file_permissions_wide: "A file in the data folder has too wide permissions",
  },
  areas: {
    darstellung: { label: "Appearance", hint: "Themes, colour mode, row density" },
    timer: { label: "Timer", hint: "Work done when stopping" },
    export: { label: "Export", hint: "Target folder, template, rounding" },
    daten: { label: "Data", hint: "Back up, restore, move" },
    tags: { label: "Tags", hint: "Tags, folders and default tags" },
    regeln: { label: "Rules", hint: "Pools and Kanban columns" },
    prioritaeten: { label: "Priorities", hint: "Priorities and their weighting" },
    status: { label: "Status", hint: "Status values of a todo" },
    addin: { label: "Outlook add-in", hint: "Access of the add-in" },
    arbeitsplatz: { label: "Workstation", hint: "Billing name, location, notices" },
  },
  settingsTitle: "Settings",
  areasNav: "Settings areas",
  settingsLoading: "Loading settings",
  density: {
    comfortable: "Normal — more space between rows",
    compact: "Compact — more rows on the screen",
  },
  timerTitle: "Timer",
  timerLead: "Decide when you want to enter your work done.",
  promptOnStop: "Ask for work done when stopping",
  promptOnStopHint: "When off, the time is booked at once, also when switching to another timer. Existing work done is kept; missing text can be added later in the bookings overview.",
  detectIdle: "Detect inactive time",
  detectIdleHint: "When you return, the timer pauses until you leave the inactive time out as a break, assign it to a todo or split it. Open assignments are kept when this setting is switched off.",
  timerWhenIdle: "Timer when inactive",
  keepRunning: "Keep running",
  pauseUntilAssigned: "Pause until assigned",
  detectIdleAfter: "Detect inactivity after",
  minutes: (count: number) => `${String(count)} ${count === 1 ? "minute" : "minutes"}`,
  idleChecking: "Checking inactivity detection …",
  idleSupported: "System-wide detection available — input in other programs counts as activity too.",
  idleUnsupported: "System-wide detection is not available here. It needs the desktop app and a supported system interface.",
  idlePrivacy: "Only points in time are read; no keys, texts or program contents are recorded.",
  displayTitle: "Appearance",
  displayLead: "Everything here applies immediately and is kept on the next start.",
  language: "Language",
  languageHint: "The Outlook add-in and messages from the local service stay in German for now.",
  versionCheckTitle: "Version check",
  versionCheckLabel: "Check for new versions",
  versionCheckHint: "Queries SuperTakt's releases on GitHub. When off, SuperTakt makes no outside connection.",
  permissionsTitle: "The data files are readable by other users",
  permissionsBody: "SuperTakt could not restrict the permissions at start. The data contains customer data and internal notes.",
  permissionsRemedy: "Restrict the files in the folder above to your own user, then restart SuperTakt. The warning disappears after the restart.",
  colorMode: "Colour mode",
  modeSystem: "System",
  modeSystemHint: "Follows the colour mode of the operating system.",
  modeDark: "Dark",
  modeLight: "Light",
  fixedColors: (dark: boolean) => `This theme uses fixed ${dark ? "dark" : "light"} colours. Free colour choice is available with Classic and the adaptable themes.`,
  chooseTheme: "Choose theme",
  themeMode: { dark: "Dark · ", light: "Light · ", auto: "Light & dark · " },
  themeHint: "All themes use the classic layout. Classic is the default.",
  rowDensity: "Row density",
  rowDensityHint: "Sets the spacing in tables and lists, independent of the chosen theme.",
  motionIntensity: "Interface motion",
  motionIntensityHint: "Controls transitions, dialogs, and feedback. Your system’s “reduce motion” setting always takes priority.",
  motion: {
    reduced: "Reduced — almost no movement",
    subtle: "Subtle — brief, calm transitions",
    expressive: "Expressive — stronger spatial feedback",
  },
  workstation: "Workstation",
  workstationLead: "Reported by the service. Not changeable here.",
  factsLoading: "Loading the information.",
  securityNotices: "Security notices",
  securityNoticesLead: "Counts and points in time, no contents.",
  refresh: "Refresh",
  noticesLoading: "Loading notices",
  nothingNoticed: "Nothing noticed. The list is empty again on the next start — it lives in memory, not in a file next to customer data.",
  times: "time",
  timesPlural: "times",
  lastAt: (when: string) => `last ${when}`,

  settingsSaved: "Settings saved.",
  exportTitle: "Export",
  exportLead: "Checked again before every run.",
  save: "Save",
  folderBlocksSave: "As long as this folder is entered, nothing can be saved. Choose another one — the other settings on this card are not lost.",
  activeTemplate: "Active export template",
  builtIn: (name: string) => `${name} (built-in)`,
  templateFieldsHint: "Which fields a template contains is set in the template editor.",
  editTemplates: "Edit templates",
  roundingBeforeExport: "Rounding before export",
  roundUp: (label: string) => `${label} — always to the next quarter hour`,
  roundNearest: (label: string) => `${label} — to the nearest`,
  roundingGroupTitle: "The day group is rounded, not the single booking",
  roundingGroupBody: "All still open bookings of the same todo on one calendar day are added up, and only then is the sum rounded — at least 0.25. Ten, twenty and five minutes yield 0.75 and not three times 0.25.",
  settingsNotSaved: "The settings were not saved",
  setThisFolder: "Set this folder?",
  readableNotes: "The export file contains readable customer notes. Base64 is an encoding, not encryption — whoever can open the file can read it.",
  setFolderAnyway: "Set folder anyway",
  chooseOtherFolder: "Choose another folder",
  folderAcknowledge: "I know that the customer notes go there, and I want it that way.",

  statusNameTaken: "This name already exists. Two status values with the same name could not be told apart in any selection.",
  newStatus: "Create new status",
  renameStatus: (name: string) => `Rename ${name}`,
  newStatusLead: "The new status is then in every selection. It gets no todos as long as none is set to it.",
  renameStatusLead: "Only the name changes. Which todos carry this status stays unchanged — and which card is on the board depends on the tags anyway.",
  create: "Create",
  statusCreated: "Status created.",
  statusRenamed: "Status renamed.",
  statusCreatedBody: (name: string) => `${name} can be chosen from now on. That does not make it the default for new todos.`,
  statusRenamedBody: (from: string, to: string) => `${from} became ${to}.`,
  name: "Name",
  statusPlaceholder: "e.g. Waiting for reply",
  newStatusHint: "The new status is at the end of the order. It can then be moved with the arrows.",
  renameStatusHint: "The order and the default stay as they are.",
  renameEverywhereTitle: "Renaming applies everywhere at once",
  renameEverywhereBody: "The status is a property of the todo, not a text in one place. The new name then appears in the todo list, the detail view, every form and every card on the board.",
  statusMoved: (name: string, position: number, total: number) => `${name} is now at position ${String(position)} of ${String(total)}.`,
  defaultChanged: "Default changed.",
  defaultChangedBody: (name: string) => `New todos get ${name} from now on. Existing todos do not change.`,
  statusDeleted: "Status deleted.",
  statusDeletedBody: (name: string) => `${name} can no longer be chosen.`,
  statusTitle: "Status",
  statusLead: "Not the columns of the board.",
  createStatus: "Create status",
  countsUnknown: "How many todos are in a status is not known right now",
  countAgain: "Count again",
  countsUnknownTail: "Creating, renaming and moving still work. When deleting, the service decides — it rejects a status in use without reassigning anything.",
  noStatusTitle: "There is not a single status",
  noStatusBody: "Without a status no todo can be created — every new todo gets one. Create at least one.",
  statusOrder: "Status values in their order",
  changeNotApplied: "The change was not applied",
  twoThings: "Two things before you change anything",
  oneDefaultStrong: "Exactly one status is the default.",
  oneDefaultBody: " Every new todo gets it — from the list, the board and the Outlook add-in. Another one becomes the default when you make it so; the default cannot be deselected, only passed on.",
  inUseStrong: "A status with todos is not deleted.",
  inUseBody: " SuperTakt does not reassign anything automatically — there would be no honest target value. Move the todos to another status first; then the empty status can be deleted.",
  deleteStatusTitle: "Delete status?",
  statusNotDeleted: "The status was not deleted",
  deleteStatusLead: (name: string) => `${name} then can no longer be chosen — neither in the list nor in any form.`,
  statusStillThere: (name: string) => `${name} can still be chosen. The service refused the deletion and changed nothing.`,
  statusEmpty: "The status is empty: no todo carries it. Existing todos do not change by deleting, because none is affected.",
  todoAddedMeanwhile: " Apparently a todo was added between counting and deleting. Close this dialog: the row now says how many there are and leads to them.",
  deleteStatus: "Delete status",
  lastStatus: "This is the last status. There must be at least one, otherwise a new todo would get none.",
  isDefaultBlocker: "This is the default for new todos. Make another one the default first — otherwise it would no longer be set what a new todo gets.",
  oneTodoLeft: "One todo is still here. SuperTakt does not reassign it by itself; move it to another status first.",
  todosLeft: (todos: string) => `${todos} are still here. SuperTakt does not reassign them by itself; move them to another status first.`,
  todo: "todo",
  todos: "todos",
  counting: "Counting todos …",
  countUnknown: "Count unknown",
  defaultForNew: " · default for new todos",
  showThisTodo: "Show this todo",
  showTheseTodos: (todos: string) => `Show these ${todos}`,
  defaultWord: "Default",
  defaultForNewOf: (name: string) => ` for new todos — ${name}`,
  moveUp: (name: string) => `Move ${name} up`,
  moveDown: (name: string) => `Move ${name} down`,
  rename: "Rename",
  deleteBlocked: (name: string) => `Delete ${name} — not possible right now`,
  deleteNamed: (name: string) => `Delete ${name}`,
  prioritiesTitle: "Priorities",
  prioritiesLead: "The higher the integer weighting, the more important the priority. Todos without a priority come last in this sorting.",
  addPriority: "Add priority",
  prioritiesLoading: "Loading priorities",
  noPriorities: "No priorities set up yet.",
  weightOf: (weight: number) => `Weighting ${String(weight)}`,
  edit: "Edit",
  delete: "Delete",
  editPriority: "Edit priority",
  createPriority: "Create priority",
  weight: "Weighting",
  weightHint: "A whole number. Higher values come first on the Kanban.",
  deletePriorityTitle: "Delete priority?",
  willBeRemoved: (name: string) => `${name} is removed.`,
  deletePriorityConsequence: "Assigned todos are kept and then have no priority.",
  editNamed: (name: string) => `Edit ${name}`,
  priorityNameMissing: "Name is missing.",
  priorityNameTooLong: "Name is longer than 120 characters.",
  priorityWeightInvalid: "Weighting is not a whole number.",

  defaultTags: "Default tags",
  defaultTagsLead: "Also from the add-in.",
  defaultTagsSaved: "Default tags saved.",
  noTagYet: "No tag yet",
  noTagYetBody: "Create a tag below under “Tags and folders”. Then you can choose it here as a default.",
  searchTag: "Search tag …",
  noDefaultTag: "No default tag set. New todos are created without tags — rules that require tags do not match them at first.",
  tagIs: "tag is",
  tagsAre: "tags are",
  attachedToEveryTodo: (tags: string) => `${tags} attached to every new todo.`,
  defaultTagsNotSaved: "The default tags were not saved",
  importDone: "Import finished",
  importRejectedOver24h: (count: number) =>
    count === 1 ? "1 booking over 24 hours rejected." : `${String(count)} bookings over 24 hours rejected.`,
  importCounts: (todos: number, projects: number, tags: number, entries: number) =>
    `${String(todos)} todos, ${String(projects)} projects, ${String(tags)} tags and ${String(entries)} time bookings were taken over.`,
  dataImported: "Data imported.",
  backupCreated: "Backup created.",
  invalidJson: "The chosen file contains no valid JSON.",
  backupTitle: "SuperTakt backup",
  backupLead: "Complete, versioned JSON archive.",
  backupHint: "Contains todos, internal notes, tags, structures, time bookings, export settings, logs and image attachments. A restore replaces the current data.",
  downloadBackup: "Download backup",
  restoreBackup: "Restore backup",
  todoistTitle: "Import from Todoist",
  addsToData: "Adds to the existing data.",
  todoistHint: "Unpack the Todoist backup and choose one or more CSV files. Projects become pools, sections and priorities become tags; subtasks stay traceable in the internal note.",
  chooseTodoist: "Choose Todoist CSV",
  superProductivityTitle: "Import from Super Productivity",
  superProductivityHint: "Choose a JSON backup from Super Productivity. Projects, sections, tags, due dates, notes, done state and recorded times are taken over.",
  outlookBridgeHint: "Work records from OutlookBridge are assigned to the matching booking day. Original notes are kept as internal note.",
  callPattern: "Detect call number from title (regex)",
  callPatternHint: "The first capture group yields the call number, without a group the whole match. Case is ignored. Leave empty to switch off.",
  excludeTransferred: "Exclude times already transferred from another export",
  excludeTransferredHint: "OutlookBridge marks “Eingetragen” are taken over as written off with an origin note. When off, all times are imported as open again.",
  chooseSuperProductivity: "Choose Super Productivity JSON",
  fileFailed: "The file could not be processed",
  restoreTitle: "Restore SuperTakt backup?",
  restoreLead: "The current data is replaced completely by the content of the chosen backup.",
  restoreConsequence: "Todos and time bookings that exist only in the current data are gone afterwards.",
  restoreAcknowledge: "I have backed up the current data if needed.",
  replaceData: "Replace data",
  settingNotSaved: "The setting was not saved",

  updateOpenFailed: "The update could not be opened",
  releasePageOpened: "The release page is open in the browser.",
  releasePageOpenedBody: "Downloading and installing happen there — SuperTakt does none of it by itself.",
  versionRejected: "The reported version name did not pass the application's check. SuperTakt opens no page for it.",
  releasePageFailed: "The release page could not be opened. Possibly no browser is set up on this computer; the link shown leads to the same target by hand.",
  versionSkipped: (version: string) => `Version ${version} is no longer reported.`,
  versionSkippedBody: "A later, higher version reports itself again.",
  newerAvailableBefore: "A newer version of SuperTakt is available: ",
  installedIs: (installed: string) => `. Installed is ${installed}.`,
  view: "View",
  closeUpdateNotice: "Close the notice about the new version",
  updateAvailable: "Update available",
  updateReady: "A new version of SuperTakt is ready.",
  decideLater: "Decide later",
  installed: "Installed",
  newVersion: "New version",
  releasePageHint: "The release page opens in the browser. You start download and installation there yourself.",
  officialReleasePage: "Official release page on GitHub",
  skipHint: "Skip hides only this version. Close reminds you on the next start.",
  openReleasePage: "Open release page",
  skip: "Skip",
  httpsState: {
    ready: "The add-in page is reachable over HTTPS; the server certificate was checked.",
    unreachable: "The local add-in server cannot be reached. Check whether SuperTakt has fully started.",
    tls_failed: "The HTTPS check failed. Check the certificate trust and restart Outlook after a change.",
    certificate_mismatch: "The add-in server uses a different certificate. Please restart SuperTakt and check again.",
    page_missing: "HTTPS works, but the add-in page is missing. Please check the SuperTakt installation.",
    certificate_invalid: "The certificate is not valid or does not match the local SuperTakt server certificate.",
  },
  outlookTitle: "Set up Outlook locally",
  outlookLead: "Check the certificate, confirm trust, then connect the add-in.",
  outlookChecking: "Checking local certificate and HTTPS access …",
  outlookCheckFailed: "The setup could not be checked",
  outlookBrowserOnly: "Open these settings in the SuperTakt desktop app. In the browser, SuperTakt cannot check the local certificate stores.",
  outlookUnsupported: "Certificate setup is not available for this operating system yet. Supported are Windows, Linux and macOS.",
  localAddress: "Local address",
  issuedFor: "Issued for",
  issuer: "Issuer",
  validFrom: "Valid from",
  validUntil: "Valid until",
  fingerprint: "SHA-256 fingerprint",
  trustLinux: "Trust in the browser certificate stores",
  trustMac: "Trust in the user keychain",
  trustWindows: "Trust in the Windows user account",
  stored: "Stored",
  notStored: "Not stored",
  storeChromium: "Chromium / Chrome / Brave",
  storeFirefox: "Firefox profile",
  storeMac: "macOS user keychain",
  trustStored: "trust stored",
  trustNotStored: "trust not stored",
  toolsMissing: "Certificate tools missing",
  toolsMissingBody: "The setup needs OpenSSL and, on Linux, the NSS tools with certutil. Install the missing tools and choose “Check again”.",
  trustIncomplete: "Trust not fully stored",
  trustIncompleteBody: "At least one certificate store could not be changed. Close the browser completely and try again. Successful entries are kept.",
  linuxImportHint: "The import applies to the shared certificate store of Chromium and Brave and to the Firefox profiles of this user account found here. Restart the browser completely after the import. Separately sandboxed browsers may need their own setup.",
  httpsChecked: "Local HTTPS server checked",
  httpsNotReady: "HTTPS access not ready yet",
  checkAndTrust: "Check and trust certificate …",
  manifestHint: "After a successful HTTPS check, import manifest.xml into Outlook and enter the access token generated below in the add-in settings. The certificate confirms the local connection; signing in to the add-in still uses the token.",
  checkAgain: "Check again",
  trustTitle: "Trust this local certificate?",
  trustLead: "Confirm the SHA-256 fingerprint of the certificate shown above: ",
  trustLinuxConsequence: "This certificate is stored as a trusted server certificate in the browser certificate stores of your user account named above. It applies to localhost and 127.0.0.1. No administrator rights are needed. SuperTakt then checks the entries and the HTTPS connection. Restart the browser afterwards.",
  trustMacConsequence: "This certificate is stored as trusted for localhost in the user keychain. Confirm the macOS security prompt if asked. SuperTakt then checks trust and HTTPS connection.",
  trustWindowsConsequence: "This certificate is stored as trusted in the certificate store of your Windows user account. It applies to localhost and 127.0.0.1. Also confirm the Windows security prompt shown afterwards. You have three minutes for it. SuperTakt then checks the HTTPS connection again.",
  trustAcknowledge: "I have checked the certificate data and want to trust this certificate.",
  trustConfirm: "Trust certificate",
  addinTitle: "Outlook add-in",
  addinLead: "Separate from the access of this interface.",
  tokenLoading: "Loading token state",
  tokenUnreadable: "The token file cannot be read",
  tokenUnreadableBody: "SuperTakt does not create a new token by itself — that would lock out a configured add-in without warning. Create one by hand if you want to set up the add-in again.",
  configured: "Configured",
  yes: "Yes",
  notConfigured: "No — the add-in cannot identify itself yet.",
  issued: "Issued",
  lastUsed: "Last used",
  neverUsed: "Never. If the add-in is configured, nobody has talked to it so far.",
  number: "Number",
  tokenNumber: (generation: number) => `Token no. ${String(generation)}`,
  tokenOnceTitle: "This token is shown right now — and never again",
  tokenOnceBody: "Enter it in the add-in settings in Outlook. After that the plain text is gone; it is stored nowhere, not even by this page.",
  toClipboard: "Copy to clipboard",
  copied: "Copied.",
  copyFailed: "Copying did not work — select the value by hand.",
  hide: "Hide",
  newToken: "Create new token",
  createToken: "Create token",
  newTokenTitle: "Create new add-in token?",
  newTokenLead: "Exactly one valid fingerprint is created. The previous token becomes invalid in the same moment.",
  newTokenConsequence: "The add-in only works again once you have entered the new token there. There is no grace period.",
  newTokenAcknowledge: "I have Outlook at hand and will enter the new token right away.",
  tokenCreated: "New token created.",
  tokenCreatedBody: "The old one is invalid from now on. The plain text is only on the screen now.",
  tokenNotCreated: "The token was not created",
  databaseAdvice: {
    sync_folder: {
      title: "The data is in a synchronised folder",
      body: "This file holds all todos, bookings and internal notes in plain text. The provider's client uploads it continuously — even while SuperTakt runs, without asking and without anyone seeing it. Your customers' data then sits with a provider. There is a second problem: a database file copied in the middle of writing regularly arrives unusable, and if two computers synchronise the same folder, they damage each other's file.",
      remedy: "SuperTakt cannot move the location — it follows this user's application data folder. Exclude this folder from transfer in the synchronisation client.",
    },
    network_share: {
      title: "The data is not on this computer",
      body: "The path points to a network share. Running an SQLite file over the network is considered unsafe: the locks that protect it against simultaneous access do not work reliably over many network file systems, and a connection drop in the middle of writing can damage it. Also, the customer data then sits on another computer — for a product that works fully locally according to E-001.",
      remedy: "The application data folder belongs on the local disk. If it is on the network here, that is a setting of the Windows profile; the administration of the computer decides that, not SuperTakt.",
    },
    roaming_profile: {
      title: "The data is in the roaming profile",
      body: "The folder AppData\\Roaming is copied to a file server at sign-in and sign-out if the account has a roaming profile. All data travels along, customer notes included — and a file that was still open is copied too. This is exactly why SuperTakt keeps its data under AppData\\Local (E-018).",
      remedy: "If Roaming shows here anyway, this Windows profile is set up differently. The administration of the computer decides that too.",
    },
    temporary_folder: {
      title: "The data is in a folder for temporary files",
      body: "Folders named Temp or tmp are emptied by Windows Storage Sense, cleanup tools and, depending on the system, on restart — without asking. What you enter may be missing on the next start. In test and development operation that is intended; on a workstation it is a setup error.",
      remedy: "Start SuperTakt via the installed shortcut. A different application data folder comes from the environment the application was started in, not from the settings.",
    },
  },
  billedAs: "Billed as",
  noUserName: "The service reports no user name",
  noUserNameBody: "Without a name, you cannot check here to whom billing assigns your working time. The export still carries one — which, the export log shows after the first run.",
  noUserNameRemedy: "Quit SuperTakt and start the application again via its shortcut. The name comes from the application shell at start; if it is missing, the service was not started the usual way.",
  userNameBefore: "This name is in ",
  userNameStrong: "every row of every export file",
  userNameAfter: ". It tells billing whose working time it has in front of it.",
  userNameSourceBefore: "SuperTakt gets it from the operating system at start, not from an environment variable: ",
  userNameSourceMiddle: " does not change it, and no route can set it. That is why it is shown here: you can check it ",
  userNameSourceStrong: "before",
  userNameSourceAfter: " the first export and not only afterwards in the export log.",
  impact: {
    confidentiality: "The customer data leaves this computer",
    durability: "The data can be lost or damaged",
  },
  foundInPath: "Found in the path",
  dataLiesIn: "The data is stored in",
  noFile: "This version keeps no file",
  noFileBody: "The data lives in memory: everything you enter is gone on quit. This is how test operation and the design system page run. In the installed SuperTakt a path is shown here.",
  copyPath: "Copy path",
  copyPathFailed: "Copying did not work — select the path by hand.",
  oneFileBody: "This one file holds all todos, bookings and internal notes — in plain text. SuperTakt cannot move the location: it follows this user's application data folder and cannot be changed by any setting.",
  backupBefore: "To back up: quit SuperTakt and copy the ",
  backupStrong: "whole folder",
  backupMiddle: ". Next to ",
  backupSidecars: " SQLite keeps the companion files ",
  and: " and ",
  backupAfter: "; the file alone can be incomplete.",
  pathNothing: "Nothing was noticed about the path — that is no all-clear, but no statement at all: ",
  pathOnlyJudged: "Only what is in the path was judged. ",
  limitBefore: "For the ",
  limitExportStrong: "export folder",
  limitMiddle: " the service asks the operating system and proves traits; for ",
  limitFileStrong: "this file",
  limitDrive: " it asks about the access rights only. A mapped network drive such as ",
  limitAfter: " and a folder a synchronisation client keeps watching after a rename appear in no path.",
};

export function settingsTexts(): typeof de {
  return pickTexts({ de, en });
}

/**
 * English theme labels and hints. The German ones come from the theme files
 * (`themeCatalog.generated.ts`, written by `scripts/sync-themes.mjs`); proper
 * theme names stay as they are, only "Klassisch" has an English word.
 */
const THEME_TEXT_EN: Readonly<Record<string, { readonly label?: string; readonly hint: string }>> = {
  classic: { label: "Classic", hint: "Default · the classic SuperTakt design" },
  arc: { hint: "Slate grey with blue accents" },
  cybr: { hint: "Cyberpunk · deep surfaces and neon accents" },
  "dark-base": { hint: "Neutral black with pink accents" },
  dracula: { hint: "Violet and pastel on anthracite" },
  everfrost: { hint: "Forest green and warm natural tones · Everforest palette" },
  glass: { hint: "Subtly translucent glass surfaces" },
  lines: { hint: "Clear outlines and reduced surfaces" },
  "liquid-glass": { hint: "Soft light reflections on tinted glass" },
  "nord-polar-night": { hint: "Cool blue and grey tones" },
  "nord-snow-storm": { hint: "Bright snow white and arctic blue" },
  plainspace: { hint: "Warm paper colours and subtle accents" },
  rainbow: { hint: "Multicoloured accents and soft gradients" },
  zen: { hint: "Calm, reduced surfaces" },
  velvet: { hint: "Velvety dark with soft light accents" },
  "catppuccin-latte": { hint: "Light pastel colours" },
  "catppuccin-frappe": { hint: "Soft pastels on smoky blue" },
  "catppuccin-macchiato": { hint: "Pastel on deep blue" },
  "catppuccin-mocha": { hint: "Pastel on dark mauve" },
};

export function themeText(preset: { readonly value: string; readonly label: string; readonly hint: string }): {
  readonly label: string;
  readonly hint: string;
} {
  if (getLanguage() === "de") return { label: preset.label, hint: preset.hint };
  const english = THEME_TEXT_EN[preset.value];
  return { label: english?.label ?? preset.label, hint: english?.hint ?? preset.hint };
}
