import { pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // IdleRecovery and IdleTaskSelect (A-24)
  pickTaskForTime: "Wählen Sie das Todo aus, auf das die Zeit gebucht werden soll.",
  distributeAll: "Verteilen Sie die gesamte Zeit. Geben Sie Minuten oder eine Dauer als Stunden:Minuten:Sekunden ein.",
  idleAssigned: "Inaktive Zeit zugeordnet.",
  idleAlreadyHandled: "Diese Zeit wurde bereits bearbeitet.",
  idleAssignedBody: (recorded: string, pause: string) => `${recorded} gebucht, ${pause} als Pause ausgelassen.`,
  idleTime: "Inaktive Zeit",
  idleDetectedRunning: "Inaktivität erkannt · Timer läuft weiter.",
  idleDetectedPaused: "Inaktivität erkannt · Timer pausiert.",
  idleWaiting: "Inaktive Zeit wartet auf Zuordnung.",
  imBack: "Ich bin wieder da",
  assignTime: "Zeit zuordnen",
  welcomeBack: "Willkommen zurück",
  idleDialogDescription: "Der Timer ist pausiert. Ordnen Sie die Zeit zu und entscheiden Sie anschließend, ob er weiterlaufen soll.",
  takeAsPause: "Als Pause übernehmen",
  bookTime: "Zeit buchen",
  bookTimeAndStop: "Zeit buchen und Timer stoppen",
  later: "Später",
  inactiveFor: "Sie waren inaktiv für",
  idlePeriods: (count: number) => `${String(count)} Inaktivitätsphasen · aktive Zeit dazwischen bleibt erhalten`,
  returnDetecting: "Rückkehr wird erkannt …",
  whatDidYouDo: "Was haben Sie in dieser Zeit gemacht?",
  modePause: "Pause",
  modeWorked: "Gearbeitet",
  modeSplit: "Aufteilen",
  notBooked: "Diese Zeit wird nicht gebucht.",
  section: (number: number) => `Abschnitt ${String(number)}`,
  taskOrPause: "Todo oder Pause",
  task: "Todo",
  duration: "Dauer",
  durationPlaceholder: "Minuten oder h:mm:ss",
  takeRest: "Rest übernehmen",
  removeSection: (number: number) => `Abschnitt ${String(number)} entfernen`,
  editNote: "Leistung bearbeiten",
  addNote: "Leistung hinzufügen",
  noteOptional: "Leistung (optional)",
  pauseNotBooked: "Pause — nicht buchen",
  addSection: "Abschnitt hinzufügen",
  allDistributed: "Alles verteilt",
  left: (time: string) => `${time} übrig`,
  tooMuch: (time: string) => `${time} zu viel`,
  timerKeepsRunning: "Der Timer läuft weiter.",
  timerResumesAfter: "Der Timer läuft nach der Zuordnung weiter.",
  timerStopped: "Der Timer ist gestoppt.",
  searchTask: "Todo suchen …",
  showTasks: "Todos anzeigen",
  searching: "Suche …",
  noTasksFound: "Keine Todos gefunden.",
  searchFailed: "Suche fehlgeschlagen.",
  moreTasks: "Weitere Todos: Suche nach Titel oder Call-Nummer eingrenzen.",
  // stopMessage
  booked: (duration: string) => `Gebucht: ${duration}.`,
  timeBookedOn: (title: string) => `Zeit gebucht auf ${title}`,
  withSituation: (on: string, situation: string) => `${on} — ${situation}.`,
  butSituation: (on: string, situation: string) => `${on} — aber ${situation}.`,
  previewFailedTail: "Die erfasste Zeit steht fest; der gerundete Wert steht in der Export-Ansicht.",
  openThatDay: (open: string, quarters: string) => `An diesem Tag sind für dieses Todo ${open} offen — das ergibt beim Export ${quarters}.`,
  // TimerBar and Timer
  timerLoading: "Timer wird geladen …",
  noTimerRunning: "Kein Timer läuft.",
  recordTime: "Zeit erfassen",
  since: (time: string) => `seit ${time} Uhr`,
  timerRunsOn: "Timer läuft auf: ",
  stopTimer: "Timer stoppen",
  startTimer: "Timer starten",
  stopTimerFor: (title: string) => `Timer für ${title} stoppen`,
  startTimerFor: (title: string) => `Timer für ${title} starten`,
  runningTime: (display: string) => `Laufende Zeit ${display}`,
  recordedTime: (display: string) => `Erfasste Zeit ${display}`,
  stop: "Stoppen",
  start: "Starten",
  // TimerContext
  checkFailed: "Timer konnte nicht geprüft werden",
  nothingBooked: "Nichts gebucht.",
  underOneSecond: (title: string) => `Der Timer auf ${title} lief weniger als eine Sekunde. Das ist ein Doppelklick auf „Start“, keine geleistete Arbeit.`,
  stopFailed: "Der Timer ließ sich nicht stoppen",
  switchStartFailed: (title: string) => `Gebucht, aber der Timer auf ${title} ließ sich nicht starten`,
  switchStartFailedBody: (detail: string) => `Die Zeit des vorigen Timers ist gebucht — daran ändert das nichts. ${detail}`,
  stillRunning: "Es läuft weiterhin ein Timer. Bitte starten Sie erneut.",
  startFailed: "Der Timer ließ sich nicht starten",
  orphanBooked: (title: string) => `Buchung auf ${title} abgeschlossen.`,
  orphanBookedBody: (duration: string) => `Gebucht bis zum letzten Lebenszeichen: ${duration}.`,
  orphanDiscarded: "Buchung verworfen.",
  orphanDiscardedBody: (title: string) => `Sie haben die unvollständige Buchung auf ${title} verworfen. Es ist keine Zeit gebucht worden.`,
  orphanNothing: "Nichts zu buchen.",
  orphanNothingBody: (title: string) => `Zwischen dem Start und dem letzten Lebenszeichen liegt auf ${title} weniger als eine Sekunde. Die unvollständige Buchung ist damit weg, gebucht wurde nichts.`,
  idleCheckFailed: "Inaktivität konnte nicht geprüft werden: ",
  checkAgain: "Erneut prüfen",
  stopTitle: "Timer stoppen",
  // Stop after more than 24 hours (A-28.6, welle-18-fluss.md 4.2)
  longStopLead: "Eine Buchung dauert höchstens 24 Stunden. Wann endete die Arbeit?",
  longStopEnd: "Ende",
  longStopEndFor: (title: string) => `Ende für ${title}`,
  longStopHint: (start: string) => `Anfang: ${start}. Die Zeit nach dem Ende wird nicht gebucht.`,
  longStopReadout: (duration: string) => `Gebucht werden: ${duration}`,
  runningFor: (elapsed: string, title: string) => `Läuft seit ${elapsed} auf ${title}.`,
  stopAndBook: "Stoppen und buchen",
  keepRunning: "Weiterlaufen lassen",
  notePlaceholder: "Was wurde geleistet?",
  alreadyRunning: "Es läuft bereits ein Timer",
  switchLead: (running: string, next: string) => `Auf ${running} läuft ein Timer. Er wird gestoppt und die Zeit gebucht, dann startet der Timer auf ${next}.`,
  stopAndSwitch: "Stoppen und wechseln",
  note: "Leistung",
  noteFor: (title: string) => `Leistung für ${title}`,
  orphanTitle: "Eine Buchung ohne Ende",
  orphanLead: (title: string) => `Beim letzten Mal wurde SuperTakt nicht ordentlich beendet. Auf ${title} lief ein Timer, der nie gestoppt wurde.`,
  decide: "Entscheiden",
  decideLater: "Später entscheiden",
  whatShouldHappen: "Was soll damit geschehen?",
  bookUntilHeartbeat: "Bis zum letzten Lebenszeichen buchen",
  bookUntilHeartbeatHint: (duration: string) => `Das ergibt ${duration}. Gibt es kein Lebenszeichen, gibt es nichts zu buchen — dann wird verworfen.`,
  discard: "Verwerfen",
  discardHint: "Es wird keine Zeit gebucht.",
  noBookUntilNow: "„Bis jetzt buchen“ gibt es bewusst nicht. Genau das wäre der Weg, auf dem ein über Nacht vergessener Timer vierzehn Stunden in eine Rechnung bringt.",
  // TimeScreen
  timeTracking: "Zeiterfassung",
  timeTrackingLoading: "Zeiterfassung wird geladen",
  timer: "Timer",
  atMostOne: "Es läuft höchstens einer.",
  idleHint: "Kein Timer läuft. Wählen Sie unten ein Todo — oder starten Sie den Timer direkt aus der Todo-Liste, dem Kanban-Board oder dem Dashboard.",
  stopHint: "Beim Stoppen fragt SuperTakt nach der Leistung. Sie geht in die Abrechnung — im Unterschied zum Vermerk, der in SuperTakt bleibt.",
  pickTodo: "Todo wählen",
  pickTodoLead: "Startet der Timer auf einem erledigten Todo, ist es danach wieder offen.",
  searchTodos: "Todos durchsuchen",
  searchPlaceholder: "Titel oder Call-Nummer …",
  showDone: "Erledigte einblenden",
  hiddenByDefault: "Voreingestellt ausgeblendet",
  hiddenDoneOne: "erledigtes Todo ist",
  hiddenDoneMany: "erledigte Todos sind",
  hiddenDone: (count: string) => `${count} ausgeblendet.`,
  show: "Einblenden",
  noTodoYet: "Noch kein Todo",
  noOpenTodo: "Kein offenes Todo",
  noMatch: "Kein Treffer",
  createTodoFirst: "Legen Sie zuerst ein Todo an — Zeit wird immer auf ein Todo gebucht.",
  allDone: "Alle Todos sind erledigt.",
  noTodoMatches: "Kein Todo passt zu dieser Eingabe.",
  noOpenTodoMatches: "Kein offenes Todo passt zu dieser Eingabe. Erledigte sind ausgeblendet.",
  call: "Call",
  manual: "Von Hand",
  today: "Heute",
  recorded: "Erfasst",
  booking: "Buchung",
  bookings: "Buchungen",
  stillOpen: "Noch offen",
  exportUnavailable: "Was der Export daraus macht, ist gerade nicht abrufbar.",
  notExportedYet: "Noch nicht exportiert.",
  yieldsAtExport: (quarters: string) => `Ergibt beim Export ${quarters}.`,
  // Split around the service message so it can carry `lang="de"` (E-138 point 4).
  previewProblemLead: "Was der Export aus den offenen Buchungen macht, ließ sich nicht abrufen: ",
  previewProblemTail: " Die erfasste Zeit stimmt trotzdem — nur der gerundete Wert fehlt, und geraten wird er nicht.",
  groupHas: "Tagesgruppe hat",
  groupsHave: "Tagesgruppen haben",
  blockedGroups: (groups: string, one: boolean) => `${groups} noch keinen Leistungstext und ${one ? "geht" : "gehen"} so nicht in den Export. Die Export-Ansicht zeigt, welche.`,
  todayBookings: "Buchungen von heute",
  nothingToday: "Heute noch nichts erfasst",
  nothingTodayBody: "Der erste Timerstart legt die erste Buchung an.",
  withoutNote: "Ohne Leistung",
  // useReactivation
  undoStepFailed: {
    stop: "Der Timer ließ sich nicht anhalten. „Erledigt“ bleibt aufgehoben.",
    discard: "Der Timer ist angehalten, aber die eben entstandene Buchung ließ sich nicht verwerfen. Sie steht in den Buchungen, „Erledigt“ bleibt aufgehoben.",
    markDone: "Der Timer ist angehalten und die Buchung verworfen, aber „Erledigt“ ließ sich nicht wieder setzen.",
  },
  undone: "Zurückgenommen.",
  doneAgain: (title: string) => `${title} ist wieder erledigt, die eben entstandene Buchung wurde verworfen.`,
  timerStarted: "Timer gestartet.",
  runsOn: (title: string) => `Er läuft auf ${title}.`,
  undo: "Rückgängig",
};

const en: typeof de = {
  pickTaskForTime: "Choose the todo the time should be booked on.",
  distributeAll: "Distribute the whole time. Enter minutes or a duration as hours:minutes:seconds.",
  idleAssigned: "Inactive time assigned.",
  idleAlreadyHandled: "This time was already handled.",
  idleAssignedBody: (recorded: string, pause: string) => `${recorded} booked, ${pause} left out as a break.`,
  idleTime: "Inactive time",
  idleDetectedRunning: "Inactivity detected · timer keeps running.",
  idleDetectedPaused: "Inactivity detected · timer paused.",
  idleWaiting: "Inactive time waits to be assigned.",
  imBack: "I am back",
  assignTime: "Assign time",
  welcomeBack: "Welcome back",
  idleDialogDescription: "The timer is paused. Assign the time, then decide whether it should continue running.",
  takeAsPause: "Take as break",
  bookTime: "Book time",
  bookTimeAndStop: "Book time and stop timer",
  later: "Later",
  inactiveFor: "You were inactive for",
  idlePeriods: (count: number) => `${String(count)} inactivity periods · active time in between is kept`,
  returnDetecting: "Detecting return …",
  whatDidYouDo: "What did you do during this time?",
  modePause: "Break",
  modeWorked: "Worked",
  modeSplit: "Split",
  notBooked: "This time is not booked.",
  section: (number: number) => `Part ${String(number)}`,
  taskOrPause: "Todo or break",
  task: "Todo",
  duration: "Duration",
  durationPlaceholder: "Minutes or h:mm:ss",
  takeRest: "Take the rest",
  removeSection: (number: number) => `Remove part ${String(number)}`,
  editNote: "Edit work done",
  addNote: "Add work done",
  noteOptional: "Work done (optional)",
  pauseNotBooked: "Break — do not book",
  addSection: "Add part",
  allDistributed: "All distributed",
  left: (time: string) => `${time} left`,
  tooMuch: (time: string) => `${time} too much`,
  timerKeepsRunning: "The timer keeps running.",
  timerResumesAfter: "The timer resumes after the assignment.",
  timerStopped: "The timer is stopped.",
  searchTask: "Search todo …",
  showTasks: "Show todos",
  searching: "Searching …",
  noTasksFound: "No todos found.",
  searchFailed: "Search failed.",
  moreTasks: "More todos: narrow the search by title or call number.",
  booked: (duration: string) => `Booked: ${duration}.`,
  timeBookedOn: (title: string) => `Time booked on ${title}`,
  withSituation: (on: string, situation: string) => `${on} — ${situation}.`,
  butSituation: (on: string, situation: string) => `${on} — but ${situation}.`,
  previewFailedTail: "The recorded time is fixed; the rounded value is shown in the export view.",
  openThatDay: (open: string, quarters: string) => `${open} are open on this todo for this day — that yields ${quarters} at export.`,
  timerLoading: "Loading timer …",
  noTimerRunning: "No timer running.",
  recordTime: "Record time",
  since: (time: string) => `since ${time}`,
  timerRunsOn: "Timer running on: ",
  stopTimer: "Stop timer",
  startTimer: "Start timer",
  stopTimerFor: (title: string) => `Stop timer for ${title}`,
  startTimerFor: (title: string) => `Start timer for ${title}`,
  runningTime: (display: string) => `Running time ${display}`,
  recordedTime: (display: string) => `Recorded time ${display}`,
  stop: "Stop",
  start: "Start",
  checkFailed: "The timer could not be checked",
  nothingBooked: "Nothing booked.",
  underOneSecond: (title: string) => `The timer on ${title} ran for less than a second. That is a double click on “Start”, not work done.`,
  stopFailed: "The timer could not be stopped",
  switchStartFailed: (title: string) => `Booked, but the timer on ${title} could not be started`,
  switchStartFailedBody: (detail: string) => `The time of the previous timer is booked — this does not change that. ${detail}`,
  stillRunning: "A timer is still running. Please start again.",
  startFailed: "The timer could not be started",
  orphanBooked: (title: string) => `Booking on ${title} completed.`,
  orphanBookedBody: (duration: string) => `Booked up to the last sign of life: ${duration}.`,
  orphanDiscarded: "Booking discarded.",
  orphanDiscardedBody: (title: string) => `You discarded the incomplete booking on ${title}. No time was booked.`,
  orphanNothing: "Nothing to book.",
  orphanNothingBody: (title: string) => `Between the start and the last sign of life on ${title} there is less than a second. The incomplete booking is gone, nothing was booked.`,
  idleCheckFailed: "Inactivity could not be checked: ",
  checkAgain: "Check again",
  stopTitle: "Stop timer",
  longStopLead: "A booking lasts at most 24 hours. When did the work end?",
  longStopEnd: "End",
  longStopEndFor: (title: string) => `End for ${title}`,
  longStopHint: (start: string) => `Start: ${start}. Time after the end is not booked.`,
  longStopReadout: (duration: string) => `To be booked: ${duration}`,
  runningFor: (elapsed: string, title: string) => `Running for ${elapsed} on ${title}.`,
  stopAndBook: "Stop and book",
  keepRunning: "Keep running",
  notePlaceholder: "What was done?",
  alreadyRunning: "A timer is already running",
  switchLead: (running: string, next: string) => `A timer is running on ${running}. It is stopped and the time booked, then the timer starts on ${next}.`,
  stopAndSwitch: "Stop and switch",
  note: "Work done",
  noteFor: (title: string) => `Work done for ${title}`,
  orphanTitle: "A booking without an end",
  orphanLead: (title: string) => `Last time SuperTakt was not shut down properly. A timer on ${title} was never stopped.`,
  decide: "Decide",
  decideLater: "Decide later",
  whatShouldHappen: "What should happen with it?",
  bookUntilHeartbeat: "Book up to the last sign of life",
  bookUntilHeartbeatHint: (duration: string) => `That makes ${duration}. Without a sign of life there is nothing to book — it is then discarded.`,
  discard: "Discard",
  discardHint: "No time is booked.",
  noBookUntilNow: "“Book until now” deliberately does not exist. That would be exactly the way an overnight forgotten timer brings fourteen hours into an invoice.",
  timeTracking: "Time tracking",
  timeTrackingLoading: "Loading time tracking",
  timer: "Timer",
  atMostOne: "At most one runs at a time.",
  idleHint: "No timer running. Choose a todo below — or start the timer directly from the todo list, the Kanban board or the dashboard.",
  stopHint: "When stopping, SuperTakt asks for the work done. It goes into billing — unlike the internal note, which stays in SuperTakt.",
  pickTodo: "Choose todo",
  pickTodoLead: "If the timer starts on a done todo, it is open again afterwards.",
  searchTodos: "Search todos",
  searchPlaceholder: "Title or call number …",
  showDone: "Show done",
  hiddenByDefault: "Hidden by default",
  hiddenDoneOne: "done todo is",
  hiddenDoneMany: "done todos are",
  hiddenDone: (count: string) => `${count} hidden.`,
  show: "Show",
  noTodoYet: "No todo yet",
  noOpenTodo: "No open todo",
  noMatch: "No match",
  createTodoFirst: "Create a todo first — time is always booked on a todo.",
  allDone: "All todos are done.",
  noTodoMatches: "No todo matches this input.",
  noOpenTodoMatches: "No open todo matches this input. Done ones are hidden.",
  call: "Call",
  manual: "By hand",
  today: "Today",
  recorded: "Recorded",
  booking: "booking",
  bookings: "bookings",
  stillOpen: "Still open",
  exportUnavailable: "What the export makes of it cannot be retrieved right now.",
  notExportedYet: "Not exported yet.",
  yieldsAtExport: (quarters: string) => `Yields ${quarters} at export.`,
  previewProblemLead: "What the export makes of the open bookings could not be retrieved: ",
  previewProblemTail: " The recorded time is still correct — only the rounded value is missing, and it is not guessed.",
  groupHas: "day group has",
  groupsHave: "day groups have",
  blockedGroups: (groups: string, one: boolean) => `${groups} no work text yet and so ${one ? "does" : "do"} not go into the export. The export view shows which.`,
  todayBookings: "Today's bookings",
  nothingToday: "Nothing recorded today",
  nothingTodayBody: "The first timer start creates the first booking.",
  withoutNote: "No work done",
  undoStepFailed: {
    stop: "The timer could not be stopped. “Done” stays lifted.",
    discard: "The timer is stopped, but the booking just created could not be discarded. It is in the bookings, “Done” stays lifted.",
    markDone: "The timer is stopped and the booking discarded, but “Done” could not be set again.",
  },
  undone: "Undone.",
  doneAgain: (title: string) => `${title} is done again; the booking just created was discarded.`,
  timerStarted: "Timer started.",
  runsOn: (title: string) => `It runs on ${title}.`,
  undo: "Undo",
};

export function timerTexts(): typeof de {
  return pickTexts({ de, en });
}
