import { pickTexts } from "../../lib/language";

/** UI texts of the bookings feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // BookingFormDialog
  bookingChanged: "Buchung geändert",
  groupChangesToo: "Die Tagesgruppe dieses Todos ändert sich mit.",
  startMissing: "Anfang fehlt.",
  endMissing: "Ende fehlt.",
  manualTitle: "Zeit von Hand erfassen",
  editTitle: "Buchung bearbeiten",
  manualLead: (title: string) => `Für ${title}. Die Dauer ergibt sich aus Anfang und Ende; SuperTakt rechnet sie aus.`,
  editLead: (title: string) => `Für ${title}. Der gerundete Exportwert hängt an der Tagesgruppe, nicht an dieser Buchung.`,
  book: "Buchen",
  save: "Speichern",
  start: "Anfang",
  end: "Ende",
  notePlaceholder: "Was wurde geleistet?",

  // ResetExportDialog
  resetNothingOpen: (duration: string) =>
    `An diesem Tag ist auf diesem Todo derzeit nichts offen. Diese Buchung mit ${duration} bildet danach die Tagesgruppe.`,
  // Lead texts end where the service message begins; it carries `lang="de"` (E-138 point 4).
  resetPreviewFailedLead: (open: string, duration: string) =>
    `An diesem Tag sind auf diesem Todo bereits ${open} offen. Diese Buchung mit ${duration} kommt hinzu. Was die Tagesgruppe danach gerundet ergibt, ließ sich gerade nicht abfragen: `,
  openAmount: (open: string) => `${open} offen`,
  openAmountWithExport: (open: string, quarters: string) => `${open} offen, das ergibt beim Export ${quarters}`,
  resetAdds: (current: string, duration: string) =>
    `An diesem Tag sind auf diesem Todo bereits ${current}. Diese Buchung mit ${duration} kommt hinzu und verändert den gerundeten Wert der Tagesgruppe.`,
  resetContextFailedLead: "Was an diesem Tag auf diesem Todo bereits offen ist, ließ sich nicht abfragen: ",
  resetContextFailedTail: " Dieselbe Arbeitszeit geht mit dem Zurücksetzen trotzdem beim nächsten Export erneut in die Abrechnung.",
  resetDone: "Exportstatus zurückgesetzt.",
  resetDoneBody: "Die Buchung ist wieder offen und geht beim nächsten Export erneut in die Abrechnung. Der Vorgang steht mit Ihrer Begründung im Protokoll.",
  resetFailed: "Der Exportstatus ließ sich nicht zurücksetzen",
  resetTitle: "Exportstatus zurücksetzen?",
  resetLead: (day: string, title: string, duration: string) =>
    `Die Buchung vom ${day} auf ${title} (${duration}) wird wieder als offen geführt.`,
  resetConsequence: "Dieselbe Arbeitszeit geht damit beim nächsten Export erneut in die Abrechnung.",
  reset: "Zurücksetzen",
  reasonForLog: "Begründung für das Protokoll",
  resetAcknowledge: "Mir ist klar, dass diese Zeit dadurch ein zweites Mal abgerechnet werden kann.",

  // NotBilledDialog
  notBilledDone: "Diese Zeit wird nicht abgerechnet.",
  notBilledDoneBody: "Die Buchung ist abgeschlossen und geht in keinen Export mehr ein. Der Vorgang steht im Protokoll.",
  notBilledFailed: "Die Buchung ließ sich nicht ausbuchen",
  notBilledNoExport: "Dieses Todo ist von der Abrechnung ausgeschlossen. Seine Buchungen gehen ohnehin in keinen Export und lassen sich deshalb nicht ausbuchen.",
  notBilledTitle: "Diese Zeit nicht abrechnen?",
  notBilledLead: (day: string, title: string, duration: string) =>
    `Die Buchung vom ${day} auf ${title} (${duration}) wird als abgeschlossen geführt.`,
  notBilledConsequence: "Sie geht in keinen Export mehr ein. Exportiert wird sie nicht — Sie rechnen diese Zeit einfach nicht ab. Rückgängig machen lässt sich das über „Exportstatus zurücksetzen“.",
  notBilled: "Nicht abrechnen",
  reasonOptional: "Grund (freiwillig)",

  // BookingHistoryDialog
  historyTitle: "Verlauf dieser Buchung",
  on: "auf",
  fullLog: "Gesamtes Protokoll",
  today: "Heute",
  inNoRun: "In keinem Exportlauf gewesen.",
  runContained: "Exportlauf hat diese Zeit enthalten",
  runsContained: "Exportläufe haben diese Zeit enthalten",
  historyLoading: "Der Verlauf dieser Buchung wird geladen",
  historyFailed: "Der Verlauf ließ sich nicht laden",
  historyFailedTail: "Der Exportstatus der Buchung ist davon unberührt.",
  historyEmptyTitle: "Für diese Buchung ist nichts protokolliert",
  historyEmptyBody: "Das Protokoll hält ausschließlich Wechsel des Exportstatus fest: exportiert, zurückgesetzt, nicht abgerechnet. Eine geänderte Zeit oder ein nachgetragener Leistungstext steht nicht darin.",
  event: "Vorgang",
  events: "Vorgänge",
  historyLeadTail: ", der jüngste zuerst. Das Protokoll ist anhängend: Es gibt keinen Weg, eine dieser Zeilen zu ändern oder zu löschen.",

  // InfoDialog
  close: "Schließen",

  // bookingRows
  unknownTodo: "Unbekanntes Todo",

  // BookingsScreen
  exportStatus: "Exportstatus",
  open: "Offen",
  exported: "Exportiert",
  narrowing: "Einengung",
  exportedBefore: "schon einmal exportiert",
  from: "Ab",
  to: "Bis",
  todo: "Todo",
  restricted: "eingeschränkt",
  search: "Suche",
  bookingIs: "Buchung ist",
  bookingsAre: "Buchungen sind",
  reopened: (count: string) => `${count} wieder offen.`,
  bulkResetBody: "Dieselbe Arbeitszeit geht beim nächsten Export erneut in die Abrechnung. Jeder Vorgang steht mit Ihrer Begründung im Protokoll.",
  bulkPartialTitle: "Nicht alles ließ sich zurücksetzen",
  bulkPartial: (done: number, total: number) => `${String(done)} von ${String(total)} Buchungen sind wieder offen. Der Rest blieb unverändert.`,
  bulkStoppedAt: (failure: string) => ` Abgebrochen wurde bei: ${failure}`,
  lockedNotBilled: "Diese Zeit wurde ausgebucht und ist gesperrt. Setzen Sie den Exportstatus zurück, um sie wieder zu bearbeiten.",
  lockedExported: "Diese Buchung wurde bereits exportiert und ist gesperrt. Setzen Sie den Exportstatus zurück, um sie zu bearbeiten.",
  openTodo: "Todo öffnen",
  edit: "Bearbeiten",
  resetExportStatus: "Exportstatus zurücksetzen",
  alreadyOpen: "Diese Buchung ist bereits offen.",
  alreadyNotBilled: "Diese Zeit ist bereits ausgebucht.",
  alreadyExported: "Diese Buchung ist bereits exportiert und damit abgeschlossen.",
  screenTitle: "Buchungen",
  lead: "Zeitbuchungen prüfen, bearbeiten und nach Exportstatus filtern.",
  filterLabel: "Buchungen filtern",
  booking: "Buchung",
  bookings: "Buchungen",
  loadingShort: "wird geladen …",
  all: "Alle",
  onlyExportedBefore: "Nur schon einmal exportierte",
  onlyExportedBeforeHint: "Einengung innerhalb des Status, kein eigener Statuswert",
  fromDay: "Ab Tag",
  toDay: "Bis Tag",
  lastSevenDays: "Letzte 7 Tage",
  restrictTodo: "Todo einschränken",
  searchTodo: "Todo suchen …",
  pickTodo: "Todo für den Filter wählen",
  loading: "Buchungen werden geladen",
  noBookingTitle: "Noch keine Zeitbuchung",
  noMatchTitle: "Keine Buchung passt zu diesen Filtern",
  noBookingBody: "Starten Sie den Timer auf einem Todo — die erste Buchung entsteht beim Stoppen.",
  noMatchBody: "Setzen Sie einen Filter zurück oder erweitern Sie den Zeitraum.",
  toTimeTracking: "Zur Zeiterfassung",
  resetFilters: "Filter zurücksetzen",
  selectHint: "Zeilen auswählen, um mehrere Buchungen auf einmal zu bearbeiten.",
  bookingSelected: "Buchung ausgewählt",
  bookingsSelected: "Buchungen ausgewählt",
  resetSelected: (count: number) => `Exportstatus zurücksetzen (${String(count)})`,
  clearSelection: "Auswahl aufheben",
  caption: "Alle Zeitbuchungen mit Exportstatus, Zeitraum, Dauer und Leistung",
  rowActions: (title: string) => `Aktionen für die Buchung ${title}`,
  thisTodo: "diesem Todo",
  bulkTitle: "Exportstatus mehrerer Buchungen zurücksetzen?",
  bulkLead: "Alle ausgewählten Buchungen, die exportiert sind, werden wieder als offen geführt.",
  bulkConsequence: "Dieselbe Arbeitszeit geht beim nächsten Export erneut in die Abrechnung. Jeder einzelne Vorgang wird mit dieser Begründung protokolliert.",
  bulkAcknowledge: "Mir ist klar, dass diese Zeiten dadurch ein zweites Mal abgerechnet werden können.",

  // BookingTable
  columnState: "Status",
  columnCall: "Call",
  columnPeriod: "Zeitraum",
  columnSource: "Herkunft",
  columnDuration: "Dauer",
  columnNote: "Leistung",
  columnActions: "Aktionen",
  writtenOffAt: (date: string) => `ausgebucht am ${date}`,
  exportedTimes: (count: number) => `${String(count)}× exportiert`,
  selectAll: "Alle sichtbaren Buchungen auswählen",
  selectRow: (title: string) => `Buchung ${title} auswählen`,
  noCall: "— ohne Call —",
  sourcePrefix: "Herkunft der Buchung: ",
  noNote: "— keine Leistung erfasst —",
};

const en: typeof de = {
  bookingChanged: "Booking changed",
  groupChangesToo: "This todo's day group changes with it.",
  startMissing: "Start is missing.",
  endMissing: "End is missing.",
  manualTitle: "Record time by hand",
  editTitle: "Edit booking",
  manualLead: (title: string) => `For ${title}. The duration follows from start and end; SuperTakt calculates it.`,
  editLead: (title: string) => `For ${title}. The rounded export value belongs to the day group, not to this booking.`,
  book: "Book",
  save: "Save",
  start: "Start",
  end: "End",
  notePlaceholder: "What was done?",

  resetNothingOpen: (duration: string) =>
    `Nothing is open on this todo for this day right now. This booking of ${duration} then forms the day group.`,
  resetPreviewFailedLead: (open: string, duration: string) =>
    `${open} are already open on this todo for this day. This booking of ${duration} is added. What the day group then yields rounded could not be retrieved just now: `,
  openAmount: (open: string) => `${open} open`,
  openAmountWithExport: (open: string, quarters: string) => `${open} open, which yields ${quarters} at export`,
  resetAdds: (current: string, duration: string) =>
    `Already on this todo for this day: ${current}. This booking of ${duration} is added and changes the rounded value of the day group.`,
  resetContextFailedLead: "What is already open on this todo for this day could not be retrieved: ",
  resetContextFailedTail: " The same working time still goes into billing again with the next export after the reset.",
  resetDone: "Export status reset.",
  resetDoneBody: "The booking is open again and goes into billing again with the next export. The action is logged with your reason.",
  resetFailed: "The export status could not be reset",
  resetTitle: "Reset export status?",
  resetLead: (day: string, title: string, duration: string) =>
    `The booking of ${day} on ${title} (${duration}) is marked as open again.`,
  resetConsequence: "The same working time then goes into billing again with the next export.",
  reset: "Reset",
  reasonForLog: "Reason for the log",
  resetAcknowledge: "I understand that this time may be billed a second time.",

  notBilledDone: "This time is not billed.",
  notBilledDoneBody: "The booking is closed and goes into no further export. The action is logged.",
  notBilledFailed: "The booking could not be written off",
  notBilledNoExport: "This todo is excluded from billing. Its bookings never go into an export and therefore cannot be written off.",
  notBilledTitle: "Do not bill this time?",
  notBilledLead: (day: string, title: string, duration: string) =>
    `The booking of ${day} on ${title} (${duration}) is marked as closed.`,
  notBilledConsequence: "It goes into no further export. It is not exported — you simply do not bill this time. “Reset export status” undoes this.",
  notBilled: "Do not bill",
  reasonOptional: "Reason (optional)",

  historyTitle: "History of this booking",
  on: "on",
  fullLog: "Full log",
  today: "Today",
  inNoRun: "Not in any export run.",
  runContained: "export run contained this time",
  runsContained: "export runs contained this time",
  historyLoading: "Loading the history of this booking",
  historyFailed: "The history could not be loaded",
  historyFailedTail: "The export status of the booking is not affected.",
  historyEmptyTitle: "Nothing is logged for this booking",
  historyEmptyBody: "The log records only changes of the export status: exported, reset, not billed. A changed time or a work text added later is not in it.",
  event: "action",
  events: "actions",
  historyLeadTail: ", newest first. The log is append-only: there is no way to change or delete any of these rows.",

  close: "Close",

  unknownTodo: "Unknown todo",

  exportStatus: "Export status",
  open: "Open",
  exported: "Exported",
  narrowing: "Narrowed",
  exportedBefore: "exported before",
  from: "From",
  to: "To",
  todo: "Todo",
  restricted: "restricted",
  search: "Search",
  bookingIs: "booking is",
  bookingsAre: "bookings are",
  reopened: (count: string) => `${count} open again.`,
  bulkResetBody: "The same working time goes into billing again with the next export. Each action is logged with your reason.",
  bulkPartialTitle: "Not everything could be reset",
  bulkPartial: (done: number, total: number) => `${String(done)} of ${String(total)} bookings are open again. The rest stayed unchanged.`,
  bulkStoppedAt: (failure: string) => ` Stopped at: ${failure}`,
  lockedNotBilled: "This time was written off and is locked. Reset the export status to edit it again.",
  lockedExported: "This booking was already exported and is locked. Reset the export status to edit it.",
  openTodo: "Open todo",
  edit: "Edit",
  resetExportStatus: "Reset export status",
  alreadyOpen: "This booking is already open.",
  alreadyNotBilled: "This time is already written off.",
  alreadyExported: "This booking is already exported and therefore closed.",
  screenTitle: "Bookings",
  lead: "Review and edit time bookings, filter by export status.",
  filterLabel: "Filter bookings",
  booking: "booking",
  bookings: "bookings",
  loadingShort: "loading …",
  all: "All",
  onlyExportedBefore: "Only exported before",
  onlyExportedBeforeHint: "Narrows within the status, not a status value of its own",
  fromDay: "From day",
  toDay: "To day",
  lastSevenDays: "Last 7 days",
  restrictTodo: "Restrict to todo",
  searchTodo: "Search todo …",
  pickTodo: "Choose todo for the filter",
  loading: "Loading bookings",
  noBookingTitle: "No time booking yet",
  noMatchTitle: "No booking matches these filters",
  noBookingBody: "Start the timer on a todo — the first booking is created when you stop it.",
  noMatchBody: "Reset a filter or widen the period.",
  toTimeTracking: "Go to time tracking",
  resetFilters: "Reset filters",
  selectHint: "Select rows to edit several bookings at once.",
  bookingSelected: "booking selected",
  bookingsSelected: "bookings selected",
  resetSelected: (count: number) => `Reset export status (${String(count)})`,
  clearSelection: "Clear selection",
  caption: "All time bookings with export status, period, duration and work done",
  rowActions: (title: string) => `Actions for booking ${title}`,
  thisTodo: "this todo",
  bulkTitle: "Reset export status of several bookings?",
  bulkLead: "All selected bookings that are exported are marked as open again.",
  bulkConsequence: "The same working time goes into billing again with the next export. Each single action is logged with this reason.",
  bulkAcknowledge: "I understand that these times may be billed a second time.",

  columnState: "Status",
  columnCall: "Call",
  columnPeriod: "Period",
  columnSource: "Source",
  columnDuration: "Duration",
  columnNote: "Work done",
  columnActions: "Actions",
  writtenOffAt: (date: string) => `written off ${date}`,
  exportedTimes: (count: number) => `exported ${String(count)}×`,
  selectAll: "Select all visible bookings",
  selectRow: (title: string) => `Select booking ${title}`,
  noCall: "— no call —",
  sourcePrefix: "Source of the booking: ",
  noNote: "— no work recorded —",
};

export function bookingTexts(): typeof de {
  return pickTexts({ de, en });
}
