import { pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // PoolFormDialog
  placementHint: {
    pool: "Die Regel steht im Pool-Bereich und in den Filtern. Auf dem Board erscheint sie nicht.",
    board: "Die Regel ist eine Spalte des Kanban-Boards. In der Pool-Liste und in den Filtern erscheint sie nicht.",
    both: "Dieselbe Regel an zwei Stellen: als Pool und als Spalte des Boards.",
  },
  newPool: "Neuen Pool anlegen",
  newColumn: "Neue Board-Spalte anlegen",
  editTitle: (name: string) => `${name} bearbeiten`,
  formLead: "Eine Regel nennt Bedingungen. Jede engt weiter ein: Erforderliche Tags müssen da sein, ausgeschlossene dürfen es nicht, und Status, Erledigt und Exportstatus grenzen weiter ab. Was auf „Alle“ steht, schränkt nicht ein.",
  create: "Anlegen",
  save: "Speichern",
  columnCreated: "Spalte angelegt.",
  poolCreated: "Pool angelegt.",
  ruleChanged: "Regel geändert.",
  savedEmptyFolder: (name: string, folders: string, column: boolean) =>
    `${name} trifft zurzeit nichts: In ${folders} liegt kein Tag. Legen Sie dort ein Tag an, dann füllt sich ${column ? "die Spalte" : "der Pool"} von selbst.`,
  savedNoCondition: (name: string) => `${name} nennt noch keine Bedingung und bleibt deshalb leer. Ergänzen Sie eine, dann füllt sie sich von selbst.`,
  condition: "Bedingung",
  conditions: "Bedingungen",
  savedSummary: (name: string, conditions: string, placement: string) => `${name} — ${conditions}, Anzeigeort: ${placement}.`,
  name: "Name",
  columnPlaceholder: "z. B. Wartet auf Rückmeldung",
  poolPlaceholder: "z. B. Kunden Nord",
  placement: "Anzeigeort",
  requiredTags: "Erforderliche Tags",
  requiredTagsLead: "Was ein Todo tragen muss, damit es dazugehört. Ein genannter Ordner steht für die Tags, die in ihm liegen.",
  requiredTagsPlaceholder: "Tag suchen und hinzufügen",
  requiredTagsHint: "Ein genanntes Tag trifft jedes Todo, das es trägt.",
  howMany: "Wie viele davon müssen zutreffen?",
  modeChangedTitle: "Diese Regel trifft danach andere Todos",
  modeChangedToAll: "Bisher genügte eines der genannten Tags. Mit „Alle davon“ muss ein Todo ab dem Speichern jeden davon tragen — die Regel trifft dann weniger.",
  modeChangedToAny: "Bisher mussten alle genannten Tags zutreffen. Mit „Mindestens eines davon“ genügt ab dem Speichern eines — die Regel trifft dann mehr.",
  requiredFolders: "Erforderliche Ordner",
  requiredFoldersHint: "Ein Ordner steht für alles, was in ihm liegt.",
  excludedTags: "Ausgeschlossene Tags",
  excludedTagsLead: "Was ein Todo nicht tragen darf. Keines davon — dafür gibt es keine Einstellung, „ausgeschlossen“ heißt immer „keines davon“.",
  excludedTagsPlaceholder: "Tag suchen und ausschließen",
  excludedTagsHint: "Trägt ein Todo eines dieser Tags, gehört es nicht dazu — auch wenn alles andere passt.",
  excludedFolders: "Ausgeschlossene Ordner",
  excludedFoldersHint: "Ein ausgeschlossener Ordner schließt jedes Tag darin aus.",
  folderDepth: "Ordnertiefe",
  folderDepthLead: "Eine Einstellung für beide Listen — erforderliche wie ausgeschlossene Ordner.",
  includeSubfolders: "Unterordner einschließen",
  includeSubfoldersHint: "Ein genannter Ordner steht dann auch für alles, was tiefer liegt — beliebig tief. Ohne Haken zählen nur die Tags unmittelbar im Ordner.",
  moreConditions: "Weitere Bedingungen",
  moreConditionsLead: "Drei Bedingungen, die keine Tags brauchen. Jede steht auf „Alle“, solange sie nicht einschränken soll.",
  statusNothing: (neutral: string, hint: string) => `Nichts gewählt heißt „${neutral}“ — ${hint}.`,
  statusChosen: "Status gewählt",
  statusChosenTail: (count: string) => `${count} — ein Todo genügt mit einem davon; es trägt immer genau einen.`,
  completion: "Erledigt",
  completionAny: "Erledigt entscheidet nicht über die Zugehörigkeit. Ob erledigte Karten zu sehen sind, sagt dann wie bisher der Schalter „Erledigte einblenden“.",
  completionDone: "Nur erledigte Todos. Diese Regel hat das letzte Wort — die Karten erscheinen auch dann, wenn erledigte sonst ausgeblendet sind. Hebt ein Timerstart das Kennzeichen auf, verlässt die Karte diese Spalte und steht wieder in ihrem Pool.",
  completionOpen: "Nur unerledigte Todos. Hebt ein Timerstart das Kennzeichen auf, kehrt das Todo ohne Zutun hierher zurück.",
  exportState: "Exportstatus",
  exportAny: "Der Exportstatus entscheidet nicht über die Zugehörigkeit.",
  exportOpen: "Todos mit mindestens einer abgeschlossenen, offenen Buchung — die Antwort auf „was habe ich noch nicht abgerechnet“.",
  exportExported: (notBilledHint: string) =>
    `Todos mit mindestens einer exportierten Buchung. Nicht „vollständig abgerechnet“: Ein Todo mit einer offenen und einer exportierten Buchung erfüllt beide Bedingungen und steht in beiden Spalten. ${notBilledHint}`,
  emptyFolderTitleOne: "Der geforderte Ordner enthält kein Tag",
  emptyFolderTitleMany: "Die geforderten Ordner enthalten kein Tag",
  emptyFolderBefore: (folders: string) => `In ${folders} liegt zurzeit kein Tag. Eine Bedingung, die auf keinen Tag zeigt, kann `,
  emptyFolderStrong: "kein Todo",
  emptyFolderAfter: (one: boolean) =>
    ` erfüllen — die Regel trifft damit nichts, auch wenn die übrigen Bedingungen stehen und auch dann, wenn daneben ein Tag oder ein gefüllter Ordner genannt ist. Legen Sie ein Tag in ${one ? "diesem Ordner" : "diesen Ordnern"} an oder nennen Sie hier einen anderen. Ausgeschlossene Ordner sind davon nicht betroffen: Was leer ist, schließt nichts aus.`,
  exclusionNoEffectTitle: "Ein Ausschluss bleibt ohne Wirkung",
  exclusionNoEffectBefore: "Mindestens einer der ausgeschlossenen Ordner enthält zurzeit kein Tag. „Keiner davon“ über nichts schließt nichts aus — dieser Teil der Regel lässt alles durch, und sie trifft genau dasselbe wie ohne ihn. Das ist ",
  exclusionNoEffectStrong: "kein Fehler",
  exclusionNoEffectAfter: ": Sobald ein Tag in dem Ordner liegt, greift der Ausschluss von selbst.",
  ruleMatches: "Diese Regel trifft",
  ruleMatchesLead: "So liest sie sich, sobald sie gespeichert ist.",
  noConditionPreview: (column: boolean) =>
    `Keine Bedingung — diese Regel trifft nichts. ${column ? "Die Spalte" : "Der Pool"} bleibt leer, bis eine Bedingung dazukommt.`,
  columnStaysEmpty: "Diese Spalte bleibt leer",
  poolStaysEmpty: "Dieser Pool bleibt leer",
  noConditionBefore: "Es ist noch keine Bedingung gewählt. Eine Regel ohne Bedingung trifft ",
  noConditionStrong: "nichts",
  noConditionAfter: " — nicht alles. Anlegen lässt sie sich trotzdem: Sie bleibt leer, bis Sie eine Bedingung ergänzen, und füllt sich dann von selbst.",
  // PoolRenameDialog
  unchangedHint: "Der Name ist unverändert. Ändern Sie ihn — oder schließen Sie den Dialog.",
  nameTaken: "Diesen Namen trägt bereits eine andere Regel. Zwei Regeln mit demselben Namen wären im Spaltenkopf und in der Pool-Auswahl nicht auseinanderzuhalten.",
  nameEmptyHint: "Ohne Namen geht es nicht: Er ist das, woran diese Regel auf dem Board und in den Pools erkennbar ist.",
  nameChangedHint: "Der neue Name erscheint sofort überall, wo diese Regel genannt wird.",
  nothingToSave: (unchangedHint: string) => `Es gibt nichts zu speichern. ${unchangedHint}`,
  nameRestored: "Name wiederhergestellt.",
  ruleRenamed: "Regel umbenannt.",
  renamedBody: (from: string, to: string) => `Aus ${from} wurde ${to}. Die Regel selbst ist unverändert; an den Todos ändert sich nichts.`,
  undo: "Rückgängig",
  restoreFailed: "Der alte Name ließ sich nicht wiederherstellen",
  renameTitle: (name: string) => `${name} umbenennen`,
  onlyNameChanges: "Es ändert sich nur der Name",
  onlyNameChangesBody: "Die Regel bleibt, wie sie ist: dieselben erforderlichen und ausgeschlossenen Tags, derselbe Status, dasselbe „Erledigt“ und derselbe Exportstatus. Welche Karten hier stehen, ändert sich dadurch nicht.",
  namesUnknownTitle: "Die vorhandenen Namen sind gerade nicht bekannt",
  namesUnknownBody: "Ob es diesen Namen schon gibt, lässt sich hier im Moment nicht sagen — die Liste der Regeln ist nicht geladen. Speichern geht trotzdem; ist der Name vergeben, weist der lokale Dienst ihn ab und der Grund steht danach hier.",
  surfacesBoard: (short: string) => `Anzeigeort: ${short}. Der Name steht im Kopf der Spalte; in den Pools erscheint diese Regel nicht.`,
  surfacesBoth: (short: string) => `Anzeigeort: ${short}. Der neue Name gilt für die Board-Spalte und für den Pool zugleich — es ist ein Name.`,
  surfacesPool: (short: string) => `Anzeigeort: ${short}. Der Name steht in der Pool-Liste und im Pool-Filter der Todo-Liste; auf dem Board erscheint diese Regel nicht.`,
  // RulePickers
  withoutListNothing: "Ohne die Liste lässt sich hier nichts wählen.",
  searchIn: (label: string) => `${label} durchsuchen`,
  folderSearchPlaceholder: "Ordner oder Pfad suchen …",
  foldersLoading: "Ordner werden geladen …",
  foldersFailed: "Die Ordner ließen sich nicht laden",
  noFolderYet: "Es gibt noch keinen Ordner.",
  noFolderMatches: (query: string) => `Kein Ordner passt zu „${query}“.`,
  moreFolderMatches: "Weiterer Ordner passt",
  moreFoldersMatch: "Weitere Ordner passen",
  typeMorePrecisely: (count: string) => `${count} ebenfalls. Tippen Sie genauer.`,
  status: "Status",
  statusesLoading: "Statuswerte werden geladen …",
  statusesFailed: "Die Statuswerte ließen sich nicht laden",
  noStatusYet: "Es gibt noch keinen Statuswert.",
  // RuleSummary
  noTagInside: " — kein Tag darin",
  withSubfolders: " mit Unterordnern",
  unreachable: (folders: string, one: boolean) =>
    `Kein Tag in ${folders} — ${one ? "diese Bedingung kann" : "diese Bedingungen können"} kein Todo erfüllen, und die Regel trifft damit nichts.`,
  neutralAxes: (axes: string) =>
    `Ohne Einschränkung: ${axes}. Diese Bedingungen lassen alles durch, was die übrigen übrig lassen — sie treffen nichts von sich aus.`,
};

const en: typeof de = {
  placementHint: {
    pool: "The rule is in the pool area and in the filters. It does not appear on the board.",
    board: "The rule is a column of the Kanban board. It does not appear in the pool list or the filters.",
    both: "The same rule in two places: as a pool and as a board column.",
  },
  newPool: "Create new pool",
  newColumn: "Create new board column",
  editTitle: (name: string) => `Edit ${name}`,
  formLead: "A rule names conditions. Each one narrows further: required tags must be there, excluded ones must not, and status, done and export status narrow further. Whatever is set to “All” does not restrict.",
  create: "Create",
  save: "Save",
  columnCreated: "Column created.",
  poolCreated: "Pool created.",
  ruleChanged: "Rule changed.",
  savedEmptyFolder: (name: string, folders: string, column: boolean) =>
    `${name} matches nothing right now: there is no tag in ${folders}. Create a tag there, and the ${column ? "column" : "pool"} fills by itself.`,
  savedNoCondition: (name: string) => `${name} names no condition yet and so stays empty. Add one, and it fills by itself.`,
  condition: "condition",
  conditions: "conditions",
  savedSummary: (name: string, conditions: string, placement: string) => `${name} — ${conditions}, placement: ${placement}.`,
  name: "Name",
  columnPlaceholder: "e.g. Waiting for reply",
  poolPlaceholder: "e.g. Customers North",
  placement: "Placement",
  requiredTags: "Required tags",
  requiredTagsLead: "What a todo must carry to belong. A named folder stands for the tags inside it.",
  requiredTagsPlaceholder: "Search and add tag",
  requiredTagsHint: "A named tag matches every todo that carries it.",
  howMany: "How many of them must apply?",
  modeChangedTitle: "This rule then matches other todos",
  modeChangedToAll: "So far one of the named tags was enough. With “Each of the named”, a todo must carry every one of them from saving on — the rule then matches fewer.",
  modeChangedToAny: "So far all named tags had to apply. With “At least one of them”, one is enough from saving on — the rule then matches more.",
  requiredFolders: "Required folders",
  requiredFoldersHint: "A folder stands for everything inside it.",
  excludedTags: "Excluded tags",
  excludedTagsLead: "What a todo must not carry. None of them — there is no setting for this, “excluded” always means “none of them”.",
  excludedTagsPlaceholder: "Search and exclude tag",
  excludedTagsHint: "If a todo carries one of these tags, it does not belong — even if everything else fits.",
  excludedFolders: "Excluded folders",
  excludedFoldersHint: "An excluded folder excludes every tag inside it.",
  folderDepth: "Folder depth",
  folderDepthLead: "One setting for both lists — required and excluded folders.",
  includeSubfolders: "Include subfolders",
  includeSubfoldersHint: "A named folder then also stands for everything deeper — at any depth. Unticked, only the tags directly in the folder count.",
  moreConditions: "More conditions",
  moreConditionsLead: "Three conditions that need no tags. Each stays on “All” as long as it should not restrict.",
  statusNothing: (neutral: string, hint: string) => `Nothing selected means “${neutral}” — ${hint}.`,
  statusChosen: "status selected",
  statusChosenTail: (count: string) => `${count} — one of them is enough for a todo; it always carries exactly one.`,
  completion: "Done",
  completionAny: "Done does not decide membership. Whether done cards are visible is then decided as before by the “Show done” switch.",
  completionDone: "Only done todos. This rule has the last word — the cards appear even when done ones are otherwise hidden. If a timer start lifts the flag, the card leaves this column and is back in its pool.",
  completionOpen: "Only todos not done. If a timer start lifts the flag, the todo comes back here by itself.",
  exportState: "Export status",
  exportAny: "The export status does not decide membership.",
  exportOpen: "Todos with at least one closed, open booking — the answer to “what have I not billed yet”.",
  exportExported: (notBilledHint: string) =>
    `Todos with at least one exported booking. Not “fully billed”: a todo with one open and one exported booking meets both conditions and is in both columns. ${notBilledHint}`,
  emptyFolderTitleOne: "The required folder contains no tag",
  emptyFolderTitleMany: "The required folders contain no tag",
  emptyFolderBefore: (folders: string) => `There is currently no tag in ${folders}. A condition that points to no tag can be met by `,
  emptyFolderStrong: "no todo",
  emptyFolderAfter: (one: boolean) =>
    ` — the rule then matches nothing, even if the other conditions are set and even if a tag or a filled folder is named next to it. Create a tag in ${one ? "this folder" : "these folders"} or name a different one here. Excluded folders are not affected: what is empty excludes nothing.`,
  exclusionNoEffectTitle: "An exclusion has no effect",
  exclusionNoEffectBefore: "At least one of the excluded folders contains no tag right now. “None of them” over nothing excludes nothing — this part of the rule lets everything through, and it matches exactly the same as without it. That is ",
  exclusionNoEffectStrong: "no error",
  exclusionNoEffectAfter: ": as soon as a tag is in the folder, the exclusion takes effect by itself.",
  ruleMatches: "This rule matches",
  ruleMatchesLead: "This is how it reads once saved.",
  noConditionPreview: (column: boolean) =>
    `No condition — this rule matches nothing. The ${column ? "column" : "pool"} stays empty until a condition is added.`,
  columnStaysEmpty: "This column stays empty",
  poolStaysEmpty: "This pool stays empty",
  noConditionBefore: "No condition is selected yet. A rule without a condition matches ",
  noConditionStrong: "nothing",
  noConditionAfter: " — not everything. It can still be created: it stays empty until you add a condition and then fills by itself.",
  unchangedHint: "The name is unchanged. Change it — or close the dialog.",
  nameTaken: "Another rule already carries this name. Two rules with the same name could not be told apart in the column header and the pool selection.",
  nameEmptyHint: "A name is required: it is how this rule is recognised on the board and in the pools.",
  nameChangedHint: "The new name appears at once everywhere this rule is named.",
  nothingToSave: (unchangedHint: string) => `There is nothing to save. ${unchangedHint}`,
  nameRestored: "Name restored.",
  ruleRenamed: "Rule renamed.",
  renamedBody: (from: string, to: string) => `${from} became ${to}. The rule itself is unchanged; nothing changes on the todos.`,
  undo: "Undo",
  restoreFailed: "The old name could not be restored",
  renameTitle: (name: string) => `Rename ${name}`,
  onlyNameChanges: "Only the name changes",
  onlyNameChangesBody: "The rule stays as it is: the same required and excluded tags, the same status, the same “Done” and the same export status. Which cards appear here does not change.",
  namesUnknownTitle: "The existing names are not known right now",
  namesUnknownBody: "Whether this name already exists cannot be said here right now — the list of rules is not loaded. Saving works anyway; if the name is taken, the local service rejects it and the reason appears here.",
  surfacesBoard: (short: string) => `Placement: ${short}. The name is in the column header; this rule does not appear in the pools.`,
  surfacesBoth: (short: string) => `Placement: ${short}. The new name applies to the board column and the pool at once — it is one name.`,
  surfacesPool: (short: string) => `Placement: ${short}. The name is in the pool list and in the todo list's pool filter; this rule does not appear on the board.`,
  withoutListNothing: "Without the list nothing can be chosen here.",
  searchIn: (label: string) => `Search ${label}`,
  folderSearchPlaceholder: "Search folder or path …",
  foldersLoading: "Loading folders …",
  foldersFailed: "The folders could not be loaded",
  noFolderYet: "There is no folder yet.",
  noFolderMatches: (query: string) => `No folder matches “${query}”.`,
  moreFolderMatches: "more folder matches",
  moreFoldersMatch: "more folders match",
  typeMorePrecisely: (count: string) => `${count} as well. Type more precisely.`,
  status: "Status",
  statusesLoading: "Loading status values …",
  statusesFailed: "The status values could not be loaded",
  noStatusYet: "There is no status value yet.",
  noTagInside: " — no tag inside",
  withSubfolders: " with subfolders",
  unreachable: (folders: string, one: boolean) =>
    `No tag in ${folders} — ${one ? "this condition" : "these conditions"} cannot be met by any todo, so the rule matches nothing.`,
  neutralAxes: (axes: string) =>
    `Without restriction: ${axes}. These conditions let through everything the others leave — they match nothing by themselves.`,
};

export function structureTexts(): typeof de {
  return pickTexts({ de, en });
}
