import { pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // Export audit (ExportAudit, exportAuditRows, ExportAuditScreen)
  eventPrefix: "Vorgang: ",
  transitionPrefix: "Statuswechsel: ",
  bookingGone: "Diese Buchung ist nicht mehr auffindbar. Die Protokollzeile bleibt trotzdem stehen — sie ist der Beleg, dass es sie gab.",
  call: "Call",
  noRun: "Kein Exportlauf — diese Zeit ist nie in eine Datei gegangen.",
  runNotLoaded: "Der zugehörige Exportlauf ließ sich nicht laden.",
  written: (when: string) => `geschrieben ${when}`,
  notBilledWithoutReason: "Ohne Begründung ausgebucht. Das Feld ist freiwillig — protokolliert ist trotzdem, dass hier jemand Zeit ohne Abrechnung abgehakt hat, und wann.",
  reason: "Begründung",
  actorPrefix: "Ausgelöst von: ",
  runUnreadable: "Lauf nicht mehr lesbar",
  unknownTodo: "Unbekanntes Todo",
  eventDescription: {
    exported: "In eine Exportdatei geschrieben. Die Datei steht daneben; die Buchung war danach gesperrt.",
    reset: "Der Exportstatus wurde zurückgesetzt. Diese Zeit geht beim nächsten Export erneut in die Abrechnung — genau dafür gibt es dieses Protokoll.",
    not_billed: "Von Hand ausgebucht: Diese Zeit wird nicht abgerechnet. Eine Exportdatei hat sie nie enthalten, deshalb steht hier kein Lauf.",
  },
  event: "Vorgang",
  run: "Lauf",
  runNotLoadedYet: "noch nicht geladen",
  auditTitle: "Exportprotokoll",
  auditLead: "Jeder Wechsel eines Exportstatus, mit Zeitpunkt, Buchung, Vorgang und Lauf. Anhängend und unveränderlich.",
  toExport: "Zur Export-Ansicht",
  auditFilter: "Protokoll filtern",
  eventLoaded: "Vorgang geladen",
  eventsLoaded: "Vorgänge geladen",
  eventsOfTotal: (loaded: string, total: string) => `${loaded} von ${total}`,
  eventSingular: "Vorgang",
  eventPlural: "Vorgänge",
  eventsOfLoaded: (visible: string, loaded: string) => `${visible} von ${loaded} geladenen`,
  loadingShort: "wird geladen …",
  allEvents: "Alle Vorgänge",
  exportRun: "Exportlauf",
  allRuns: "Alle Läufe",
  auditLegendNote: "Eine Zeile lässt sich weder ändern noch löschen — es gibt dafür keine Route, und die Speicherung verbietet beides zusätzlich. Wer eine Buchung zurücksetzt und erneut exportiert, findet beides hier nebeneinander.",
  auditLoading: "Das Exportprotokoll wird geladen",
  auditEmptyTitle: "Noch kein Vorgang protokolliert",
  auditEmptyBody: "Sobald der erste Export läuft, eine Buchung zurückgesetzt oder eine Zeit als „nicht abgerechnet“ abgehakt wird, steht es hier — mit Zeitpunkt, Buchung und Lauf.",
  auditNoMatchTitle: "Kein Vorgang passt zu diesen Filtern",
  auditNoMatchBody: "Der Filter wirkt über die geladenen Zeilen. Laden Sie weitere, wenn Sie einen älteren Vorgang suchen — oder setzen Sie den Filter zurück.",
  loadMore: "Weitere laden",
  resetFilters: "Filter zurücksetzen",
  countedOne: "Gezählt über den einen Vorgang.",
  countedAll: (total: string) => `Gezählt über alle ${total} Vorgänge.`,
  countedPartial: (loaded: string, total: string) => `Gezählt über ${loaded} von ${total} Vorgängen — ohne die noch nicht geladenen.`,
  tileExported: (scope: string) => `In eine Datei geschrieben. ${scope}`,
  tileReset: (scope: string) => `Danach geht dieselbe Zeit erneut in die Abrechnung. ${scope}`,
  tileNotBilled: (scope: string) => `Nie exportiert, bewusst nicht abgerechnet. ${scope}`,
  scopeFilter: "Die Kacheln zählen über alle geladenen Vorgänge und nicht über den gesetzten Filter.",
  scopeOlder: "Ältere Vorgänge sind noch nicht geladen. „Weitere laden“ am Ende der Liste erhöht beide Zahlen.",
  scopeFilterAndOlder: "Die Kacheln zählen über alle geladenen Vorgänge und nicht über den gesetzten Filter. Ältere sind zudem noch nicht geladen.",
  auditEnd: "Das ist der Anfang des Protokolls — ältere Vorgänge gibt es nicht.",
  loadMoreLeft: (left: string) => `Weitere laden (${left} übrig)`,
  // ExportRunList
  recentRuns: "Letzte Exportläufe",
  recentRunsLead: "Was wann geschrieben wurde.",
  openLog: "Protokoll öffnen",
  noExportTitle: "Noch kein Export",
  noExportBody: "Der erste Lauf schreibt die erste Datei.",
  booking: "Buchung",
  bookings: "Buchungen",
  runFilterHint: "Öffnet das Protokoll mit diesem Lauf als Filter. Der Filter wirkt über die geladenen Zeilen; bei älteren Läufen müssen dort weitere geladen werden.",
  runBookings: "Buchungen dieses Laufs",

  // ExportTabs
  tabExport: "Export",
  tabTemplates: "Vorlagen",
  tabLog: "Protokoll",
  tabsLabel: "Bereiche des Exports",

  // RunResult
  runDone: "Export abgeschlossen",
  runDoneLead: "In einer Transaktion geschrieben.",
  hide: "Ausblenden",
  file: "Datei",
  scope: "Umfang",
  exportRow: "Exportzeile",
  exportRows: "Exportzeilen",
  runScope: (bookings: string, rows: string, hours: string, bytes: string) => `${bookings} in ${rows} · ${hours} Stunden · ${bytes}`,
  checksum: "Prüfsumme",
  groupSkipped: "Tagesgruppe wurde",
  groupsSkipped: "Tagesgruppen wurden",
  skippedTitle: (groups: string) => `${groups} ausgelassen`,
  skippedBefore: "Ohne Leistungstext nimmt das Abrechnungstool eine Zeile nicht an. Der übrige Export ist durchgelaufen; diese Gruppen sind ",
  skippedStrong: "weiterhin offen",
  skippedAfter: " und erscheinen beim nächsten Mal wieder. Tragen Sie die Leistung nach, dann gehen sie mit.",
  addNote: "Leistung nachtragen",

  // GroupRowDetail and ExportRowPanes
  rowDeselected: "Diese Tagesgruppe ist abgewählt und erzeugt keine Zeile. Haken Sie sie an, dann steht hier, was geschrieben würde.",
  noTemplate: "Es ist keine Exportvorlage gewählt. Ohne sie gibt es keine Zeile, die sich zeigen ließe — und keinen Lauf.",
  templateUnreadable: "Diese Vorlage lässt sich nicht lesen",
  templateUnreadableTail: "Geprüft hat das dieselbe Stelle, die auch beim Speichern prüft. Solange das so ist, wird hier keine Zeile gezeigt — eine geratene wäre schlimmer als keine.",
  templateReading: "Die Vorlage wird gelesen",
  templateReadingDots: "Die Vorlage wird gelesen …",
  rowComputing: "Die Zeile wird gerechnet",
  rowComputingLong: "Die Zeile wird gerechnet — vom Dienst, mit demselben Renderer wie die Datei.",
  clearTextInGroup: "Der Klartext steht unten bei den Buchungen dieser Tagesgruppe.",
  clearTextBelow: "Der Klartext steht unten bei den Buchungen.",
  asInFile: "So steht es in der Datei",
  fieldByField: "Feld für Feld",
  base64Note: "Base64 ist eine Kodierung, keine Verschlüsselung.",
  missingKeys: (names: string) => `Nicht in dieser Zeile, weil die Bedingung nicht zutraf: ${names}. Der Schlüssel fehlt vollständig, er steht nicht leer da.`,
  // Export directory advice (locked sentences SP-14: all bodies)
  directoryAdvice: {
    not_absolute: {
      title: "Das ist kein vollständiger Pfad",
      body: "SuperTakt braucht den ganzen Weg zum Ordner — unter Windows mit Laufwerksbuchstaben, etwa C:\\Takt\\Export. Ein Pfad ohne Anfang zeigt je nach Arbeitsverzeichnis woandershin.",
    },
    drive_root: {
      title: "Das ist die Wurzel eines Laufwerks",
      body: "Dorthin schreibt SuperTakt nicht. Exportdateien in der Laufwerkswurzel sind für jedes Programm sichtbar, das das Laufwerk durchsucht, und lassen sich später von den Dateien des Systems nicht mehr auseinanderhalten. Legen Sie einen eigenen Unterordner an.",
    },
    system_directory: {
      title: "Das ist ein Verzeichnis des Betriebssystems",
      body: "Dorthin gehört nichts, was SuperTakt schreibt. Der Export enthält Kundendaten, die in einem Systemordner niemand vermutet und die dort bei der nächsten Aktualisierung oder Bereinigung ohne Vorwarnung verschwinden können. Wählen Sie einen Ordner unter Ihrem Benutzerprofil.",
    },
    network_share: {
      title: "Dieser Ordner liegt nicht auf diesem Rechner",
      body: "Die Exportdatei enthält lesbare Kundennotizen und verlässt damit diesen Rechner — bei einem Produkt, das laut E-001 vollständig lokal arbeitet. Und der Export schlägt fehl, sobald die Verbindung gerade nicht steht: Das Laufwerk ist getrennt, der Server nicht erreichbar, das Notebook nicht im Firmennetz. Wenn das Ihr Übergabeweg an die Abrechnung ist, ist es der richtige Ordner — dann wissen Sie jetzt, was darin liegt.",
    },
    sync_folder: {
      title: "Dieser Ordner wird in einen Onlinespeicher synchronisiert",
      body: "Alles, was SuperTakt hier ablegt, wird kurz darauf hochgeladen — automatisch, ohne weitere Rückfrage und ohne dass es jemand sieht. Die Exportdatei enthält lesbare Kundennotizen; Base64 ist eine Kodierung, keine Verschlüsselung. Damit liegen die Daten Ihrer Kunden bei einem Anbieter, und die Entscheidung dafür trifft man besser hier als später beim Aufräumen.",
    },
    roaming_profile: {
      title: "Dieser Ordner gehört zum servergespeicherten Profil",
      body: "Der Ordner AppData\\Roaming wird beim An- und Abmelden auf einen Dateiserver kopiert, wenn das Konto ein servergespeichertes Profil hat. Die Exportdateien mit ihren lesbaren Kundennotizen wandern dann mit. Genau deswegen liegen die Daten von SuperTakt unter AppData\\Local (E-018) — dort bleiben sie auf diesem Rechner.",
    },
    redirected_folder: {
      title: "Dieser Ordner ist auf verwalteten Rechnern häufig nach OneDrive umgeleitet",
      body: "Desktop, Dokumente und Bilder werden auf geschäftlichen Windows-Rechnern regelmäßig über „Bekannte Ordner verschieben“ in OneDrive gelegt. Von außen sieht der Pfad unverändert aus. Prüfen Sie im Explorer, ob der Ordner ein Wolkensymbol trägt — wenn ja, gehen die Exportdateien in den Onlinespeicher.",
    },
    volatile_folder: {
      title: "Der Downloads-Ordner wird von Aufräumwerkzeugen geleert",
      body: "Windows-Speicheroptimierung und die meisten Bereinigungswerkzeuge löschen hier ohne Rückfrage. Eine Exportdatei, die noch nicht in der Abrechnung angekommen ist, wäre dann weg — und die Buchungen darin sind bereits als exportiert markiert.",
    },
  },
  // ExportDirectoryField
  foundInPath: "Gefunden im Pfad",
  traits: {
    unc: {
      title: "Der Ordner ist eine Netzfreigabe",
      body: "Der Pfad ist in UNC-Schreibweise geschrieben. Der Export schreibt dann über das Netz: Ist die Freigabe weg, schlägt der Lauf fehl — vollständig, ohne halbe Datei (A-8.8).",
    },
    network: {
      title: "Der Ordner liegt auf einem Netzdateisystem",
      body: "Belegt über die Art des Dateisystems, nicht über den Namen. Dasselbe gilt wie bei einer Freigabe: Ohne Verbindung kein Lauf.",
    },
    sync_folder: {
      title: "Der Ordner gehört einem Synchronisierungsdienst",
      body: "Sein Client meldet ihn selbst so — auch wenn der Ordner umbenannt wurde. Die Exportdatei enthält lesbare Kundennotizen (A-8.9); hier verlässt sie diesen Rechner, sobald sie geschrieben ist.",
    },
    system_dir: {
      title: "Der Ordner ist ein Systemverzeichnis",
      body: "So benennt das Betriebssystem ihn selbst, unabhängig davon, auf welchem Laufwerk Windows liegt. Dorthin gehört nichts, was SuperTakt schreibt.",
    },
  },
  traitSource: "Belegt vom Betriebssystem, nicht aus dem Pfad gelesen.",
  nothingProven: "Am eingestellten Ordner ist nichts belegt worden. Das ist keine Entwarnung, sondern eine Nichtaussage: ",
  alsoChecked: "Geprüft wurde außerdem: ",
  mappedDriveBefore: "Ein ",
  mappedDriveStrong: "zugeordnetes Netzlaufwerk",
  mappedDriveMiddle: " wie ",
  mappedDriveAfter: " erkennt SuperTakt nicht — die Auskunft dazu bekommt der Dienst vom Betriebssystem nicht.",
  unreachableOpen: " Und weil dieser Ordner gerade nicht antwortet, konnte auch das Dateisystem nicht befragt werden; ob er im Netz liegt, ist damit offen.",
  base64Before: "Die Exportdatei enthält ",
  base64Strong: "lesbare Kundennotizen",
  base64After: ". Base64 ist eine Kodierung, keine Verschlüsselung — wer die Datei öffnen kann, kann sie lesen.",
  directoryState: {
    not_set: "Noch nicht gewählt. Ohne Exportordner ist kein Export möglich.",
    missing: "Dieser Ordner ist nicht erreichbar. SuperTakt legt ihn nicht von sich aus an.",
    not_writable: "Dieser Ordner ist da, aber SuperTakt darf nicht hineinschreiben.",
    not_a_directory: "Dieser Pfad zeigt auf eine Datei, nicht auf einen Ordner.",
    // T-039: not proven absent, just no answer; the sentence names the other step.
    unreachable: "Dieser Ordner hat nicht innerhalb von drei Sekunden geantwortet. Das ist kein Beleg dafür, dass es ihn nicht gibt — bei einem Netzlaufwerk fehlt meist nur die Verbindung.",
  },
  shellNoAnswer: "Die Anwendungshülle hat auf die Frage nach dem Ordnerauswahldialog nicht geantwortet.",
  folderChosen: (path: string) => `Ordner gewählt: ${path}. Zum Übernehmen speichern.`,
  pickCancelled: "Auswahl abgebrochen. Der bisher eingestellte Ordner bleibt.",
  exportFolder: "Exportordner",
  folderPlaceholder: "z. B. C:\\Takt\\Export",
  folderHintTyped: "Vollständiger Pfad. Die geschriebene Datei liegt immer innerhalb dieses Ordners — SuperTakt schreibt niemals daneben.",
  notChosen: "Noch nicht gewählt",
  chooseFolder: "Ordner wählen …",
  chooseOtherFolder: "Anderen Ordner wählen …",
  folderHintPicked: "Der Ordner wird im Dialog des Betriebssystems gewählt und nicht getippt. Die geschriebene Datei liegt immer innerhalb dieses Ordners — SuperTakt schreibt niemals daneben.",
  pickerUnavailable: "Der Ordnerauswahldialog steht hier nicht zur Verfügung",
  typeByHand: "Tragen Sie den vollständigen Pfad von Hand ein — SuperTakt prüft ihn genauso.",
  noShellTitle: "SuperTakt läuft gerade ohne seine Anwendungshülle",
  noShellBody: "Im Browser allein gibt es keinen Ordnerauswahldialog des Betriebssystems. In der installierten Anwendung wird der Ordner ausgewählt statt eingetippt.",
  notSavedYet: "Noch nicht übernommen — mit „Speichern“ wird dieser Ordner eingestellt.",
  folderOk: "Der Ordner ist vorhanden und beschreibbar — soeben geprüft. Vor jedem Exportlauf wird er erneut geprüft.",
  // Export groups (exportGroupLayout, ExportGroups, PreviewGroupRow)
  allExcluded: "Alle Buchungen ausgeschlossen",
  noteMissing: "Leistung fehlt",
  notExportable: "Nicht exportierbar",
  todoTableCaption: "Export nach Todo, aufklappbar nach Tagen",
  dayTableCaption: "Tagesgruppen für den Export",
  expand: "Aufklappen",
  selectAllGroups: "Alle exportierbaren Tagesgruppen auswählen",
  columnStatus: "Status",
  columnCall: "Call",
  columnTodo: "Todo",
  columnDays: "Tage",
  columnBookings: "Buchungen",
  columnSelectedDays: "Ausgewählte Tage",
  noCall: "ohne Call",
  multipleTodos: "Mehrere Todos",
  toggleDays: (title: string) => `Tage auf- oder einklappen: ${title}`,
  selectAllDays: (title: string) => `Alle exportierbaren Tage auswählen: ${title}`,
  daysBlocked: (count: number) => `${String(count)} ${count === 1 ? "Tag blockiert" : "Tage blockiert"}`,
  exportable: "Exportierbar",
  selection: "Auswahl",
  columnDate: "Datum",
  columnNote: "Leistung",
  columnExportTime: "Exportzeit",
  toggleBookings: (day: string) => `Buchungen auf- oder einklappen: ${day}`,
  exportGroup: (day: string) => `Tagesgruppe exportieren: ${day}`,
  roundedPrefix: "Gerundete Exportzeit: ",
  entriesLeadBefore: "Die einzelnen Buchungen mit ihrer ",
  entriesLeadStrong: "ungerundeten",
  entriesLeadAfter: " Dauer. Wird hier eine Buchung ausgeschlossen, ändert sich die gerundete Zeit der Gruppe sofort.",
  includeInGroup: "In der Tagesgruppe berücksichtigen: ",
  unroundedPrefix: "Ungerundete Dauer: ",
  sourcePrefix: "Herkunft: ",
  noNote: "— keine Leistung erfasst —",
  addNoteShort: "Leistung nachtragen",
  editNote: "Leistung bearbeiten",
  bookingSuffix: (period: string) => `, Buchung ${period}`,
  recorded: (duration: string) => `${duration} erfasst`,
  dayGroupSuffix: (day: string) => `, Tagesgruppe ${day}`,
  groupBookingsTitle: "Die Buchungen dieser Tagesgruppe",
  groupBookingsHint: " — ihre Leistungstexte führt der Dienst zu einem Text zusammen",
  // ExportScreen
  directoryProblem: {
    not_set: {
      title: "Es ist kein Exportordner eingestellt",
      body: "Ohne Exportordner schreibt SuperTakt keine Datei. Wählen Sie ihn in den Einstellungen.",
    },
    missing: {
      title: "Der eingestellte Exportordner ist nicht da",
      body: "Er wurde verschoben, umbenannt oder liegt auf einem Laufwerk, das gerade nicht verbunden ist. SuperTakt legt ihn nicht von sich aus wieder an.",
    },
    not_writable: {
      title: "In den Exportordner lässt sich nicht schreiben",
      body: "Der Ordner ist da, aber die Rechte fehlen. Ein Lauf würde mitten im Vorgang scheitern — deshalb hält SuperTakt hier an.",
    },
    not_a_directory: {
      title: "Der eingestellte Pfad ist kein Ordner",
      body: "Er zeigt auf eine Datei. SuperTakt schreibt Exporte nur in einen Ordner.",
    },
    // T-039: "does not answer" is not "does not exist"; the steps differ.
    unreachable: {
      title: "Der Exportordner antwortet nicht",
      body: "Die Prüfung hat drei Sekunden gewartet und keine Antwort bekommen. Das heißt nicht, dass es den Ordner nicht gibt — bei einem Netzlaufwerk heißt es meistens, dass die Verbindung fehlt. Verbinden Sie das Laufwerk neu, statt einen neuen Pfad einzutragen.",
    },
  },
  filterTodo: "Todo",
  restricted: "eingeschränkt",
  filterFrom: "Ab",
  filterTo: "Bis",
  narrowing: "Einengung",
  exportedBefore: "schon einmal exportiert",
  sourcesFailed: (message: string) => `Die Auswahlliste der Quellen ließ sich nicht laden: ${message}`,
  templatesFailed: (message: string) => `Die Exportvorlagen ließen sich nicht laden: ${message}`,
  exportWritten: "Export geschrieben.",
  exportWrittenBody: (bookings: string, rows: string, hours: string) => `${bookings} in ${rows} · ${hours} Stunden.`,
  exportWrittenSkipped: "Export geschrieben — mit ausgelassenen Gruppen.",
  groupStayed: "Tagesgruppe blieb",
  groupsStayed: "Tagesgruppen blieben",
  exportWrittenSkippedBody: (groups: string) => `${groups} stehen, weil die Leistung fehlt. Sie sind weiterhin offen und erscheinen beim nächsten Mal wieder.`,
  screenTitle: "Export",

  runBlockedFailed: "Solange die Gesamtvorschau fehlt, steht nicht fest, was geschrieben würde.",
  runBlockedPending: "Die Gesamtvorschau wird gerade gerechnet.",
  runExport: "Export ausführen",
  checkSettings: "In den Einstellungen prüfen",
  templateAndRounding: "Vorlage und Rundung",

  editTemplates: "Vorlagen bearbeiten",
  exportTemplate: "Exportvorlage",
  exportTemplateHint: "Hinweis zur Exportvorlage",
  savedStateBefore: "Gezeigt und geschrieben wird der ",
  savedStateStrong: "gespeicherte",
  savedStateAfter: " Stand dieser Vorlage. Ein Entwurf, der im Vorlageneditor noch nicht gespeichert ist, wirkt hier nicht mit.",
  builtIn: (name: string) => `${name} (mitgeliefert)`,
  rounding: "Rundung",
  roundingHint: "Hinweis: Rundung",
  roundingRule: "Auf die nächste Viertelstunde, mindestens 0,25 — angewandt auf die Summe der Tagesgruppe, nicht auf die einzelne Buchung.",
  folderHint: "Hinweis: Exportordner",
  folderCheckedOk: "Vorhanden und beschreibbar — soeben geprüft.",
  folderUnknown: "Zustand unbekannt.",
  folderNotChosen: "nicht gewählt",
  changeFolder: "Ordner ändern",
  billedAs: "Abgerechnet unter",
  billedAsHint: "Hinweis: Abgerechnet unter",
  billedAsNoName: "Der Dienst nennt keinen Benutzernamen. In der Datei steht trotzdem einer — welcher, zeigt danach das Exportprotokoll.",
  billedAsName: "Dieser Name steht in jeder Zeile der Datei. SuperTakt bekommt ihn vom Betriebssystem; über keine Einstellung lässt er sich ändern.",
  noNameReported: "kein Name gemeldet",
  inRows: (rows: string) => ` in ${rows}`,
  computingTotals: "Zeilen und Stunden werden gerechnet",
  computingTotalsDots: "Zeilen und Stunden werden gerechnet …",
  totalsUnknown: "Zeilen und Stunden unbekannt — die Vorschau hat nicht geantwortet",
  rowWithExported: "Zeile enthält eine schon einmal exportierte Buchung",
  rowsWithExported: "Zeilen enthalten schon einmal exportierte Buchungen",
  groupStays: "Gruppe bleibt stehen",
  groupsStay: "Gruppen bleiben stehen",
  noNoteNoExport: (groups: string) => `${groups} — ohne Leistung kein Export`,
  legend: "Legende",
  legendNoteMissing: "Leistung fehlt:",
  legendNoteMissingText: " Leistungstext in einer Buchung ergänzen.",
  legendAllExcluded: "Alle Buchungen ausgeschlossen:",
  legendAllExcludedText: " Mindestens eine Buchung auswählen.",
  legendGroupsStayOpen: "Betroffene Gruppen bleiben offen; der übrige Export läuft weiter.",
  filterLabel: "Export filtern",
  exportStatus: "Exportstatus",
  all: "Alle",
  open: "Offen",
  exported: "Exportiert",
  onlyExportedBefore: "Nur schon einmal exportierte",
  fromDay: "Ab Tag",
  toDay: "Bis Tag",
  lastSevenDays: "Letzte 7 Tage",
  restrictTodo: "Todo einschränken",
  // C-14 filters (welle-18-fluss.md 8.1)
  filterTag: "Tag",
  filterPool: "Pool",
  filterNote: "Leistung",
  allTags: "Alle Tags",
  allPoolsOption: "Alle Pools",
  noteAny: "Alle",
  notePresent: "Vorhanden",
  noteAbsent: "Fehlt",
  filterGone: "nicht mehr vorhanden",
  searchTodoOrCall: "Todo oder Call suchen …",
  previewByTodo: "Exportvorschau nach Todo und Tag",
  openBookingsLoading: "Offene Buchungen werden geladen",
  layoutFailed: "Die Gliederung ließ sich nicht abrufen",
  layoutFailedTail: "Solange die Gliederung fehlt, wird nichts zur Auswahl gestellt — eine geratene Zeilenzahl wäre schlimmer als keine.",
  nothingToExport: "Nichts zu exportieren",
  noOpenMatch: "Keine offenen Buchungen passen zu diesen Filtern.",
  noOpenBookings: "Es liegen keine offenen Buchungen für den Export vor.",
  toTimeTracking: "Zur Zeiterfassung",
  totalsFailed: "Die Gesamtvorschau ließ sich nicht abrufen",
  totalsFailedTail: "Solange sie fehlt, weiß SuperTakt nicht, wie viele Zeilen und wie viele Stunden dieser Lauf schreiben würde — deshalb ist „Export ausführen\" gesperrt. Eine Null an dieser Stelle wäre keine Auskunft, sondern eine Behauptung. Die Auswahl darunter bleibt erhalten.",
  templatesLoading: "Vorlagen werden geladen",
  confirmTitle: "Export ausführen?",
  bookingWill: "Buchung wird",
  bookingsWill: "Buchungen werden",
  confirmLead: (bookings: string, rows: string, hours: string) => `${bookings} in ${rows} geschrieben — zusammen ${hours} Stunden.`,
  // Locked sentence SP-17.
  confirmConsequence: "Die Datei wird geschrieben und jede enthaltene Buchung als exportiert markiert — beides zusammen oder gar nichts. Danach sind diese Buchungen gesperrt; ändern lassen sie sich erst nach dem ausdrücklichen Zurücksetzen des Exportstatus.",
  thisFolder: "diesem Ordner",
  firstRunAcknowledge: (folder: string) => `Mir ist bewusst: Die Datei landet in ${folder} und enthält lesbare Kundennotizen. Base64 ist eine Kodierung, keine Verschlüsselung.`,
  confirmExport: "Exportieren",
  thisTodo: "diesem Todo",
  // Template parsing and deviations (exportTemplateModel)
  parse: {
    notAnObject: "Die Vorlage ist kein Objekt.",
    unknownVersion: "Unbekannte Vorlagenfassung. Diese Anwendung liest Fassung 1.",
    noFieldList: "Die Vorlage führt keine Feldliste.",
    fieldNotAnObject: (position: string) => `Feld ${position} ist kein Objekt.`,
    fieldWithoutName: (position: string) => `Feld ${position} hat keinen Namen.`,
    unknownSource: (position: string, name: string) => `Feld ${position} (${name}) nennt eine Quelle, die diese Anwendung nicht kennt.`,
    unknownTransformation: (position: string, name: string) => `Feld ${position} (${name}) nennt eine unbekannte Transformation.`,
    conditionNotAnObject: (position: string, name: string) => `Die Bedingung von Feld ${position} (${name}) ist kein Objekt.`,
    conditionUnknownSource: (position: string, name: string) => `Die Bedingung von Feld ${position} (${name}) nennt eine unbekannte Quelle.`,
    conditionUnknownOperator: (position: string, name: string) => `Die Bedingung von Feld ${position} (${name}) nennt einen unbekannten Vergleich.`,
  },
  deviation: {
    missing: (name: string) => `Das Feld ${name} der Standardvorlage fehlt. Das Abrechnungstool erwartet es.`,
    source: (name: string, actual: string, expected: string) => `${name} liest ${actual} statt ${expected}.`,
    transformation: (name: string, actual: string, expected: string) =>
      `${name} wird als ${actual} ausgegeben, die Standardvorlage benutzt ${expected}.`,
    condition: (name: string, source: string, operator: string) =>
      `${name} steht nur in der Datei, wenn ${source} ${operator}. Die Standardvorlage gibt das Feld immer aus.`,
    extra: (name: string) => `Zusätzliches Feld ${name}, das die Standardvorlage nicht kennt.`,
    order: (names: string) => `Die Felder stehen in einer anderen Reihenfolge als in der Standardvorlage (${names}).`,
  },
  // Template editor (TemplateFieldRow, TemplateFields)
  positionPrefix: "Position ",
  key: "Schlüssel",
  source: "Quelle",
  transformation: "Transformation",
  sourceGone: "Diese Quelle steht nicht mehr auf der Auswahlliste des Dienstes.",
  keyEmpty: "Ohne Namen gibt es keinen Schlüssel in der Datei.",
  keyDuplicate: (name: string) => `${name} steht mehr als einmal in dieser Vorlage. In der Datei bleibt nur das letzte dieser Felder übrig.`,
  fieldNumber: (number: string) => `Feld ${number}`,
  fieldUp: (name: string) => `Feld ${name} nach oben`,
  fieldDown: (name: string) => `Feld ${name} nach unten`,
  fieldDuplicate: (name: string) => `Feld ${name} verdoppeln`,
  fieldRemove: (name: string) => `Feld ${name} entfernen`,
  onlyWithCondition: "Nur unter einer Bedingung ausgeben",
  checkedSource: "Geprüfte Quelle",
  comparison: "Vergleich",
  conditionHint: "Trifft die Bedingung nicht zu, fehlt der Schlüssel in dieser Zeile vollständig. Er steht dort nicht leer.",
  fieldMoved: (name: string, position: string, total: string) => `Feld ${name} steht jetzt an Position ${position} von ${total}.`,
  fieldDragged: (from: string, to: string) => `Feld an Position ${from} steht jetzt an Position ${to}.`,
  noFieldTitle: "Noch kein Feld",
  noFieldBody: "Eine Vorlage ohne Feld erzeugt keine Datei — der Dienst nimmt sie nicht an. Fügen Sie das erste Feld hinzu; die Vorschau zeigt sofort, was dabei herauskommt.",
  addFirstField: "Erstes Feld hinzufügen",
  fieldsLead: "Die Reihenfolge dieser Liste ist die Reihenfolge der Schlüssel in der Datei. Verschieben lässt sich ein Feld durch Ziehen am Griff oder mit den beiden Pfeilknöpfen.",
  addField: "Feld hinzufügen",
  templateNotSaved: "Die Vorlage wurde nicht gespeichert",
  templateUnchanged: "Die bisherige Fassung der Vorlage ist unverändert geblieben.",
  // TemplateList
  templatesNav: "Exportvorlagen",
  builtInBadge: "mitgeliefert",
  activeBadge: "aktiv",
  lastChanged: (when: string) => `Zuletzt geändert ${when}`,
  copyTemplate: (name: string) => `Vorlage ${name} kopieren`,
  builtinNotDeletable: "Die Standardvorlage lässt sich nicht löschen",
  deleteTemplate: (name: string) => `Vorlage ${name} löschen`,
  onlyBuiltin: "Es gibt bisher nur die Standardvorlage. Sie lässt sich nicht ändern, aber kopieren — und die Kopie können Sie beliebig umbauen.",
  // TemplatePreview
  previewSource: "Vorschau anhand Ihrer offenen Buchungen.",
  legendNoteMissingLong: " Leistungstext in einer Buchung ergänzen. Betroffene Tagesgruppen bleiben offen; der übrige Export läuft weiter.",
  unsavedDraft: (source: string) => `Noch nicht gespeicherter Entwurf. ${source}`,
  changedNotSaved: (source: string) => `Geänderter Stand, noch nicht gespeichert — die Vorschau speichert nichts. ${source}`,
  previewBookingsLoading: "Offene Buchungen für die Vorschau werden geladen",
  noOpenTitle: "Keine offenen Buchungen",
  noOpenBody: "Die Vorschau läuft auf echten Daten und erfindet keine. Sobald eine Zeit erfasst und noch nicht exportiert ist, steht hier, was diese Vorlage daraus macht.",
  noFieldNoRowTitle: "Noch kein Feld, also keine Zeile",
  noFieldNoRowBody: "Eine Vorlage ohne Feld erzeugt keine Datei — der Dienst nimmt sie nicht an. Fügen Sie links das erste Feld hinzu; die Vorschau zieht sofort nach.",
  cannotRender: "Diese Vorlage lässt sich so nicht rendern",
  cannotRenderTail: "Geprüft hat das dieselbe Stelle, die auch beim Speichern prüft — so wie es hier steht, ließe sich die Vorlage also auch nicht speichern. Geschrieben wurde nichts; die gespeicherte Fassung ist unverändert.",
  previewPending: "Vorschau wird erzeugt",
  previewPendingLong: "Der Dienst rendert Ihren Stand …",
  noRowTitle: "Diese Vorlage erzeugt keine Zeile",
  noRowBody: "Der Dienst hat den Entwurf angenommen, aber aus den offenen Buchungen entsteht damit keine Zeile. Prüfen Sie die Bedingungen an den Feldern.",
  dayGroup: "Tagesgruppe",
  dayGroups: "Tagesgruppen",
  openBooking: "offenen Buchung",
  openBookings: "offenen Buchungen",
  groupsFromBookings: (groups: string, bookings: string, newestFirst: boolean) => `${groups} aus ${bookings}${newestFirst ? " — neueste zuerst." : "."}`,
  currentDraft: "Aktueller Entwurf.",
  renderedFromSaved: (name: string) => `Gerendert aus der gespeicherten Vorlage ${name}.`,
  // TemplatesScreen
  copyOf: (name: string) => `Kopie von ${name}`,
  newTemplate: "Neue Vorlage",
  templateCreated: "Vorlage angelegt.",
  templateCreatedBody: (name: string) => `${name} steht jetzt in der Export-Ansicht zur Wahl.`,
  templateSaved: "Vorlage gespeichert.",
  templateSavedBody: (name: string) => `Bereits geschriebene Exportdateien ändern sich dadurch nicht — ${name} gilt ab dem nächsten Lauf.`,
  changesDiscarded: "Änderungen verworfen.",
  copyCreated: "Kopie angelegt.",
  copyCreatedBody: (name: string) => `${name} ist eine ganz gewöhnliche Vorlage: änderbar und löschbar.`,
  templateDeleted: "Vorlage gelöscht.",
  templateDeletedBody: "Bereits geschriebene Exportdateien bleiben, wie sie sind.",
  templateActivated: "Vorlage aktiviert.",
  templateActivatedBody: (name: string) => `Der nächste Export benutzt ${name}.`,
  templatesTitle: "Exportvorlagen",
  templatesLead: "Eine Vorlage bestimmt, welche Felder in die Datei gehen, in welcher Reihenfolge und unter welchem Namen.",
  templateListLoading: "Exportvorlagen werden geladen",
  openPreview: "Vorschau öffnen",
  forbiddenSourcesTitle: "Der Dienst hat Feldquellen geliefert, die nicht wählbar sein dürfen",
  forbiddenSources: (paths: string) => `SuperTakt bietet sie nicht an: ${paths}. Der interne Vermerk eines Todos geht in keinen Export (A-7.2). Melden Sie das bitte — an der Auswahlliste dieses Editors ändert es nichts, aber es gehört geprüft.`,
  builtinTemplate: "Standardvorlage",
  template: "Vorlage",
  builtinLead: "Die Struktur, die das Abrechnungstool erwartet. Sie lässt sich nicht ändern — aber kopieren.",
  editorLead: "Name und Felder. Die Reihenfolge der Felder ist die Reihenfolge der Schlüssel in der Datei.",
  createCopy: "Kopie anlegen",
  discard: "Verwerfen",
  save: "Speichern",
  templateName: "Name der Vorlage",
  templateNameHint: "Nur für Sie. In der Datei steht dieser Name nicht.",
  templateNameMissing: "Ohne Namen lässt sich die Vorlage nicht wiederfinden.",
  unsavedBefore: "Ungespeicherte Änderungen. Die Vorschau zeigt den aktuellen Entwurf — auf den ",
  unsavedStrong: "Export",
  unsavedAfter: " wirken sie sich erst nach dem Speichern aus.",
  cannotShow: "Diese Vorlage lässt sich nicht anzeigen",
  cannotShowTail: "Solange das so ist, wird sie hier nicht bearbeitet — eine halb gelesene Vorlage zu speichern hieße, Felder stillschweigend zu verlieren.",
  useTemplateTitle: "Diese Vorlage benutzen",
  useTemplateLead: "Der Export nimmt die Vorlage, die in den Einstellungen aktiv ist.",
  activeIsBefore: "Aktiv ist derzeit ",
  theBuiltinTemplate: "die Standardvorlage",
  activeIsAfter: ". Änderungen an dieser Vorlage wirken sich erst auf einen Export aus, wenn sie aktiv ist.",
  useForExport: "Für den Export verwenden",
  preview: "Vorschau",
  deleteTitle: (name: string) => `Vorlage ${name} löschen?`,
  deleteLead: "Die Vorlage verschwindet aus der Auswahl in der Export-Ansicht und in den Einstellungen.",
  deleteActive: "Diese Vorlage ist gerade die aktive. Nach dem Löschen greift wieder die mitgelieferte Standardvorlage. Bereits geschriebene Exportdateien bleiben unverändert.",
  deleteInactive: "Bereits geschriebene Exportdateien bleiben unverändert. Rückgängig machen lässt sich das Löschen nicht.",
  deleteConfirm: "Vorlage löschen",
  copyTitle: "Vorlage kopieren",
  copyBuiltinLead: "Die Kopie enthält dieselben Felder wie die Standardvorlage und ist von da an eine ganz gewöhnliche Vorlage: änderbar und löschbar.",
  copyLead: "Die Kopie enthält dieselben Felder und lässt sich unabhängig weiterbearbeiten.",
  copyName: "Name der Kopie",
  copyNameMissing: "Name der Kopie fehlt.",
  leaveTitle: "Diese Vorlage hat ungespeicherte Änderungen",
  leaveLead: "Wenn Sie jetzt wechseln, gehen die Änderungen an dieser Vorlage verloren.",
  leaveConsequence: "Die gespeicherte Fassung bleibt unverändert; Export und Vorschau benutzen weiterhin sie.",
  leaveConfirm: "Änderungen verwerfen und wechseln",
  stay: "Hierbleiben",
  builtinStructure: (fields: string) => `Diese Vorlage bildet die Struktur ab, die das Abrechnungstool erwartet: ${fields}. Sie ist mitgeliefert und lässt sich weder ändern noch löschen — genau deshalb ist sie der Stand, auf den Sie jederzeit zurückkommen können.`,
  builtinFieldsFallback: "die mitgelieferten Felder",
  builtinCopyHint: "Wollen Sie etwas anderes exportieren, legen Sie eine Kopie an. Die Kopie ist eine gewöhnliche Vorlage, und SuperTakt zeigt Ihnen dort laufend, worin sie von dieser hier abweicht.",
  compareWith: (name: string) => `Abgleich mit ${name}`,
  compareLead: "Was das Abrechnungstool erwartet, steht in der mitgelieferten Vorlage. Hier steht, worin diese davon abweicht.",
  compareEqual: "Diese Vorlage entspricht der Struktur der Standardvorlage — gleiche Felder, gleiche Quellen, gleiche Transformationen.",
  compareOnlyAdditions: "Die erwartete Struktur ist vollständig enthalten; darüber hinaus gibt es Ergänzungen.",
  compareDeviations: "Abweichungen sind erlaubt — sie sollen nur nicht versehentlich entstehen. Prüfen Sie, ob das Abrechnungstool damit umgehen kann.",
};

const en: typeof de = {
  eventPrefix: "Action: ",
  transitionPrefix: "Status change: ",
  bookingGone: "This booking can no longer be found. The log row stays anyway — it is the proof that it existed.",
  call: "Call",
  noRun: "No export run — this time never went into a file.",
  runNotLoaded: "The related export run could not be loaded.",
  written: (when: string) => `written ${when}`,
  notBilledWithoutReason: "Written off without a reason. The field is optional — it is still logged that someone ticked off time without billing here, and when.",
  reason: "Reason",
  actorPrefix: "Triggered by: ",
  runUnreadable: "Run no longer readable",
  unknownTodo: "Unknown todo",
  eventDescription: {
    exported: "Written into an export file. The file is shown next to it; the booking was locked afterwards.",
    reset: "The export status was reset. This time goes into billing again with the next export — this is exactly what this log is for.",
    not_billed: "Written off by hand: this time is not billed. No export file ever contained it, so no run is shown here.",
  },
  event: "Action",
  run: "Run",
  runNotLoadedYet: "not loaded yet",
  auditTitle: "Export log",
  auditLead: "Every change of an export status, with time, booking, action and run. Append-only and unchangeable.",
  toExport: "Go to export",
  auditFilter: "Filter log",
  eventLoaded: "action loaded",
  eventsLoaded: "actions loaded",
  eventsOfTotal: (loaded: string, total: string) => `${loaded} of ${total}`,
  eventSingular: "action",
  eventPlural: "actions",
  eventsOfLoaded: (visible: string, loaded: string) => `${visible} of ${loaded} loaded`,
  loadingShort: "loading …",
  allEvents: "All actions",
  exportRun: "Export run",
  allRuns: "All runs",
  auditLegendNote: "A row can be neither changed nor deleted — there is no route for it, and the storage forbids both as well. If you reset a booking and export it again, you find both here side by side.",
  auditLoading: "Loading the export log",
  auditEmptyTitle: "No action logged yet",
  auditEmptyBody: "As soon as the first export runs, a booking is reset or a time is ticked off as “not billed”, it appears here — with time, booking and run.",
  auditNoMatchTitle: "No action matches these filters",
  auditNoMatchBody: "The filter works on the loaded rows. Load more if you are looking for an older action — or reset the filter.",
  loadMore: "Load more",
  resetFilters: "Reset filters",
  countedOne: "Counted over the one action.",
  countedAll: (total: string) => `Counted over all ${total} actions.`,
  countedPartial: (loaded: string, total: string) => `Counted over ${loaded} of ${total} actions — without those not loaded yet.`,
  tileExported: (scope: string) => `Written into a file. ${scope}`,
  tileReset: (scope: string) => `The same time then goes into billing again. ${scope}`,
  tileNotBilled: (scope: string) => `Never exported, deliberately not billed. ${scope}`,
  scopeFilter: "The tiles count over all loaded actions, not over the filter that is set.",
  scopeOlder: "Older actions are not loaded yet. “Load more” at the end of the list raises both numbers.",
  scopeFilterAndOlder: "The tiles count over all loaded actions, not over the filter that is set. Older ones are not loaded yet either.",
  auditEnd: "This is the start of the log — there are no older actions.",
  loadMoreLeft: (left: string) => `Load more (${left} left)`,
  recentRuns: "Recent export runs",
  recentRunsLead: "What was written when.",
  openLog: "Open log",
  noExportTitle: "No export yet",
  noExportBody: "The first run writes the first file.",
  booking: "booking",
  bookings: "bookings",
  runFilterHint: "Opens the log with this run as filter. The filter works on the loaded rows; for older runs, more must be loaded there.",
  runBookings: "Bookings of this run",

  tabExport: "Export",
  tabTemplates: "Templates",
  tabLog: "Log",
  tabsLabel: "Export areas",

  runDone: "Export finished",
  runDoneLead: "Written in one transaction.",
  hide: "Hide",
  file: "File",
  scope: "Scope",
  exportRow: "export row",
  exportRows: "export rows",
  runScope: (bookings: string, rows: string, hours: string, bytes: string) => `${bookings} in ${rows} · ${hours} hours · ${bytes}`,
  checksum: "Checksum",
  groupSkipped: "day group was",
  groupsSkipped: "day groups were",
  skippedTitle: (groups: string) => `${groups} skipped`,
  skippedBefore: "The billing tool does not accept a row without work text. The rest of the export went through; these groups are ",
  skippedStrong: "still open",
  skippedAfter: " and appear again next time. Add the work done, and they go along.",
  addNote: "Add work done",

  rowDeselected: "This day group is deselected and produces no row. Tick it, and this shows what would be written.",
  noTemplate: "No export template is selected. Without one there is no row to show — and no run.",
  templateUnreadable: "This template cannot be read",
  templateUnreadableTail: "The same check that runs on save found this. As long as that is so, no row is shown here — a guessed one would be worse than none.",
  templateReading: "Reading the template",
  templateReadingDots: "Reading the template …",
  rowComputing: "Computing the row",
  rowComputingLong: "Computing the row — by the service, with the same renderer as the file.",
  clearTextInGroup: "The plain text is shown below with the bookings of this day group.",
  clearTextBelow: "The plain text is shown below with the bookings.",
  asInFile: "As it appears in the file",
  fieldByField: "Field by field",
  base64Note: "Base64 is an encoding, not encryption.",
  missingKeys: (names: string) => `Not in this row because the condition did not apply: ${names}. The key is missing entirely, it is not present empty.`,
  directoryAdvice: {
    not_absolute: {
      title: "This is not a full path",
      body: "SuperTakt needs the whole way to the folder — on Windows with a drive letter, for example C:\\Takt\\Export. A path without a start points somewhere else depending on the working directory.",
    },
    drive_root: {
      title: "This is the root of a drive",
      body: "SuperTakt does not write there. Export files in the drive root are visible to every program that searches the drive, and later cannot be told apart from the system's files. Create a subfolder of its own.",
    },
    system_directory: {
      title: "This is an operating system directory",
      body: "Nothing SuperTakt writes belongs there. The export contains customer data that nobody expects in a system folder and that can disappear there without warning at the next update or cleanup. Choose a folder under your user profile.",
    },
    network_share: {
      title: "This folder is not on this computer",
      body: "The export file contains readable customer notes and thus leaves this computer — for a product that works fully locally according to E-001. And the export fails whenever the connection is down: the drive is disconnected, the server unreachable, the notebook not in the company network. If this is your hand-over path to billing, it is the right folder — now you know what goes into it.",
    },
    sync_folder: {
      title: "This folder is synchronised to online storage",
      body: "Everything SuperTakt puts here is uploaded shortly after — automatically, without further question and without anyone seeing it. The export file contains readable customer notes; Base64 is an encoding, not encryption. Your customers' data then sits with a provider, and that decision is better made here than later while tidying up.",
    },
    roaming_profile: {
      title: "This folder belongs to the roaming profile",
      body: "The folder AppData\\Roaming is copied to a file server at sign-in and sign-out if the account has a roaming profile. The export files with their readable customer notes travel along. This is exactly why SuperTakt's data lives under AppData\\Local (E-018) — there it stays on this computer.",
    },
    redirected_folder: {
      title: "On managed computers this folder is often redirected to OneDrive",
      body: "On business Windows computers, Desktop, Documents and Pictures are regularly moved to OneDrive via “Known Folder Move”. From outside the path looks unchanged. Check in Explorer whether the folder shows a cloud icon — if so, the export files go to online storage.",
    },
    volatile_folder: {
      title: "The Downloads folder is emptied by cleanup tools",
      body: "Windows Storage Sense and most cleanup tools delete here without asking. An export file that has not yet reached billing would then be gone — and the bookings in it are already marked as exported.",
    },
  },
  foundInPath: "Found in the path",
  traits: {
    unc: {
      title: "The folder is a network share",
      body: "The path is written in UNC notation. The export then writes over the network: if the share is gone, the run fails — completely, without a half file (A-8.8).",
    },
    network: {
      title: "The folder is on a network file system",
      body: "Proven by the kind of file system, not by the name. The same applies as for a share: no connection, no run.",
    },
    sync_folder: {
      title: "The folder belongs to a synchronisation service",
      body: "Its client reports it this way itself — even if the folder was renamed. The export file contains readable customer notes (A-8.9); here it leaves this computer as soon as it is written.",
    },
    system_dir: {
      title: "The folder is a system directory",
      body: "The operating system names it so itself, regardless of which drive Windows is on. Nothing SuperTakt writes belongs there.",
    },
  },
  traitSource: "Proven by the operating system, not read from the path.",
  nothingProven: "Nothing was proven about the configured folder. That is no all-clear, but no statement at all: ",
  alsoChecked: "Also checked: ",
  mappedDriveBefore: "A ",
  mappedDriveStrong: "mapped network drive",
  mappedDriveMiddle: " such as ",
  mappedDriveAfter: " is not recognised by SuperTakt — the service does not get this information from the operating system.",
  unreachableOpen: " And because this folder does not answer right now, the file system could not be asked either; whether it is on the network remains open.",
  base64Before: "The export file contains ",
  base64Strong: "readable customer notes",
  base64After: ". Base64 is an encoding, not encryption — whoever can open the file can read it.",
  directoryState: {
    not_set: "Not chosen yet. Without an export folder no export is possible.",
    missing: "This folder cannot be reached. SuperTakt does not create it by itself.",
    not_writable: "This folder exists, but SuperTakt may not write into it.",
    not_a_directory: "This path points to a file, not a folder.",
    unreachable: "This folder did not answer within three seconds. That does not prove it does not exist — for a network drive usually only the connection is missing.",
  },
  shellNoAnswer: "The application shell did not answer when asked for the folder picker.",
  folderChosen: (path: string) => `Folder chosen: ${path}. Save to apply.`,
  pickCancelled: "Selection cancelled. The folder set so far stays.",
  exportFolder: "Export folder",
  folderPlaceholder: "e.g. C:\\Takt\\Export",
  folderHintTyped: "Full path. The written file always goes inside this folder — SuperTakt never writes next to it.",
  notChosen: "Not chosen yet",
  chooseFolder: "Choose folder …",
  chooseOtherFolder: "Choose other folder …",
  folderHintPicked: "The folder is chosen in the operating system's dialog, not typed. The written file always goes inside this folder — SuperTakt never writes next to it.",
  pickerUnavailable: "The folder picker is not available here",
  typeByHand: "Enter the full path by hand — SuperTakt checks it the same way.",
  noShellTitle: "SuperTakt is running without its application shell right now",
  noShellBody: "In the browser alone there is no folder picker of the operating system. In the installed application the folder is picked instead of typed.",
  notSavedYet: "Not applied yet — “Save” sets this folder.",
  folderOk: "The folder exists and is writable — just checked. It is checked again before every export run.",
  allExcluded: "All bookings excluded",
  noteMissing: "Work done missing",
  notExportable: "Not exportable",
  todoTableCaption: "Export by todo, expandable by day",
  dayTableCaption: "Day groups for the export",
  expand: "Expand",
  selectAllGroups: "Select all exportable day groups",
  columnStatus: "Status",
  columnCall: "Call",
  columnTodo: "Todo",
  columnDays: "Days",
  columnBookings: "Bookings",
  columnSelectedDays: "Selected days",
  noCall: "without call",
  multipleTodos: "Multiple todos",
  toggleDays: (title: string) => `Expand or collapse days: ${title}`,
  selectAllDays: (title: string) => `Select all exportable days: ${title}`,
  daysBlocked: (count: number) => `${String(count)} ${count === 1 ? "day blocked" : "days blocked"}`,
  exportable: "Exportable",
  selection: "Selection",
  columnDate: "Date",
  columnNote: "Work done",
  columnExportTime: "Export time",
  toggleBookings: (day: string) => `Expand or collapse bookings: ${day}`,
  exportGroup: (day: string) => `Export day group: ${day}`,
  roundedPrefix: "Rounded export time: ",
  entriesLeadBefore: "The single bookings with their ",
  entriesLeadStrong: "unrounded",
  entriesLeadAfter: " duration. Excluding a booking here changes the group's rounded time at once.",
  includeInGroup: "Include in the day group: ",
  unroundedPrefix: "Unrounded duration: ",
  sourcePrefix: "Source: ",
  noNote: "— no work recorded —",
  addNoteShort: "Add work done",
  editNote: "Edit work done",
  bookingSuffix: (period: string) => `, booking ${period}`,
  recorded: (duration: string) => `${duration} recorded`,
  dayGroupSuffix: (day: string) => `, day group ${day}`,
  groupBookingsTitle: "The bookings of this day group",
  groupBookingsHint: " — the service joins their work texts into one text",
  directoryProblem: {
    not_set: {
      title: "No export folder is set",
      body: "Without an export folder SuperTakt writes no file. Choose one in the settings.",
    },
    missing: {
      title: "The configured export folder is not there",
      body: "It was moved, renamed or is on a drive that is not connected right now. SuperTakt does not create it again by itself.",
    },
    not_writable: {
      title: "The export folder cannot be written to",
      body: "The folder is there, but the permissions are missing. A run would fail midway — so SuperTakt stops here.",
    },
    not_a_directory: {
      title: "The configured path is not a folder",
      body: "It points to a file. SuperTakt writes exports only into a folder.",
    },
    unreachable: {
      title: "The export folder does not answer",
      body: "The check waited three seconds and got no answer. That does not mean the folder does not exist — for a network drive it usually means the connection is missing. Reconnect the drive instead of entering a new path.",
    },
  },
  filterTodo: "Todo",
  restricted: "restricted",
  filterFrom: "From",
  filterTo: "To",
  narrowing: "Narrowed",
  exportedBefore: "exported before",
  sourcesFailed: (message: string) => `The list of sources could not be loaded: ${message}`,
  templatesFailed: (message: string) => `The export templates could not be loaded: ${message}`,
  exportWritten: "Export written.",
  exportWrittenBody: (bookings: string, rows: string, hours: string) => `${bookings} in ${rows} · ${hours} hours.`,
  exportWrittenSkipped: "Export written — with skipped groups.",
  groupStayed: "day group stayed",
  groupsStayed: "day groups stayed",
  exportWrittenSkippedBody: (groups: string) => `${groups} behind because the work done is missing. They are still open and appear again next time.`,
  screenTitle: "Export",

  runBlockedFailed: "As long as the overall preview is missing, it is not certain what would be written.",
  runBlockedPending: "The overall preview is being computed.",
  runExport: "Run export",
  checkSettings: "Check in settings",
  templateAndRounding: "Template and rounding",

  editTemplates: "Edit templates",
  exportTemplate: "Export template",
  exportTemplateHint: "Note on the export template",
  savedStateBefore: "Shown and written is the ",
  savedStateStrong: "saved",
  savedStateAfter: " state of this template. A draft not yet saved in the template editor does not take part here.",
  builtIn: (name: string) => `${name} (built-in)`,
  rounding: "Rounding",
  roundingHint: "Note: rounding",
  roundingRule: "To the next quarter hour, at least 0.25 — applied to the sum of the day group, not to the single booking.",
  folderHint: "Note: export folder",
  folderCheckedOk: "Exists and is writable — just checked.",
  folderUnknown: "State unknown.",
  folderNotChosen: "not chosen",
  changeFolder: "Change folder",
  billedAs: "Billed as",
  billedAsHint: "Note: billed as",
  billedAsNoName: "The service reports no user name. The file still carries one — the export log shows which one afterwards.",
  billedAsName: "This name is in every row of the file. SuperTakt gets it from the operating system; no setting can change it.",
  noNameReported: "no name reported",
  inRows: (rows: string) => ` in ${rows}`,
  computingTotals: "Computing rows and hours",
  computingTotalsDots: "Computing rows and hours …",
  totalsUnknown: "Rows and hours unknown — the preview did not answer",
  rowWithExported: "row contains a booking exported before",
  rowsWithExported: "rows contain bookings exported before",
  groupStays: "group stays behind",
  groupsStay: "groups stay behind",
  noNoteNoExport: (groups: string) => `${groups} — no work done, no export`,
  legend: "Legend",
  legendNoteMissing: "Work done missing:",
  legendNoteMissingText: " add a work text in a booking.",
  legendAllExcluded: "All bookings excluded:",
  legendAllExcludedText: " select at least one booking.",
  legendGroupsStayOpen: "Affected groups stay open; the rest of the export goes ahead.",
  filterLabel: "Filter export",
  exportStatus: "Export status",
  all: "All",
  open: "Open",
  exported: "Exported",
  onlyExportedBefore: "Only exported before",
  fromDay: "From day",
  toDay: "To day",
  lastSevenDays: "Last 7 days",
  restrictTodo: "Restrict to todo",
  filterTag: "Tag",
  filterPool: "Pool",
  filterNote: "Work done",
  allTags: "All tags",
  allPoolsOption: "All pools",
  noteAny: "All",
  notePresent: "Present",
  noteAbsent: "Missing",
  filterGone: "no longer exists",
  searchTodoOrCall: "Search todo or call …",
  previewByTodo: "Export preview by todo and day",
  openBookingsLoading: "Loading open bookings",
  layoutFailed: "The breakdown could not be retrieved",
  layoutFailedTail: "As long as the breakdown is missing, nothing is offered for selection — a guessed row count would be worse than none.",
  nothingToExport: "Nothing to export",
  noOpenMatch: "No open bookings match these filters.",
  noOpenBookings: "There are no open bookings for the export.",
  toTimeTracking: "Go to time tracking",
  totalsFailed: "The overall preview could not be retrieved",
  totalsFailedTail: "As long as it is missing, SuperTakt does not know how many rows and hours this run would write — which is why “Run export” is locked. A zero here would be no information but a claim. The selection below is kept.",
  templatesLoading: "Loading templates",
  confirmTitle: "Run export?",
  bookingWill: "booking is",
  bookingsWill: "bookings are",
  confirmLead: (bookings: string, rows: string, hours: string) => `${bookings} written in ${rows} — ${hours} hours in total.`,
  confirmConsequence: "The file is written and every booking in it is marked as exported — both together or nothing. After that these bookings are locked; they can only be changed after an explicit reset of the export status.",
  thisFolder: "this folder",
  firstRunAcknowledge: (folder: string) => `I am aware: the file lands in ${folder} and contains readable customer notes. Base64 is an encoding, not encryption.`,
  confirmExport: "Export",
  thisTodo: "this todo",
  parse: {
    notAnObject: "The template is not an object.",
    unknownVersion: "Unknown template version. This application reads version 1.",
    noFieldList: "The template has no field list.",
    fieldNotAnObject: (position: string) => `Field ${position} is not an object.`,
    fieldWithoutName: (position: string) => `Field ${position} has no name.`,
    unknownSource: (position: string, name: string) => `Field ${position} (${name}) names a source this application does not know.`,
    unknownTransformation: (position: string, name: string) => `Field ${position} (${name}) names an unknown transformation.`,
    conditionNotAnObject: (position: string, name: string) => `The condition of field ${position} (${name}) is not an object.`,
    conditionUnknownSource: (position: string, name: string) => `The condition of field ${position} (${name}) names an unknown source.`,
    conditionUnknownOperator: (position: string, name: string) => `The condition of field ${position} (${name}) names an unknown comparison.`,
  },
  deviation: {
    missing: (name: string) => `The field ${name} of the default template is missing. The billing tool expects it.`,
    source: (name: string, actual: string, expected: string) => `${name} reads ${actual} instead of ${expected}.`,
    transformation: (name: string, actual: string, expected: string) =>
      `${name} is output as ${actual}; the default template uses ${expected}.`,
    condition: (name: string, source: string, operator: string) =>
      `${name} is only in the file if ${source} ${operator}. The default template always outputs the field.`,
    extra: (name: string) => `Additional field ${name} that the default template does not know.`,
    order: (names: string) => `The fields are in a different order than in the default template (${names}).`,
  },
  positionPrefix: "Position ",
  key: "Key",
  source: "Source",
  transformation: "Transformation",
  sourceGone: "This source is no longer on the service's list.",
  keyEmpty: "Without a name there is no key in the file.",
  keyDuplicate: (name: string) => `${name} appears more than once in this template. Only the last of these fields remains in the file.`,
  fieldNumber: (number: string) => `Field ${number}`,
  fieldUp: (name: string) => `Move field ${name} up`,
  fieldDown: (name: string) => `Move field ${name} down`,
  fieldDuplicate: (name: string) => `Duplicate field ${name}`,
  fieldRemove: (name: string) => `Remove field ${name}`,
  onlyWithCondition: "Output only under a condition",
  checkedSource: "Checked source",
  comparison: "Comparison",
  conditionHint: "If the condition does not apply, the key is missing entirely from this row. It is not present empty.",
  fieldMoved: (name: string, position: string, total: string) => `Field ${name} is now at position ${position} of ${total}.`,
  fieldDragged: (from: string, to: string) => `Field at position ${from} is now at position ${to}.`,
  noFieldTitle: "No field yet",
  noFieldBody: "A template without a field produces no file — the service does not accept it. Add the first field; the preview shows at once what comes out.",
  addFirstField: "Add first field",
  fieldsLead: "The order of this list is the order of the keys in the file. Move a field by dragging its handle or with the two arrow buttons.",
  addField: "Add field",
  templateNotSaved: "The template was not saved",
  templateUnchanged: "The previous version of the template is unchanged.",
  templatesNav: "Export templates",
  builtInBadge: "built-in",
  activeBadge: "active",
  lastChanged: (when: string) => `Last changed ${when}`,
  copyTemplate: (name: string) => `Copy template ${name}`,
  builtinNotDeletable: "The default template cannot be deleted",
  deleteTemplate: (name: string) => `Delete template ${name}`,
  onlyBuiltin: "So far there is only the default template. It cannot be changed, but copied — and you can rebuild the copy as you like.",
  previewSource: "Preview based on your open bookings.",
  legendNoteMissingLong: " add a work text in a booking. Affected day groups stay open; the rest of the export goes ahead.",
  unsavedDraft: (source: string) => `Draft not saved yet. ${source}`,
  changedNotSaved: (source: string) => `Changed state, not saved yet — the preview saves nothing. ${source}`,
  previewBookingsLoading: "Loading open bookings for the preview",
  noOpenTitle: "No open bookings",
  noOpenBody: "The preview runs on real data and invents none. As soon as time is recorded and not yet exported, this shows what this template makes of it.",
  noFieldNoRowTitle: "No field yet, so no row",
  noFieldNoRowBody: "A template without a field produces no file — the service does not accept it. Add the first field on the left; the preview follows at once.",
  cannotRender: "This template cannot be rendered like this",
  cannotRenderTail: "The same check that runs on save found this — as it stands, the template could not be saved either. Nothing was written; the saved version is unchanged.",
  previewPending: "Creating preview",
  previewPendingLong: "The service is rendering your state …",
  noRowTitle: "This template produces no row",
  noRowBody: "The service accepted the draft, but it produces no row from the open bookings. Check the conditions on the fields.",
  dayGroup: "day group",
  dayGroups: "day groups",
  openBooking: "open booking",
  openBookings: "open bookings",
  groupsFromBookings: (groups: string, bookings: string, newestFirst: boolean) => `${groups} from ${bookings}${newestFirst ? " — newest first." : "."}`,
  currentDraft: "Current draft.",
  renderedFromSaved: (name: string) => `Rendered from the saved template ${name}.`,
  copyOf: (name: string) => `Copy of ${name}`,
  newTemplate: "New template",
  templateCreated: "Template created.",
  templateCreatedBody: (name: string) => `${name} can now be chosen in the export view.`,
  templateSaved: "Template saved.",
  templateSavedBody: (name: string) => `Export files already written do not change — ${name} applies from the next run.`,
  changesDiscarded: "Changes discarded.",
  copyCreated: "Copy created.",
  copyCreatedBody: (name: string) => `${name} is an ordinary template: changeable and deletable.`,
  templateDeleted: "Template deleted.",
  templateDeletedBody: "Export files already written stay as they are.",
  templateActivated: "Template activated.",
  templateActivatedBody: (name: string) => `The next export uses ${name}.`,
  templatesTitle: "Export templates",
  templatesLead: "A template decides which fields go into the file, in which order and under which name.",
  templateListLoading: "Loading export templates",
  openPreview: "Open preview",
  forbiddenSourcesTitle: "The service delivered field sources that must not be selectable",
  forbiddenSources: (paths: string) => `SuperTakt does not offer them: ${paths}. A todo's internal note goes into no export (A-7.2). Please report this — it changes nothing in this editor's list, but it needs checking.`,
  builtinTemplate: "Default template",
  template: "Template",
  builtinLead: "The structure the billing tool expects. It cannot be changed — but copied.",
  editorLead: "Name and fields. The order of the fields is the order of the keys in the file.",
  createCopy: "Create copy",
  discard: "Discard",
  save: "Save",
  templateName: "Template name",
  templateNameHint: "For you only. This name is not in the file.",
  templateNameMissing: "Without a name the template cannot be found again.",
  unsavedBefore: "Unsaved changes. The preview shows the current draft — they affect the ",
  unsavedStrong: "export",
  unsavedAfter: " only after saving.",
  cannotShow: "This template cannot be shown",
  cannotShowTail: "As long as that is so, it is not edited here — saving a half-read template would silently lose fields.",
  useTemplateTitle: "Use this template",
  useTemplateLead: "The export takes the template that is active in the settings.",
  activeIsBefore: "Currently active is ",
  theBuiltinTemplate: "the default template",
  activeIsAfter: ". Changes to this template only affect an export once it is active.",
  useForExport: "Use for export",
  preview: "Preview",
  deleteTitle: (name: string) => `Delete template ${name}?`,
  deleteLead: "The template disappears from the choice in the export view and in the settings.",
  deleteActive: "This template is currently the active one. After deleting, the built-in default template applies again. Export files already written stay unchanged.",
  deleteInactive: "Export files already written stay unchanged. Deleting cannot be undone.",
  deleteConfirm: "Delete template",
  copyTitle: "Copy template",
  copyBuiltinLead: "The copy contains the same fields as the default template and from then on is an ordinary template: changeable and deletable.",
  copyLead: "The copy contains the same fields and can be edited independently.",
  copyName: "Name of the copy",
  copyNameMissing: "Name of the copy is missing.",
  leaveTitle: "This template has unsaved changes",
  leaveLead: "If you switch now, the changes to this template are lost.",
  leaveConsequence: "The saved version stays unchanged; export and preview keep using it.",
  leaveConfirm: "Discard changes and switch",
  stay: "Stay here",
  builtinStructure: (fields: string) => `This template maps the structure the billing tool expects: ${fields}. It is built in and can be neither changed nor deleted — which is exactly why it is the state you can always come back to.`,
  builtinFieldsFallback: "the built-in fields",
  builtinCopyHint: "If you want to export something else, create a copy. The copy is an ordinary template, and SuperTakt keeps showing you there how it differs from this one.",
  compareWith: (name: string) => `Comparison with ${name}`,
  compareLead: "What the billing tool expects is in the built-in template. This shows how this one differs from it.",
  compareEqual: "This template matches the structure of the default template — same fields, same sources, same transformations.",
  compareOnlyAdditions: "The expected structure is fully contained; beyond that there are additions.",
  compareDeviations: "Deviations are allowed — they just should not happen by accident. Check whether the billing tool can handle them.",
};

export function exportTexts(): typeof de {
  return pickTexts({ de, en });
}
