import { pickTexts } from "../../lib/language";

/** UI texts of this feature (A-28.2). `en` has the shape of `de`. */
const de = {
  // PoolAdministration
  undo: "Rückgängig",
  placementFailed: "Der Anzeigeort ließ sich nicht ändern",
  // Order of rules (A-28.3, welle-18-fluss.md 3)
  orderOf: (name: string) => `Reihenfolge von ${name}`,
  moveUp: (name: string) => `${name} nach oben verschieben`,
  moveDown: (name: string) => `${name} nach unten verschieben`,
  orderChanged: "Reihenfolge geändert.",
  orderMoved: (name: string, up: boolean) => `${name} steht jetzt weiter ${up ? "oben" : "unten"}.`,
  orderMovedOnBoard: (left: boolean) => `Auf dem Board steht die Spalte jetzt weiter ${left ? "links" : "rechts"}.`,
  orderFailed: "Die Reihenfolge ließ sich nicht ändern",
  rulesTitle: "Regeln",
  rulesLead: "Eine Regel bündelt Todos. Der Anzeigeort sagt, wo sie erscheint.",
  newRule: "Neue Regel",
  noRuleTitle: "Noch keine Regel",
  noRuleBody: "Etwa alles unter dem Ordner „Kunden“ — oder alles Erledigte, das noch offen ist.",
  firstRule: "Erste Regel anlegen",
  poolEmpty: "Ohne Bedingung — dieser Pool bleibt leer.",
  showTodos: "Todos ansehen",
  addAsColumn: "Als Spalte aufnehmen",
  removeFromBoard: "Vom Board nehmen",
  rename: "Umbenennen",
  editRule: "Regel bearbeiten",
  delete: "Löschen",
  deleteRuleTitle: "Regel löschen?",
  deleteRuleLead: (name: string) => `Die Regel ${name} wird entfernt.`,
  deleteColumnConsequence: "An den Todos ändert sich nichts — die Zugehörigkeit war nie gespeichert. Auf dem Board verschwindet die Spalte; ihre Karten stehen weiter in der Todo-Liste.",
  deletePoolConsequence: "An den Todos ändert sich nichts. Die Zugehörigkeit war nie gespeichert.",
  ruleDeleted: "Regel gelöscht.",
  ruleDeleteFailed: "Die Regel ließ sich nicht löschen",
  // TagAdministration
  tagsAndFolders: "Tags und Ordner",
  tagsLead: "Beliebig tief verschachtelbar. Ein Tag liegt in genau einem Ordner oder auf der Wurzelebene.",
  folder: "Ordner",
  tag: "Tag",
  noTagTitle: "Noch kein Tag",
  noTagBody: "Tags ordnen Todos, und die meisten Regeln fragen nach ihnen. Ohne ein einziges Tag bleibt von einer Regel nur, was sie über Status, „Erledigt“ und den Exportstatus sagt.",
  firstTag: "Ersten Tag anlegen",
  moveFailed: "Das Verschieben hat nicht geklappt",
  atRoot: "auf der Wurzelebene",
  inFolder: (name: string) => `in ${name}`,
  nowLies: (name: string, place: string) => `${name} liegt jetzt ${place}.`,
  pickEntry: "Wählen Sie links einen Eintrag. Dann erscheinen hier seine Aktionen.",
  move: "Verschieben",
  todosWithTag: "Todos mit diesem Tag",
  newTagTitle: "Neuen Tag anlegen",
  newTagAtRoot: "Er landet auf der Wurzelebene. Über die Ordnerwahl geht es auch tiefer.",
  newTagInFolder: "Er landet im gerade gewählten Ordner.",
  create: "Anlegen",
  tagCreated: "Tag angelegt.",
  name: "Name",
  newFolderTitle: "Neuen Ordner anlegen",
  newFolderLead: "Ordner können beliebig tief ineinander liegen.",
  folderCreated: "Ordner angelegt.",
  save: "Speichern",
  renamed: "Umbenannt.",
  moveTagTitle: "Tag verschieben",
  nestFolderTitle: "Ordner verschachteln",
  moveTagLead: "Ein Tag liegt in genau einem Ordner. Die Todos, die ihn tragen, bleiben unberührt.",
  nestFolderLead: "Ein Ordner kann nicht unter einen seiner eigenen Unterordner. SuperTakt lehnt das ab, statt einen Zyklus anzulegen.",
  moved: "Verschoben.",
  folderForTag: "Ordner für dieses Tag",
  newParentFolder: "Neuer übergeordneter Ordner",
  rootLevel: "Wurzelebene",
  folderNotDeleted: "Der Ordner wurde nicht gelöscht",
  tagNotDeleted: "Das Tag wurde nicht gelöscht",
  deleteFolderTitle: "Ordner löschen?",
  deleteTagTitle: "Tag löschen?",
  willBeRemoved: (name: string) => `${name} wird entfernt.`,
  stillExists: (name: string) => `${name} gibt es weiterhin. Der Dienst hat das Löschen abgelehnt und dabei nichts verändert.`,
  deleteFolderConsequence: "Ein Ordner, in dem noch etwas liegt, wird nicht gelöscht — und ein Ordner, den eine Regel nennt, ebenso wenig. Räumen Sie ihn vorher aus oder nehmen Sie ihn aus der Regel heraus.",
  deleteTagConsequence: "Ein Tag, der noch an einem Todo hängt, wird nicht gelöscht — und ein Tag, den eine Regel nennt, ebenso wenig. Die Regel verlöre sonst still ihre Bedeutung.",
  deleted: "Gelöscht.",
  // TagInput
  tagInputPlaceholder: "Tag suchen oder eingeben …",
  unknownTag: "Unbekanntes Tag",
  chosen: (label: string) => `Gewählt: ${label}`,
  tagsLoadingDots: "Tags werden geladen …",
  showAllTags: "Alle Tags zeigen",
  tagsLoading: "Tags werden geladen",
  existingTags: "Vorhandene Tags",
  defaultTagHint: "Standard-Tag — hängt ohnehin an jedem neuen Todo.",
  moreTagsMatch: (count: number) => `Weitere ${String(count)} Tags passen ebenfalls. Tippen Sie genauer.`,
  createNew: "Neu anlegen",
  createAsTag: (name: string) => `${name} als neues Tag anlegen`,
  createHint: "Dieses Tag gibt es noch nicht. Es entsteht auf der Wurzelebene, sobald Sie speichern; verschieben lässt es sich danach unter Tags.",
  noTagYet: "Noch kein Tag angelegt.",
  noTagMatches: (name: string) => `Kein Tag passt zu ${name}.`,
  typeToCreate: "Tippen Sie einen Namen — SuperTakt bietet Ihnen dann an, ihn anzulegen.",
  createUnderBefore: "Neue Tags legen Sie unter ",
  createUnderLink: "Tags",
  createUnderAfter: " an.",
  tagsFailed: "Die Tags ließen sich nicht laden",
  noTagWithoutList: "Ohne die Liste lässt sich hier kein Tag wählen.",
  // TagTree and treeData
  level: (level: number) => `Ebene ${String(level)}`,
  levelShort: (level: number) => `E${String(level)}`,
  tagsInFolder: (count: number) => `${String(count)} Tags in diesem Ordner`,
  todosWithTagCount: (count: number) => `${String(count)} Todos mit diesem Tag`,
  dropAtRoot: "Hierher ziehen: auf die Wurzelebene",
  dragHint: "Ziehen legt einen Eintrag in einen Ordner. Stellen, die einen Ordner in sich selbst brächten, nehmen ihn erst gar nicht an. Mit der Tastatur: auswählen, dann „Verschieben“.",
  thisFolder: "diesem Ordner",
};

const en: typeof de = {
  undo: "Undo",
  placementFailed: "The placement could not be changed",
  orderOf: (name: string) => `Order of ${name}`,
  moveUp: (name: string) => `Move ${name} up`,
  moveDown: (name: string) => `Move ${name} down`,
  orderChanged: "Order changed.",
  orderMoved: (name: string, up: boolean) => `${name} is now ${up ? "higher" : "lower"}.`,
  orderMovedOnBoard: (left: boolean) => `On the board the column is now further ${left ? "left" : "right"}.`,
  orderFailed: "The order could not be changed",
  rulesTitle: "Rules",
  rulesLead: "A rule groups todos. The placement says where it appears.",
  newRule: "New rule",
  noRuleTitle: "No rule yet",
  noRuleBody: "For example everything under the folder “Customers” — or everything done that is still open.",
  firstRule: "Create first rule",
  poolEmpty: "No condition — this pool stays empty.",
  showTodos: "Show todos",
  addAsColumn: "Add as column",
  removeFromBoard: "Remove from board",
  rename: "Rename",
  editRule: "Edit rule",
  delete: "Delete",
  deleteRuleTitle: "Delete rule?",
  deleteRuleLead: (name: string) => `The rule ${name} is removed.`,
  deleteColumnConsequence: "Nothing changes on the todos — membership was never stored. The column disappears from the board; its cards stay in the todo list.",
  deletePoolConsequence: "Nothing changes on the todos. Membership was never stored.",
  ruleDeleted: "Rule deleted.",
  ruleDeleteFailed: "The rule could not be deleted",
  tagsAndFolders: "Tags and folders",
  tagsLead: "Nestable to any depth. A tag sits in exactly one folder or at the root level.",
  folder: "Folder",
  tag: "Tag",
  noTagTitle: "No tag yet",
  noTagBody: "Tags organise todos, and most rules ask about them. Without a single tag, a rule is left with only what it says about status, “Done” and the export status.",
  firstTag: "Create first tag",
  moveFailed: "Moving did not work",
  atRoot: "at the root level",
  inFolder: (name: string) => `in ${name}`,
  nowLies: (name: string, place: string) => `${name} is now ${place}.`,
  pickEntry: "Choose an entry on the left. Its actions then appear here.",
  move: "Move",
  todosWithTag: "Todos with this tag",
  newTagTitle: "Create new tag",
  newTagAtRoot: "It lands at the root level. Choosing a folder takes it deeper.",
  newTagInFolder: "It lands in the folder currently selected.",
  create: "Create",
  tagCreated: "Tag created.",
  name: "Name",
  newFolderTitle: "Create new folder",
  newFolderLead: "Folders can be nested to any depth.",
  folderCreated: "Folder created.",
  save: "Save",
  renamed: "Renamed.",
  moveTagTitle: "Move tag",
  nestFolderTitle: "Nest folder",
  moveTagLead: "A tag sits in exactly one folder. The todos that carry it stay untouched.",
  nestFolderLead: "A folder cannot go under one of its own subfolders. SuperTakt refuses that instead of creating a cycle.",
  moved: "Moved.",
  folderForTag: "Folder for this tag",
  newParentFolder: "New parent folder",
  rootLevel: "Root level",
  folderNotDeleted: "The folder was not deleted",
  tagNotDeleted: "The tag was not deleted",
  deleteFolderTitle: "Delete folder?",
  deleteTagTitle: "Delete tag?",
  willBeRemoved: (name: string) => `${name} is removed.`,
  stillExists: (name: string) => `${name} still exists. The service refused the deletion and changed nothing.`,
  deleteFolderConsequence: "A folder that still contains something is not deleted — nor is a folder a rule names. Empty it first or take it out of the rule.",
  deleteTagConsequence: "A tag that is still attached to a todo is not deleted — nor is a tag a rule names. The rule would otherwise silently lose its meaning.",
  deleted: "Deleted.",
  tagInputPlaceholder: "Search or type a tag …",
  unknownTag: "Unknown tag",
  chosen: (label: string) => `Selected: ${label}`,
  tagsLoadingDots: "Loading tags …",
  showAllTags: "Show all tags",
  tagsLoading: "Loading tags",
  existingTags: "Existing tags",
  defaultTagHint: "Default tag — attached to every new todo anyway.",
  moreTagsMatch: (count: number) => `${String(count)} more tags match as well. Type more precisely.`,
  createNew: "Create new",
  createAsTag: (name: string) => `Create ${name} as new tag`,
  createHint: "This tag does not exist yet. It is created at the root level when you save; it can be moved under Tags afterwards.",
  noTagYet: "No tag created yet.",
  noTagMatches: (name: string) => `No tag matches ${name}.`,
  typeToCreate: "Type a name — SuperTakt then offers to create it.",
  createUnderBefore: "New tags are created under ",
  createUnderLink: "Tags",
  createUnderAfter: ".",
  tagsFailed: "The tags could not be loaded",
  noTagWithoutList: "Without the list no tag can be chosen here.",
  level: (level: number) => `Level ${String(level)}`,
  levelShort: (level: number) => `L${String(level)}`,
  tagsInFolder: (count: number) => `${String(count)} tags in this folder`,
  todosWithTagCount: (count: number) => `${String(count)} todos with this tag`,
  dropAtRoot: "Drop here: at the root level",
  dragHint: "Dragging puts an entry into a folder. Places that would put a folder into itself do not accept it. With the keyboard: select, then “Move”.",
  thisFolder: "this folder",
};

export function tagTexts(): typeof de {
  return pickTexts({ de, en });
}
