import { pickTexts } from "../../lib/language";

/** UI texts of the board (A-28.2). `en` has the shape of `de`. */
const de = {
  screenTitle: "Kanban",
  lead: "Todos im Blick – nach Ihren Spalten und Prioritäten.",
  manageColumns: "Spalten verwalten",
  filtersLabel: "Kanban filtern und sortieren",
  priority: "Priorität",
  allPriorities: "Alle Prioritäten",
  noPriority: "Ohne Priorität",
  sorting: "Sortierung",
  sortPriority: "Priorität: wichtigste zuerst",
  sortUpdated: "Zuletzt geändert",
  showDone: "Erledigte einblenden",
  howColumnsWork: "Spalten verstehen",
  doneHidden: "Erledigte sind ausgeblendet; passende Spalten zeigen sie trotzdem.",
  loading: "Board wird geladen",
  stamp: "Stand",
  multipleCards: (count: number) => `${String(count)} Karten mehrfach`,
  moreCards: "Mehr Karten laden",
  recalculate: "Neu berechnen",
  highlightCleared: "Hervorhebung aufgehoben.",
  standsInColumns: (title: string, count: number, names: string) => `${title} steht in ${String(count)} Spalten: ${names}.`,

  doneUnchanged: "Tags und Status ändern sich dadurch nicht.",
  reopenedTitle: (title: string) => `${title} ist wieder offen.`,
  doneTitle: (title: string) => `${title} ist erledigt.`,
  doneStaysVisible: (unchanged: string) => `Erledigte Karten sind eingeblendet, sie bleibt also sichtbar. ${unchanged}`,
  doneDisappears: (unchanged: string) => `Sie verschwindet vom Board, bis erledigte Karten eingeblendet werden. ${unchanged}`,
  doneFailed: "Das Kennzeichen ließ sich nicht ändern",
  undo: "Rückgängig",
  placementFailed: "Der Anzeigeort ließ sich nicht ändern",

  addInColumn: "Todo in dieser Spalte anlegen",
  addOnlyFolders: "Diese Regel nennt nur Ordner. Welche Tags darin liegen, löst der Dienst auf — die Ansicht rechnet das nicht nach.",
  addWithTags: "Todo mit den Tags dieser Regel anlegen",
  rename: "Umbenennen",
  editRule: "Regel bearbeiten",
  allTodosInList: "Alle Todos dieser Regel in der Liste",
  removeFromBoard: "Vom Board nehmen",

  // BoardColumn
  ruleEmpty: "Ohne Bedingung — diese Spalte bleibt leer.",
  addInNamedColumn: (name: string) => `Todo in ${name} anlegen — mit den Tags dieser Regel`,
  noConditionTitle: "Diese Spalte hat noch keine Bedingung",
  noConditionBody: "Sie bleibt leer, bis eine dazukommt — eine Regel ohne Bedingung trifft nichts, nicht alles. Nennen Sie einen Tag, einen Ordner, einen Status, „Erledigt“ oder den Exportstatus, dann füllt sie sich von selbst.",
  addCondition: "Bedingung ergänzen",
  emptyFolderTitleOne: "Der geforderte Ordner enthält kein Tag",
  emptyFolderTitleMany: "Die geforderten Ordner enthalten kein Tag",
  emptyFolderBody: (folders: string, one: boolean) =>
    `Die Regel verlangt ein Tag aus ${folders} — dort liegt keines. Eine Bedingung, die auf keinen Tag zeigt, kann kein Todo erfüllen; daran ändert auch ein zweiter Tag oder Ordner daneben nichts. Legen Sie ein Tag in ${one ? "diesem Ordner" : "diesen Ordnern"} an oder nennen Sie in der Regel einen anderen.`,
  createTag: "Tag anlegen",
  noCardTitle: "Keine Karte trifft diese Regel",
  noCardBody: "Die Bedingungen stehen — im Augenblick erfüllt sie kein Todo. Sobald eines dazu passt, erscheint es hier von selbst.",
  // A-27.3 (E-133 point 4): an empty column under an active priority filter says so.
  filteredTitle: "Keine Karte passt zum Prioritätsfilter",
  filteredBody: "Der Prioritätsfilter oben blendet die übrigen Karten dieser Spalte aus.",
  showAllPriorities: "Alle Prioritäten zeigen",
  openTodo: "Todo öffnen",
  changeTags: "Tags ändern — sie entscheiden die Spalte",
  changeStatus: "Status ändern",
  markDone: "Als erledigt markieren",
  undoDone: "Erledigt zurücknehmen",
  clearHighlight: "Hervorhebung aufheben",
  highlightAll: "Alle Vorkommen hervorheben",

  // BoardEmptyState
  noColumnTitle: "Das Board hat noch keine Spalte",
  noColumnBody: "Sie richten die Spalten selbst ein. SuperTakt erfindet keine.",
  firstColumn: "Erste Spalte einrichten",
  noRuleTitle: "Sie haben noch keine Regel",
  noRuleBody: "Spalten entstehen aus Bedingungen wie Tags, Status, Erledigt oder Exportstatus.",
  adoptTitle: "Vorhandene Regeln als Spalte aufnehmen",
  adoptBody: "Diese Regeln gibt es bereits in Ihren Pools. Sie werden dadurch nicht kopiert — dieselbe Regel erscheint zusätzlich auf dem Board.",
  condition: "Bedingung",
  conditions: "Bedingungen",
  adopt: "Als Spalte aufnehmen",

  // BoardSetupDialog
  orderChanged: "Reihenfolge geändert.",
  orderMoved: (name: string, left: boolean) =>
    `${name} steht jetzt ${left ? "weiter links" : "weiter rechts"}. Die Position gilt auch in der Pool-Liste.`,
  orderFailed: "Die Reihenfolge ließ sich nicht ändern",
  setupTitle: "Spalten des Boards",
  newColumn: "Neue Spalte anlegen",
  close: "Schließen",
  columnsLoading: "Spalten werden geladen",
  columnsFailed: "Die Spalten ließen sich nicht laden",
  columnsFailedBody: "Ob dieses Board Spalten hat, ist gerade nicht feststellbar. Angelegt ist deshalb nichts verloren — nur ungezeigt.",
  noColumnYet: "Noch keine Spalte",
  noColumnYetBody: "Legen Sie eine an oder nehmen Sie eine vorhandene Regel auf.",
  card: "Karte",
  cards: "Karten",
  emptyFolderFault: (folders: string) => `Kein Tag in ${folders} — diese Spalte kann nichts treffen.`,
  orderOf: (name: string) => `Reihenfolge von ${name}`,
  moveLeft: (name: string) => `${name} weiter nach links verschieben`,
  moveRight: (name: string) => `${name} weiter nach rechts verschieben`,
  poolRules: "Vorhandene Pool-Regeln",
  adoptHint: "Die Regel erscheint dann zusätzlich auf dem Board.",
  orderHint: "Die Pfeile ändern die Reihenfolge auf dem Board und in der Pool-Liste.",

  // Kanban
  alsoInTitle: (names: string) => `Dieselbe Karte steht auch in: ${names}`,
  alsoIn: (count: number) =>
    count === 1 ? "Steht auch in 1 Spalte" : `Steht auch in ${String(count)} Spalten`,
  status: "Status",
  stopTimer: (title: string) => `Timer für ${title} stoppen`,
  startTimer: (title: string) => `Timer für ${title} starten`,
  cardActions: (title: string) => `Aktionen für ${title}`,
  columnName: (title: string) => `Spalte ${title}`,
  cardsLoaded: (count: number, total: number) => `${String(count)} von ${String(total)} Karten geladen`,
  cardsTotal: (total: number) => `${String(total)} Karten`,
  ofWhichDone: (count: number) => `davon ${String(count)} erledigt`,
  doneCount: (count: number) => `${String(count)} erledigt`,
  addInTitle: (title: string) => `Todo in ${title} anlegen`,
  manageColumn: (title: string) => `Spalte ${title} verwalten`,
};

const en: typeof de = {
  screenTitle: "Kanban",
  lead: "Todos at a glance – by your columns and priorities.",
  manageColumns: "Manage columns",
  filtersLabel: "Filter and sort the Kanban",
  priority: "Priority",
  allPriorities: "All priorities",
  noPriority: "No priority",
  sorting: "Sort",
  sortPriority: "Priority: most important first",
  sortUpdated: "Last changed",
  showDone: "Show done",
  howColumnsWork: "Understand columns",
  doneHidden: "Done todos are hidden; matching columns still show them.",
  loading: "Loading board",
  stamp: "As of",
  multipleCards: (count: number) => `${String(count)} cards in multiple columns`,
  moreCards: "Load more cards",
  recalculate: "Recalculate",
  highlightCleared: "Highlight cleared.",
  standsInColumns: (title: string, count: number, names: string) => `${title} is in ${String(count)} columns: ${names}.`,

  doneUnchanged: "Tags and status do not change.",
  reopenedTitle: (title: string) => `${title} is open again.`,
  doneTitle: (title: string) => `${title} is done.`,
  doneStaysVisible: (unchanged: string) => `Done cards are shown, so it stays visible. ${unchanged}`,
  doneDisappears: (unchanged: string) => `It disappears from the board until done cards are shown. ${unchanged}`,
  doneFailed: "The done flag could not be changed",
  undo: "Undo",
  placementFailed: "The placement could not be changed",

  addInColumn: "Create todo in this column",
  addOnlyFolders: "This rule names folders only. The service resolves which tags they contain — the view does not recompute that.",
  addWithTags: "Create todo with this rule's tags",
  rename: "Rename",
  editRule: "Edit rule",
  allTodosInList: "All todos of this rule in the list",
  removeFromBoard: "Remove from board",

  ruleEmpty: "No condition — this column stays empty.",
  addInNamedColumn: (name: string) => `Create todo in ${name} — with this rule's tags`,
  noConditionTitle: "This column has no condition yet",
  noConditionBody: "It stays empty until one is added — a rule without a condition matches nothing, not everything. Name a tag, a folder, a status, “Done” or the export status, and it fills by itself.",
  addCondition: "Add condition",
  emptyFolderTitleOne: "The required folder contains no tag",
  emptyFolderTitleMany: "The required folders contain no tag",
  emptyFolderBody: (folders: string, one: boolean) =>
    `The rule requires a tag from ${folders} — there is none. A condition that points to no tag cannot be met by any todo; a second tag or folder next to it does not change that. Create a tag in ${one ? "this folder" : "these folders"} or name a different one in the rule.`,
  createTag: "Create tag",
  noCardTitle: "No card matches this rule",
  noCardBody: "The conditions are set — right now no todo meets them. As soon as one fits, it appears here by itself.",
  filteredTitle: "No card matches the priority filter",
  filteredBody: "The priority filter above hides the other cards of this column.",
  showAllPriorities: "Show all priorities",
  openTodo: "Open todo",
  changeTags: "Change tags — they decide the column",
  changeStatus: "Change status",
  markDone: "Mark as done",
  undoDone: "Undo done",
  clearHighlight: "Clear highlight",
  highlightAll: "Highlight all occurrences",

  noColumnTitle: "The board has no column yet",
  noColumnBody: "You set up the columns yourself. SuperTakt invents none.",
  firstColumn: "Set up first column",
  noRuleTitle: "You have no rule yet",
  noRuleBody: "Columns are defined by conditions such as tags, status, done state or export status.",
  adoptTitle: "Add existing rules as columns",
  adoptBody: "These rules already exist in your pools. They are not copied — the same rule also appears on the board.",
  condition: "condition",
  conditions: "conditions",
  adopt: "Add as column",

  orderChanged: "Order changed.",
  orderMoved: (name: string, left: boolean) =>
    `${name} is now further ${left ? "left" : "right"}. The position also applies in the pool list.`,
  orderFailed: "The order could not be changed",
  setupTitle: "Board columns",
  newColumn: "Create new column",
  close: "Close",
  columnsLoading: "Loading columns",
  columnsFailed: "The columns could not be loaded",
  columnsFailedBody: "Whether this board has columns cannot be determined right now. Nothing that was set up is lost — it is just not shown.",
  noColumnYet: "No column yet",
  noColumnYetBody: "Create one or add an existing rule.",
  card: "card",
  cards: "cards",
  emptyFolderFault: (folders: string) => `No tag in ${folders} — this column cannot match anything.`,
  orderOf: (name: string) => `Order of ${name}`,
  moveLeft: (name: string) => `Move ${name} further left`,
  moveRight: (name: string) => `Move ${name} further right`,
  poolRules: "Existing pool rules",
  adoptHint: "The rule then also appears on the board.",
  orderHint: "The arrows change the order on the board and in the pool list.",

  alsoInTitle: (names: string) => `The same card is also in: ${names}`,
  alsoIn: (count: number) =>
    count === 1 ? "Also in 1 column" : `Also in ${String(count)} columns`,
  status: "Status",
  stopTimer: (title: string) => `Stop timer for ${title}`,
  startTimer: (title: string) => `Start timer for ${title}`,
  cardActions: (title: string) => `Actions for ${title}`,
  columnName: (title: string) => `Column ${title}`,
  cardsLoaded: (count: number, total: number) => `${String(count)} of ${String(total)} cards loaded`,
  cardsTotal: (total: number) => `${String(total)} cards`,
  ofWhichDone: (count: number) => `${String(count)} of them done`,
  doneCount: (count: number) => `${String(count)} done`,
  addInTitle: (title: string) => `Create todo in ${title}`,
  manageColumn: (title: string) => `Manage column ${title}`,
};

export function boardTexts(): typeof de {
  return pickTexts({ de, en });
}
